create or alter procedure EXTRACT_DATA_FC03000 (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable I_SQL varchar(3000);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable CODIGOPRINCIPAL integer;
declare variable MOVIMENTOESTOQUE integer;
declare variable CODIGO_GRUPO integer;
declare variable CODIGO_ESTOQUE_CLASSIFICACAO integer;
declare variable CODIGO_ESTOQUE_TIPO integer;
declare variable CODIGOBARRA varchar(30);
declare variable NOMEPRODUTO varchar(150);
declare variable NOMEPRODUTO_FRACAO varchar(150);
declare variable NOMEPRODUTO_ROTULO varchar(150);
declare variable UNIDADE varchar(7);
declare variable UNIDADE_CALCULO varchar(7);
declare variable VALORCUSTO numeric(18,4);
declare variable VALORCOMPRA numeric(18,4);
declare variable VALORVENDA numeric(18,4);
declare variable FATOREQUIV numeric(18,4);
declare variable CODIGO_ESTOQUE_PORTARIA integer;
declare variable CHECARMAX integer;
declare variable QTDEMAX integer;
declare variable UNIDADEMAX varchar(7);
declare variable CHECARMIN integer;
declare variable QTDEMIN integer;
declare variable UNIDADEMIN varchar(7);
declare variable ATIVO smallint;
declare variable CODIGO_DCB varchar(10);
declare variable CODIGO_CAS varchar(10);
declare variable CODIGO_NCM varchar(10);
declare variable NUMERO_MS varchar(20);
declare variable CONCENTRACAO numeric(18,4);
declare variable DENSIDADE numeric(18,4);
declare variable CLASSE_BIOFARMACEUTICA smallint;
declare variable USO_ATENDIMENTO smallint;
declare variable FATORCALCULO smallint;
declare variable PRINCIPIOATIVO varchar(130);
declare variable OBSERVACAO varchar(7000);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
BEGIN
              V_USER = 'SYSDBA';
              V_SHA = 'SySPs_PHARMACIE';

            /*OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE*/
            SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

            -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
            UPDATE FC03000
            SET CONVERSAO = :V_CONVERSAO
            WHERE CODIGO_PS IS NULL AND CONVERSAO IS NULL;

            UPDATE FC03000 P
            SET P.CDREGISTROMS = REPLACE(P.CDREGISTROMS,'-','');

            /*GERA O CODIGO_PS NA TABELA DE PRODUTOS DE ACORDO COM OS GRUPOS*/

            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL4, 1)+4000000
            WHERE GRUPO = 'M'
            AND UNIDA = 'UN'
            AND (DESCRPRD LIKE 'CAP %' OR
               DESCRPRD LIKE 'CAPS %')
            AND P.CODIGO_PS IS NULL;
        
            --ESTOQUE_GERAL_0
            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL0, 1)
            WHERE P.GRUPO = 'O'
            AND P.CODIGO_PS IS NULL;
        
            --ESTOQUE_GERAL_2
            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL2, 1)+2000000
            WHERE P.GRUPO = 'M'
            AND P.SETOR IN ('800','850')
            AND P.CODIGO_PS IS NULL;
        
        
            --ESTOQUE_GERAL_1
            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
            WHERE P.GRUPO = 'M'
            AND P.CODIGO_PS IS NULL;
        
        
            --ESTOQUE_GERAL_3
            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL3, 1)+3000000
            WHERE (P.GRUPO = 'R' OR
               P.GRUPO = 'D')
            AND P.CODIGO_PS IS NULL;
        
            --ESTOQUE_GERAL_4
            UPDATE FC03000 P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL4, 1)+4000000
            WHERE (P.GRUPO = 'E' OR
               P.GRUPO = 'N')
            AND P.CODIGO_PS IS NULL;

         /*QUERY QUE BUSCA E FORMATA OS DADOS DE PRODUTOS DO BANCO DE DADOS FORMULA CERTA*/

FOR
    SELECT
        CODIGO_PS AS CODIGO,
        CASE
          WHEN CODIGO_PS < 1000000 THEN 0
          WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 1
          WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 2
          WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 3
          WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 4
        END AS MOVIMENTOESTOQUE,
        CASE
          WHEN CODIGO_PS < 1000000 THEN 1
          WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
          WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
          WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
          WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_GRUPO,
        CASE
          WHEN CODIGO_PS < 1000000 THEN 1
          WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
          WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
          WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
          WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_ESTOQUE_CLASSIFICACAO,
        CASE
          WHEN CODIGO_PS < 1000000 THEN 1
          WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
          WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
          WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
          WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_ESTOQUE_TIPO,
        --EAN AS CODIGOBARRA,
        IIF(SITUA = 'I', UPPER('ZZZ-'||DESCR),UPPER(DESCR)) AS NOMEPRODUTO,
        IIF(DESCRDET IS NULL, UPPER(DESCRPRD), UPPER(DESCRDET)) AS NOMEPRODUTO_FRACAO,
        IIF(SITUA = 'I',UPPER('ZZZ-'||DESCRPRD),UPPER(DESCRPRD)) AS NOMEPRODUTO_ROTULO,
        LOWER(
            IIF(
                TRIM(UPPER(UNIDA)) IN ('UN', 'CAP'),
                'u',
                TRIM(LOWER(UNIDA))
            )
        ) AS UNIDADE,
                
               IIF(
            UNIRC IS NULL,
            LOWER(
                IIF(
                    TRIM(UPPER(UNIDA)) IN ('UN', 'CAP'),
                    'u',
                    TRIM(LOWER(UNIDA))
                )
            ),
            LOWER(
                IIF(
                    TRIM(UPPER(UNIRC)) IN ('UN', 'CAP'),
                    'u',
                    TRIM(LOWER(UNIRC))
                )
            )
        ) AS UNIDADE_CALCULO,
        PRCOM AS VALORCUSTO,
        PRCOMN AS VALORCOMPRA,
        PRVEN AS VALORVENDA,
        CASE PORTA
          WHEN 'A1' THEN IIF(GRUPO = 'M', 100001, 300001)
          WHEN 'A2' THEN IIF(GRUPO = 'M', 100002, 300002)
          WHEN 'A3' THEN IIF(GRUPO = 'M', 100003, 300003)
          WHEN 'AM' THEN IIF(GRUPO = 'M', 100004, 300004)
          WHEN 'B1' THEN IIF(GRUPO = 'M', 100005, 300005)
          WHEN 'B2' THEN IIF(GRUPO = 'M', 100006, 300006)
          WHEN 'C1' THEN IIF(GRUPO = 'M', 100007, 300007)
          WHEN 'C2' THEN IIF(GRUPO = 'M', 100008, 300008)
          WHEN 'C4' THEN IIF(GRUPO = 'M', 100010, 300010)
          WHEN 'C5' THEN IIF(GRUPO = 'M', 100011, 300011)
          WHEN 'D1' THEN IIF(GRUPO = 'M', 100012, 300012)
          WHEN 'D2' THEN IIF(GRUPO = 'M', 100013, 300013)
          WHEN 'F1' THEN IIF(GRUPO = 'M', 100014, 300014)
        END AS CODIGO_ESTOQUE_PORTARIA,
        IIF(DOMAX > 0, -1, NULL) AS CHECARMAX,
        IIF(DOMAX > 0, DOMAX, NULL) AS QTDEMAX,
        LOWER(UNIDM) AS UNIDADEMAX,
        IIF(DOMIN > 0, -1, NULL) AS CHECARMIN,
        IIF(DOMIN > 0, DOMIN, NULL) AS QTDEMIN,
        LOWER(UNIDMIN) AS UNIDADEMIN,
        CASE SITUA
          WHEN 'I' THEN 0
          WHEN 'A' THEN -1
        END AS ATIVO,
        CDDCB AS CODIGO_DCB,
        SUBSTRING(CDCAS FROM 1 FOR 10) AS CODIGO_CAS,
        CLFISC AS CODIGO_NCM,
        SUBSTRING (CDREGISTROMS FROM 1 FOR 13) AS NUMERO_MS,
        IIF(DILUICAO > 0, (100/DILUICAO), 100) AS CONCENTRACAO,
        IIF(DENSIDADE > 0, DENSIDADE, 0) AS DENSIDADE,
        CLBIOFARMA AS CLASSE_BIOFARMACEUTICA,
        -1 AS USO_ATENDIMENTO,
        IIF(GRUPO = 'M', 2, NULL) AS FATORCALCULO,
        SUBSTRING(PRINCIPIOATIVO FROM 1 FOR 129) AS PRINCIPIOATIVO,
        ESPCF AS OBSERVACAO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        DTCAD AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CURRENT_TIMESTAMP AS ALTERACAO_DT
    FROM FC03000 P
    WHERE P.CODIGO_PS IS NOT NULL AND P.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, /*$$IBEC$$ :CODIGOBARRA, $$IBEC$$*/ :NOMEPRODUTO, :NOMEPRODUTO_FRACAO, :NOMEPRODUTO_ROTULO, :UNIDADE, :UNIDADE_CALCULO, :VALORCUSTO, :VALORCOMPRA, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :CHECARMAX, :QTDEMAX, :UNIDADEMAX, :CHECARMIN, :QTDEMIN, :UNIDADEMIN, :ATIVO, :CODIGO_DCB, :CODIGO_CAS, :CODIGO_NCM, :NUMERO_MS, :CONCENTRACAO, :DENSIDADE, :CLASSE_BIOFARMACEUTICA, :USO_ATENDIMENTO, :FATORCALCULO, :PRINCIPIOATIVO, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT

            /*DE ACORDO COM OS RESULTADOS DA QUERY ACIMA ELE FAZ A INSERCAO DOS DADOS NA TABELA ESTOQUE_GERAL NO BANCO DE DADOS PHARMACIE*/
        DO
        BEGIN
            I_SQL = 'INSERT INTO ESTOQUE_GERAL(CODIGO, MOVIMENTOESTOQUE, CODIGO_GRUPO, CODIGO_ESTOQUE_CLASSIFICACAO, CODIGO_ESTOQUE_TIPO, NOMEPRODUTO, NOMEPRODUTO_FRACAO, NOMEPRODUTO_ROTULO, UNIDADE, UNIDADE_CALCULO, VALORCUSTO, VALORCOMPRA, VALORVENDA, CODIGO_ESTOQUE_PORTARIA, CHECARMAX,  QTDEMAX, UNIDADEMAX, CHECARMIN, QTDEMIN, UNIDADEMIN, ATIVO, CODIGO_DCB, CODIGO_CAS, CODIGO_NCM, NUMERO_MS, CONCENTRACAO, DENSIDADE, CLASSE_BIOFARMACEUTICA, USO_ATENDIMENTO, FATORCALCULO, PRINCIPIOATIVO, OBSERVACAO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
        
            EXECUTE STATEMENT (:I_SQL) (CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO,/*$$IBEC$$  :CODIGOBARRA,  $$IBEC$$*/:NOMEPRODUTO, :NOMEPRODUTO_FRACAO, :NOMEPRODUTO_ROTULO, :UNIDADE, :UNIDADE_CALCULO, :VALORCUSTO, :VALORCOMPRA, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :CHECARMAX, :QTDEMAX, :UNIDADEMAX, :CHECARMIN, :QTDEMIN, :UNIDADEMIN, :ATIVO, :CODIGO_DCB, :CODIGO_CAS, :CODIGO_NCM, :NUMERO_MS, :CONCENTRACAO, :DENSIDADE, :CLASSE_BIOFARMACEUTICA, :USO_ATENDIMENTO, :FATORCALCULO, :PRINCIPIOATIVO, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
        END

            -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
        UPDATE FC03200
        SET CONVERSAO = :V_CONVERSAO
        WHERE CODIGO_PRODUTO_PS IS NULL AND CONVERSAO IS NULL;


        UPDATE FC03200 S
        SET S.CODIGO_PRODUTO_PS = (SELECT P.CODIGO_PS FROM FC03000 P WHERE P.CDPRO = S.CDPRO)
        WHERE S.CODIGO_PRODUTO_PS IS NULL;

        BEGIN
        UPDATE FC03200 S
        SET S.CODIGO_SINONIMO_PS = CASE
                                WHEN CODIGO_PRODUTO_PS < 1000000 THEN GEN_ID(GEN_ESTOQUE_GERAL0, 1)
                                WHEN CODIGO_PRODUTO_PS > 1000000 AND CODIGO_PRODUTO_PS < 1999999 THEN GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
                                WHEN CODIGO_PRODUTO_PS > 2000000 AND CODIGO_PRODUTO_PS < 2999999 THEN GEN_ID(GEN_ESTOQUE_GERAL2, 1)+2000000
                              END;
        END



        FOR
            SELECT
                S.CODIGO_SINONIMO_PS AS CODIGO,
                S.CODIGO_PRODUTO_PS AS CODIGOPRINCIPAL,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 0
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 2
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 3
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 4
                END AS MOVIMENTOESTOQUE,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_GRUPO,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_CLASSIFICACAO,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_TIPO,
                --P.EAN AS CODIGOBARRA,
                IIF (P.SITUA = 'I', UPPER ('ZZZ-'||S.DESCR), UPPER(S.DESCR)) AS NOMEPRODUTO,
                IIF (P.SITUA = 'I', UPPER('ZZZ-'||S.DESCRPRD), UPPER(S.DESCRPRD)) AS NOMEPRODUTO_ROTULO,
                IIF(S.DESCR IS NULL, UPPER(S.DESCRPRD), UPPER(S.DESCR)) AS NOMEPRODUTO_FRACAO,
                LOWER(IIF(P.UNIDA = 'UN', 'u', P.UNIDA)) AS UNIDADE,
                IIF(P.UNIRC IS NULL, LOWER(IIF(P.UNIDA = 'UN', 'u', P.UNIDA)), LOWER(IIF(P.UNIRC = 'UN', 'u', P.UNIDA))) AS UNIDADE_CALCULO,
                P.PRCOM AS VALORCOMPRA,
                P.PRCOM AS VALORCUSTO,
                P.PRVEN AS VALORVENDA,
                CASE P.PORTA
                  WHEN 'A1' THEN IIF(P.GRUPO = 'M', 100001, 300001)
                  WHEN 'A2' THEN IIF(P.GRUPO = 'M', 100002, 300002)
                  WHEN 'A3' THEN IIF(P.GRUPO = 'M', 100003, 300003)
                  WHEN 'AM' THEN IIF(P.GRUPO = 'M', 100004, 300004)
                  WHEN 'B1' THEN IIF(P.GRUPO = 'M', 100005, 300005)
                  WHEN 'B2' THEN IIF(P.GRUPO = 'M', 100006, 300006)
                  WHEN 'C1' THEN IIF(P.GRUPO = 'M', 100007, 300007)
                  WHEN 'C2' THEN IIF(P.GRUPO = 'M', 100008, 300008)
                  WHEN 'C4' THEN IIF(P.GRUPO = 'M', 100010, 300010)
                  WHEN 'C5' THEN IIF(P.GRUPO = 'M', 100011, 300011)
                  WHEN 'D1' THEN IIF(P.GRUPO = 'M', 100012, 300012)
                  WHEN 'D2' THEN IIF(P.GRUPO = 'M', 100013, 300013)
                  WHEN 'F1' THEN IIF(P.GRUPO = 'M', 100014, 300014)
                END AS CODIGO_ESTOQUE_PORTARIA,
                IIF(P.DOMAX > 0, -1, NULL) AS CHECARMAX,
                IIF(P.DOMAX > 0, P.DOMAX, NULL) AS QTDEMAX,
                LOWER(P.UNIDM) AS UNIDADEMAX,
                IIF(P.DOMIN > 0, -1, NULL) AS CHECARMIN,
                IIF(P.DOMIN > 0, P.DOMIN, NULL) AS QTDEMIN,
                LOWER(P.UNIDMIN) AS UNIDADEMIN,
                CASE P.SITUA
                  WHEN 'I' THEN 0
                  WHEN 'A' THEN -1
                END AS ATIVO,
                P.CDDCB AS CODIGO_DCB,
                SUBSTRING(P.CDCAS FROM 1 FOR 10) AS CODIGO_CAS,
                P.CLFISC AS CODIGO_NCM,
                P.CDREGISTROMS AS NUMERO_MS,
                IIF(P.DILUICAO > 0, (100/P.DILUICAO), 100) AS CONCENTRACAO,
                IIF(P.DENSIDADE > 0, P.DENSIDADE, 0) AS DENSIDADE,
                P.CLBIOFARMA AS CLASSE_BIOFARMACEUTICA,
                -1 AS USO_ATENDIMENTO,
                IIF(P.GRUPO = 'M', 1, NULL) AS FATORCALCULO,
                IIF(S.EQUIV > 0, S.EQUIV, 1) AS FATOREQUIV,
                SUBSTRING(P.PRINCIPIOATIVO FROM 1 FOR 130) AS PRINCIPIOATIVO,
                P.ESPCF AS OBSERVACAO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                P.DTCAD AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
                FROM FC03000 P
                  INNER JOIN FC03200 S ON P.CODIGO_PS = S.CODIGO_PRODUTO_PS
                WHERE S.CODIGO_PRODUTO_PS  IS NOT NULL
                AND S.CODIGO_SINONIMO_PS IS NOT NULL AND S.CONVERSAO = :V_CONVERSAO
                INTO :CODIGO, :CODIGOPRINCIPAL, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, /*$$IBEC$$ :CODIGOBARRA, $$IBEC$$*/ :NOMEPRODUTO, :NOMEPRODUTO_ROTULO, :NOMEPRODUTO_FRACAO, :UNIDADE, :UNIDADE_CALCULO, :VALORCOMPRA, :VALORCUSTO, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :CHECARMAX, :QTDEMAX, :UNIDADEMAX, :CHECARMIN, :QTDEMIN, :UNIDADEMIN, :ATIVO, :CODIGO_DCB, :CODIGO_CAS, :CODIGO_NCM, :NUMERO_MS, :CONCENTRACAO, :DENSIDADE, :CLASSE_BIOFARMACEUTICA, :USO_ATENDIMENTO, :FATORCALCULO, :FATOREQUIV, :PRINCIPIOATIVO, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
                        
                    /*DE ACORDO COM OS RESULTADOS DA QUERY ACIMA ELE FAZ A INSERCAO DOS DADOS NA TABELA ESTOQUE_GERAL NO BANCO DE DADOS PHARMACIE*/
                DO
                BEGIN
                    I_SQL = 'INSERT INTO ESTOQUE_GERAL(CODIGO, CODIGOPRINCIPAL, MOVIMENTOESTOQUE, CODIGO_GRUPO, CODIGO_ESTOQUE_CLASSIFICACAO, CODIGO_ESTOQUE_TIPO, NOMEPRODUTO, NOMEPRODUTO_FRACAO, NOMEPRODUTO_ROTULO, UNIDADE, UNIDADE_CALCULO, VALORCUSTO, VALORCOMPRA, VALORVENDA, CODIGO_ESTOQUE_PORTARIA, CHECARMAX,  QTDEMAX, UNIDADEMAX, CHECARMIN, QTDEMIN, UNIDADEMIN, ATIVO, CODIGO_DCB, CODIGO_CAS, CODIGO_NCM, NUMERO_MS, CONCENTRACAO, DENSIDADE, CLASSE_BIOFARMACEUTICA, USO_ATENDIMENTO, FATORCALCULO, FATOREQUIV, PRINCIPIOATIVO, OBSERVACAO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
                
                    EXECUTE STATEMENT (:I_SQL) (CODIGO, :CODIGOPRINCIPAL, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, /*$$IBEC$$ :CODIGOBARRA $$IBEC$$*/ :NOMEPRODUTO, :NOMEPRODUTO_FRACAO, :NOMEPRODUTO_ROTULO, :UNIDADE, :UNIDADE_CALCULO, :VALORCUSTO, :VALORCOMPRA, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :CHECARMAX, :QTDEMAX, :UNIDADEMAX, :CHECARMIN, :QTDEMIN, :UNIDADEMIN, :ATIVO, :CODIGO_DCB, :CODIGO_CAS, :CODIGO_NCM, :NUMERO_MS, :CONCENTRACAO, :DENSIDADE, :CLASSE_BIOFARMACEUTICA, :USO_ATENDIMENTO, :FATORCALCULO,:FATOREQUIV, :PRINCIPIOATIVO, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END

END;