create or alter procedure EXTRACT_DATA_FC02000 (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable CODIGO_GRUPO integer;
declare variable TIPOPESSOA integer;
declare variable CPF_CNPJ varchar(20);
declare variable RG_IE varchar(20);
declare variable NOMEFORNECEDOR varchar(60);
declare variable NOMEFANTASIA varchar(60);
declare variable CONTATO1 varchar(60);
declare variable HOMEPAGE varchar(60);
declare variable EMAIL varchar(100);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable I_SQL varchar(2000);
declare variable CODIGO_CADASTRO integer;
declare variable CODIGO_CIDADE_PS integer;
declare variable TIPO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable CEP varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
declare variable OBSERVACAO varchar(300);
BEGIN
     V_USER = 'SYSDBA';
     V_SHA = 'SySPs_PHARMACIE';

    /*OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE*/
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO

    UPDATE FC02000 SET CONVERSAO = :V_CONVERSAO WHERE CONVERSAO IS NULL;

    FOR
        SELECT
            FORNECID AS CODIGO,
            500000 AS CODIGO_GRUPO,
            2 AS TIPOPESSOA,
            NRCNPJ AS CPF_CNPJ,
            NRINSCR AS RG_IE,
            RAZAO AS NOMEFORNECEDOR,
            FANTA AS NOMEFANTASIA,
            CTATO AS CONTATO1,
            HPAGE AS HOMEPAGE,
            IIF(EMAIL2 IS NOT NULL, IIF(EMAIL IS NOT NULL, EMAIL || '; ' || EMAIL2, ''), EMAIL)  AS EMAIL,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
            FROM FC02000 F
            WHERE F.CONVERSAO IS NOT NULL AND F.CONVERSAO = :V_CONVERSAO
            INTO :CODIGO, :CODIGO_GRUPO,:TIPOPESSOA, :CPF_CNPJ, :RG_IE, :NOMEFORNECEDOR, :NOMEFANTASIA, :CONTATO1, :HOMEPAGE, :EMAIL, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ,:ALTERACAO_CF, :ALTERACAO_DT
            DO
            BEGIN
                I_SQL = 'INSERT INTO FORNECEDOR(CODIGO, CODIGO_GRUPO, TIPOPESSOA, CPF_CNPJ, RG_IE, NOMEFORNECEDOR, NOMEFANTASIA, CONTATO1, HOMEPAGE, EMAIL, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
                EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_GRUPO,:TIPOPESSOA, :CPF_CNPJ, :RG_IE, :NOMEFORNECEDOR, :NOMEFANTASIA, :CONTATO1, :HOMEPAGE, :EMAIL, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ,:ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
            END

           /*PREPARATIVOS ENDERECO FORNECEDOR
             UPDATE PARA SETAR O CODIGO_CIDADE_PS NA TABELA DE ENDERECO FORNECEDOR
           */

        BEGIN
        UPDATE CIDADEESTADO CID
        SET CID.NOMECIDADE = (SELECT RETORNO FROM FN_TIRA_ACENTO(CID.NOMECIDADE));

        UPDATE FC02000 FC
        SET FC.MUNIC = (SELECT RETORNO FROM FN_TIRA_ACENTO(FC.MUNIC));

        END


           UPDATE FC02000 FC
           SET FC.CODIGO_CIDADE_PS = (SELECT FIRST 1 CID.CODIGO
                              FROM CIDADEESTADO CID
                              WHERE FC.MUNIC = CID.NOMECIDADE
                                AND FC.UNFED = CID.UF)
           WHERE FC.CODIGO_CIDADE_PS IS NULL;

           FOR
               SELECT GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                    4 AS TIPO_CADASTRO,
                    FORNECID AS CODIGO_CADASTRO,
                    --IIF(BAIRR IS NOT NULL, ENDER || ', ' || BAIRR, ENDER) AS ENDERECO,
                    SUBSTRING(IIF(MUNIC IS NOT NULL AND CODIGO_CIDADE_PS IS NULL, IIF(BAIRR IS NOT NULL AND BAIRR <> '', ENDER || ', ' || BAIRR || IIF(MUNIC IS NOT NULL AND MUNIC <> '', ', ' || MUNIC, '') || IIF(UNFED IS NOT NULL AND UNFED <> '', '-' || UNFED, ''), ENDER || IIF(MUNIC IS NOT NULL AND MUNIC <> '', ', ' || MUNIC, '') || IIF(UNFED IS NOT NULL AND UNFED <> '', '-' || UNFED, '')), IIF(BAIRR IS NOT NULL AND BAIRR <> '', ENDER || ', ' || BAIRR, ENDER)) FROM 1 FOR 100) AS ENDERECO,
                    ENDNR AS NUMERO,
                    NRCEP AS CEP,
                    ENDCP AS OBSERVACAO,
                    1 AS CODIGO_REGIAODETALHE,
                    COALESCE(CODIGO_CIDADE_PS, 1) AS CODIGO_CIDADEESTADO,
                    --1 AS CODIGO_CIDADEESTADO,
                    1 AS CADASTRO_LJ,
                    1 AS CADASTRO_CF,
                    CURRENT_TIMESTAMP AS CADASTRO_DT,
                    1 AS ALTERACAO_LJ,
                    1 AS ALTERACAO_CF,
                    CURRENT_TIMESTAMP AS ALTERACAO_DT
               FROM FC02000
               WHERE ENDER IS NOT NULL AND
               ENDER <> '.' AND
               ENDER <> ''
               AND CONVERSAO IS NOT NULL AND CONVERSAO = :V_CONVERSAO
               INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
           DO
           BEGIN
                I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, CEP, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
                EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
           END

           BEGIN
                UPDATE FC02000 SET NRDDD = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(lower(NRDDD), '*', ''), ']', ''), '[', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', ''), 'g', ''), 'h', ''), 'i', ''), 'j', ''), 'k', ''), 'l', ''), 'm', ''), 'n', ''), 'o', ''), 'p', ''), 'q', ''), 'r', ''), 's', ''), 't', ''), 'u', ''), 'v', ''), 'x', ''), 'y', ''), 'z', ''), 'w', ''), '.', ''), ',', ''), ' ', ''), '-', '');
                UPDATE FC02000 SET NRDDD2 = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(lower(NRDDD2), '*', ''), ']', ''), '[', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', ''), 'g', ''), 'h', ''), 'i', ''), 'j', ''), 'k', ''), 'l', ''), 'm', ''), 'n', ''), 'o', ''), 'p', ''), 'q', ''), 'r', ''), 's', ''), 't', ''), 'u', ''), 'v', ''), 'x', ''), 'y', ''), 'z', ''), 'w', ''), '.', ''), ',', ''), ' ', ''), '-', '');
                UPDATE FC02000 SET NRDDDFAX = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(lower(NRDDDFAX), '*', ''), ']', ''), '[', ''), 'a', ''), 'b', ''), 'c', ''), 'd', ''), 'e', ''), 'f', ''), 'g', ''), 'h', ''), 'i', ''), 'j', ''), 'k', ''), 'l', ''), 'm', ''), 'n', ''), 'o', ''), 'p', ''), 'q', ''), 'r', ''), 's', ''), 't', ''), 'u', ''), 'v', ''), 'x', ''), 'y', ''), 'z', ''), 'w', ''), '.', ''), ',', ''), ' ', ''), '-', '');
                UPDATE FC02000 SET NRTEL = REPLACE(REPLACE(NRTEL, ':', ''),'_','');
                UPDATE FC02000 SET NRTEL2 = REPLACE(REPLACE(NRTEL, ':', ''),'_','');
                UPDATE FC02000 SET NRFAX = REPLACE(REPLACE(NRTEL, ':', ''),'_','');
                UPDATE FC02000 SET NRDDD = NULL WHERE NRDDD = '' OR NRDDD = '0';
                UPDATE FC02000 SET NRDDD2 = NULL WHERE NRDDD2 = '' OR NRDDD2 = '0';
                UPDATE FC02000 SET NRDDDFAX = NULL WHERE NRDDDFAX = '' OR NRDDDFAX = '0';
                UPDATE FC02000 SET NRTEL = NULL WHERE NRTEL = '';
                UPDATE FC02000 SET NRTEL2 = NULL WHERE NRTEL2 = '';
                UPDATE FC02000 SET NRFAX = NULL WHERE NRFAX = '';
          END

            FOR
                 SELECT GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                        4 AS TIPO_CADASTRO,
                        FORNECID AS CODIGO_CADASTRO,
                        2 AS TELEFONE_TIPO,
                        IIF(SUBSTRING(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) FROM 1 FOR 1) = '0', SUBSTRING(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) FROM 2 FOR 2), SUBSTRING(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) FROM 1 FOR 2)) AS TELEFONEPREFIXO,
                        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRTEL, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS TELEFONE,
                        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RAMAL, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS OBSERVACAO,
                        1 AS CADASTRO_LJ,
                        1 AS CADASTRO_CF,
                        CURRENT_TIMESTAMP AS CADASTRO_DT,
                        1 AS ALTERACAO_LJ,
                        1 AS ALTERACAO_CF,
                        CURRENT_TIMESTAMP AS ALTERACAO_DT
                        FROM FC02000
                        WHERE NRTEL IS NOT NULL AND
                              NRTEL <> '' AND
                              NRTEL <> '0' AND
                              TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                              TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRTEL, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                              UPPER(NRDDD) NOT CONTAINING 'A' AND UPPER(NRDDD) NOT CONTAINING 'B' AND UPPER(NRDDD) NOT CONTAINING 'C' AND UPPER(NRDDD) NOT CONTAINING 'D' AND UPPER(NRDDD) NOT CONTAINING 'E' AND UPPER(NRDDD) NOT CONTAINING 'F' AND UPPER(NRDDD) NOT CONTAINING 'G' AND UPPER(NRDDD) NOT CONTAINING 'H' AND UPPER(NRDDD) NOT CONTAINING 'I' AND UPPER(NRDDD) NOT CONTAINING 'J' AND UPPER(NRDDD) NOT CONTAINING 'K' AND UPPER(NRDDD) NOT CONTAINING 'L' AND UPPER(NRDDD) NOT CONTAINING 'M' AND UPPER(NRDDD) NOT CONTAINING 'N' AND UPPER(NRDDD) NOT CONTAINING 'O' AND UPPER(NRDDD) NOT CONTAINING 'P' AND UPPER(NRDDD) NOT CONTAINING 'Q' AND UPPER(NRDDD) NOT CONTAINING 'R' AND UPPER(NRDDD) NOT CONTAINING 'S' AND UPPER(NRDDD) NOT CONTAINING 'T' AND UPPER(NRDDD) NOT CONTAINING 'U' AND UPPER(NRDDD) NOT CONTAINING 'V' AND UPPER(NRDDD) NOT CONTAINING 'X' AND UPPER(NRDDD) NOT CONTAINING 'Z' AND
                              UPPER(NRTEL) NOT CONTAINING 'A' AND UPPER(NRTEL) NOT CONTAINING 'B' AND UPPER(NRTEL) NOT CONTAINING 'C' AND UPPER(NRTEL) NOT CONTAINING 'D' AND UPPER(NRTEL) NOT CONTAINING 'E' AND UPPER(NRTEL) NOT CONTAINING 'F' AND UPPER(NRTEL) NOT CONTAINING 'G' AND UPPER(NRTEL) NOT CONTAINING 'H' AND UPPER(NRTEL) NOT CONTAINING 'I' AND UPPER(NRTEL) NOT CONTAINING 'J' AND UPPER(NRTEL) NOT CONTAINING 'K' AND UPPER(NRTEL) NOT CONTAINING 'L' AND UPPER(NRTEL) NOT CONTAINING 'M' AND UPPER(NRTEL) NOT CONTAINING 'N' AND UPPER(NRTEL) NOT CONTAINING 'O' AND UPPER(NRTEL) NOT CONTAINING 'P' AND UPPER(NRTEL) NOT CONTAINING 'Q' AND UPPER(NRTEL) NOT CONTAINING 'R' AND UPPER(NRTEL) NOT CONTAINING 'S' AND UPPER(NRTEL) NOT CONTAINING 'T' AND UPPER(NRTEL) NOT CONTAINING 'U' AND UPPER(NRTEL) NOT CONTAINING 'V' AND UPPER(NRTEL) NOT CONTAINING 'X' AND UPPER(NRTEL) NOT CONTAINING 'Z'  
                              AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NRTEL)) WHERE IS_NUM = 1)
                              AND CONVERSAO IS NOT NULL AND CONVERSAO = :V_CONVERSAO
            UNION

                SELECT GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                        4 AS TIPO_CADASTRO,
                        FORNECID AS CODIGO_CADASTRO,
                        IIF(SUBSTRING(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRTEL2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) FROM 1 FOR 1) <= 5, 2, 3) AS TELEFONE_TIPO,
                        SUBSTRING(CAST(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS INTEGER) FROM 1 FOR 2) AS TELEFONEPREFIXO,
                        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRTEL2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS TELEFONE,
                        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RAMAL2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS OBSERVACAO,
                        1 AS CADASTRO_LJ,
                        1 AS CADASTRO_CF,
                        CURRENT_TIMESTAMP AS CADASTRO_DT,
                        1 AS ALTERACAO_LJ,
                        1 AS ALTERACAO_CF,
                        CURRENT_TIMESTAMP AS ALTERACAO_DT
                        FROM FC02000
                        WHERE NRTEL2 IS NOT NULL AND
                              NRTEL2 <> '' AND
                              NRTEL2 <> '0' AND
                              TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDD2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                              TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRTEL2, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                              UPPER(NRDDD2) NOT CONTAINING 'A' AND UPPER(NRDDD2) NOT CONTAINING 'B' AND UPPER(NRDDD2) NOT CONTAINING 'C' AND UPPER(NRDDD2) NOT CONTAINING 'D' AND UPPER(NRDDD2) NOT CONTAINING 'E' AND UPPER(NRDDD2) NOT CONTAINING 'F' AND UPPER(NRDDD2) NOT CONTAINING 'G' AND UPPER(NRDDD2) NOT CONTAINING 'H' AND UPPER(NRDDD2) NOT CONTAINING 'I' AND UPPER(NRDDD2) NOT CONTAINING 'J' AND UPPER(NRDDD2) NOT CONTAINING 'K' AND UPPER(NRDDD2) NOT CONTAINING 'L' AND UPPER(NRDDD2) NOT CONTAINING 'M' AND UPPER(NRDDD2) NOT CONTAINING 'N' AND UPPER(NRDDD2) NOT CONTAINING 'O' AND UPPER(NRDDD2) NOT CONTAINING 'P' AND UPPER(NRDDD2) NOT CONTAINING 'Q' AND UPPER(NRDDD2) NOT CONTAINING 'R' AND UPPER(NRDDD2) NOT CONTAINING 'S' AND UPPER(NRDDD2) NOT CONTAINING 'T' AND UPPER(NRDDD2) NOT CONTAINING 'U' AND UPPER(NRDDD2) NOT CONTAINING 'V' AND UPPER(NRDDD2) NOT CONTAINING 'X' AND UPPER(NRDDD2) NOT CONTAINING 'Z' AND
                              UPPER(NRTEL2) NOT CONTAINING 'A' AND UPPER(NRTEL2) NOT CONTAINING 'B' AND UPPER(NRTEL2) NOT CONTAINING 'C' AND UPPER(NRTEL2) NOT CONTAINING 'D' AND UPPER(NRTEL2) NOT CONTAINING 'E' AND UPPER(NRTEL2) NOT CONTAINING 'F' AND UPPER(NRTEL2) NOT CONTAINING 'G' AND UPPER(NRTEL2) NOT CONTAINING 'H' AND UPPER(NRTEL2) NOT CONTAINING 'I' AND UPPER(NRTEL2) NOT CONTAINING 'J' AND UPPER(NRTEL2) NOT CONTAINING 'K' AND UPPER(NRTEL2) NOT CONTAINING 'L' AND UPPER(NRTEL2) NOT CONTAINING 'M' AND UPPER(NRTEL2) NOT CONTAINING 'N' AND UPPER(NRTEL2) NOT CONTAINING 'O' AND UPPER(NRTEL2) NOT CONTAINING 'P' AND UPPER(NRTEL2) NOT CONTAINING 'Q' AND UPPER(NRTEL2) NOT CONTAINING 'R' AND UPPER(NRTEL2) NOT CONTAINING 'S' AND UPPER(NRTEL2) NOT CONTAINING 'T' AND UPPER(NRTEL2) NOT CONTAINING 'U' AND UPPER(NRTEL2) NOT CONTAINING 'V' AND UPPER(NRTEL2) NOT CONTAINING 'X' AND UPPER(NRTEL2) NOT CONTAINING 'Z' 
                              AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NRTEL2)) WHERE IS_NUM = 1)
                              AND CONVERSAO IS NOT NULL AND CONVERSAO = :V_CONVERSAO
         UNION

             SELECT GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                    4 AS TIPO_CADASTRO,
                    FORNECID AS CODIGO_CADASTRO,
                    IIF(SUBSTRING(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) FROM 1 FOR 1) <= 5, 2, 3) AS TELEFONE_TIPO,
                    SUBSTRING(CAST(TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDDFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS INTEGER) FROM 1 FOR 2) AS TELEFONEPREFIXO,
                    TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS TELEFONE,
                    TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RAMALFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) AS OBSERVACAO,
                    1 AS CADASTRO_LJ,
                    1 AS CADASTRO_CF,
                    CURRENT_TIMESTAMP AS CADASTRO_DT,
                    1 AS ALTERACAO_LJ,
                    1 AS ALTERACAO_CF,
                    CURRENT_TIMESTAMP AS ALTERACAO_DT
                    FROM FC02000
                    WHERE NRFAX IS NOT NULL AND
                          NRFAX <> '0' AND
                          TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRDDDFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                          TRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NRFAX, '.', ''), ']', ''), '/', ''), ',', ''), '-', '')) <> '' AND
                          UPPER(NRDDDFAX) NOT CONTAINING 'A' AND UPPER(NRDDDFAX) NOT CONTAINING 'B' AND UPPER(NRDDDFAX) NOT CONTAINING 'C' AND UPPER(NRDDDFAX) NOT CONTAINING 'D' AND UPPER(NRDDDFAX) NOT CONTAINING 'E' AND UPPER(NRDDDFAX) NOT CONTAINING 'F' AND UPPER(NRDDDFAX) NOT CONTAINING 'G' AND UPPER(NRDDDFAX) NOT CONTAINING 'H' AND UPPER(NRDDDFAX) NOT CONTAINING 'I' AND UPPER(NRDDDFAX) NOT CONTAINING 'J' AND UPPER(NRDDDFAX) NOT CONTAINING 'K' AND UPPER(NRDDDFAX) NOT CONTAINING 'L' AND UPPER(NRDDDFAX) NOT CONTAINING 'M' AND UPPER(NRDDDFAX) NOT CONTAINING 'N' AND UPPER(NRDDDFAX) NOT CONTAINING 'O' AND UPPER(NRDDDFAX) NOT CONTAINING 'P' AND UPPER(NRDDDFAX) NOT CONTAINING 'Q' AND UPPER(NRDDDFAX) NOT CONTAINING 'R' AND UPPER(NRDDDFAX) NOT CONTAINING 'S' AND UPPER(NRDDDFAX) NOT CONTAINING 'T' AND UPPER(NRDDDFAX) NOT CONTAINING 'U' AND UPPER(NRDDDFAX) NOT CONTAINING 'V' AND UPPER(NRDDDFAX) NOT CONTAINING 'X' AND UPPER(NRDDDFAX) NOT CONTAINING 'Z' AND
                          UPPER(NRFAX) NOT CONTAINING 'A' AND UPPER(NRFAX) NOT CONTAINING 'B' AND UPPER(NRFAX) NOT CONTAINING 'C' AND UPPER(NRFAX) NOT CONTAINING 'D' AND UPPER(NRFAX) NOT CONTAINING 'E' AND UPPER(NRFAX) NOT CONTAINING 'F' AND UPPER(NRFAX) NOT CONTAINING 'G' AND UPPER(NRFAX) NOT CONTAINING 'H' AND UPPER(NRFAX) NOT CONTAINING 'I' AND UPPER(NRFAX) NOT CONTAINING 'J' AND UPPER(NRFAX) NOT CONTAINING 'K' AND UPPER(NRFAX) NOT CONTAINING 'L' AND UPPER(NRFAX) NOT CONTAINING 'M' AND UPPER(NRFAX) NOT CONTAINING 'N' AND UPPER(NRFAX) NOT CONTAINING 'O' AND UPPER(NRFAX) NOT CONTAINING 'P' AND UPPER(NRFAX) NOT CONTAINING 'Q' AND UPPER(NRFAX) NOT CONTAINING 'R' AND UPPER(NRFAX) NOT CONTAINING 'S' AND UPPER(NRFAX) NOT CONTAINING 'T' AND UPPER(NRFAX) NOT CONTAINING 'U' AND UPPER(NRFAX) NOT CONTAINING 'V' AND UPPER(NRFAX) NOT CONTAINING 'X' AND UPPER(NRFAX) NOT CONTAINING 'Z'
                          AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NRFAX)) WHERE IS_NUM = 1)
                          AND CONVERSAO IS NOT NULL AND CONVERSAO = :V_CONVERSAO
                   INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
                DO
                BEGIN
                    -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
                    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO,TIPO_CADASTRO,CODIGO_CADASTRO,TELEFONE_TIPO,TELEFONEPREFIXO,TELEFONE,OBSERVACAO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
            
                    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END
                

END;