create or alter procedure EXTRACT_DATA_FC07000 (
    V_CONVERSAO varchar(1))
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable NOMECLIENTE varchar(300);
declare variable NOMEROTULO varchar(300);
declare variable NOMEPAI varchar(300);
declare variable NOMEMAE varchar(300);
declare variable EMAIL1 varchar(300);
declare variable TIPOPESSOA integer;
declare variable CPF_CNPJ varchar(30);
declare variable RG_IE varchar(30);
declare variable CODIGO_TIPODOCUMENTO integer;
declare variable ORGAOEXPEDIDOR varchar(30);
declare variable ORGAOEXPEDIDOR_UF varchar(3);
declare variable SEXO integer;
declare variable OBSERVACAO varchar(300);
declare variable CONSUMIDORFINAL integer;
declare variable TIPODESCONTO integer;
declare variable NAOCONTRIBUINTE integer;
declare variable ATIVO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGO_GRUPO integer;
declare variable I_SQL varchar(2000);
declare variable ERROR_MESSAGE varchar(300);
declare variable CODIGO_CADASTRO integer;
declare variable CODIGO_CIDADE_PS integer;
declare variable TIPO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable CEP varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
BEGIN
     V_USER = 'SYSDBA';
     V_SHA = 'SySPs_PHARMACIE';
     
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
    UPDATE FC07000 SET CONVERSAO = :V_CONVERSAO WHERE CODIGO_PS IS NULL AND CONVERSAO IS NULL;

    -- GERA OS NOVOS CODIGOS E ATUALIZA O CAMPO CODIGO_PS PARA OS REGISTROS MARCADOS COM A CONVERSAO ATUAL
    UPDATE FC07000 C 
    SET C.CODIGO_PS = GEN_ID(GEN_CLIENTE, 1)
    WHERE C.CODIGO_PS IS NULL AND C.CONVERSAO = :V_CONVERSAO
    ORDER BY C.CDCLI ASCENDING;

        FOR 
            SELECT
            C.CODIGO_PS AS CODIGO,
            800000 AS CODIGO_GRUPO,
            NULLIF(TRIM(COALESCE(C.NOMECLI, '')), '') AS NOMECLIENTE,
            NULLIF(TRIM(COALESCE(C.NOMECLI, '')), '') AS NOMEROTULO,
            NULLIF(TRIM(COALESCE(C.NOMEPAI, '')), '') AS NOMEPAI,
            NULLIF(TRIM(COALESCE(C.NOMEMAE, '')), '') AS NOMEMAE,
            NULLIF(TRIM(COALESCE(C.EMAIL, '')), '') AS EMAIL1,
            CASE
                WHEN CAST(C.TPCLI AS VARCHAR(10)) = '1' THEN 1
                WHEN CAST(C.TPCLI AS VARCHAR(10)) = '2' THEN 2
                ELSE 1
            END AS TIPOPESSOA,
            NULLIF(TRIM(COALESCE(C.NRCNPJ, '')), '') AS CPF_CNPJ,
            NULLIF(TRIM(COALESCE(C.NRINSCR, '')), '') AS RG_IE,
            2 AS CODIGO_TIPODOCUMENTO,
            NULLIF(TRIM(COALESCE(C.OERG, '')), '') AS ORGAOEXPEDIDOR,
            NULLIF(TRIM(COALESCE(C.UFRG, '')), '') AS ORGAOEXPEDIDOR_UF,
            CASE
                WHEN C.TPSEX = 'M' THEN 1 -- Masculino
                WHEN C.TPSEX = 'F' THEN 2 -- Feminino
                ELSE 1
            END AS SEXO,
            NULLIF(TRIM(COALESCE(C.OBSERV, '')), '') AS OBSERVACAO,
            -1 AS CONSUMIDORFINAL,
            1 AS TIPODESCONTO,
            3 AS NAOCONTRIBUINTE,
            -1 AS ATIVO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            NULLIF(COALESCE(CAST(C.DTCAD AS VARCHAR(20)), ''), '') AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM FC07000 C
        WHERE C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO
        ORDER BY C.CODIGO_PS ASCENDING
        INTO :CODIGO, :CODIGO_GRUPO, :NOMECLIENTE,:NOMEROTULO, :NOMEPAI, :NOMEMAE, :EMAIL1, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CODIGO_TIPODOCUMENTO, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :SEXO, :OBSERVACAO, :CONSUMIDORFINAL, :TIPODESCONTO,:NAOCONTRIBUINTE, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF,:CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF,:ALTERACAO_DT
    DO BEGIN
        -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
        I_SQL = 'INSERT INTO CLIENTE (CODIGO, CODIGO_GRUPO, NOMECLIENTE, NOMEROTULO, NOMEPAI, NOMEMAE, EMAIL1, TIPOPESSOA, CPF_CNPJ, RG_IE, CODIGO_TIPODOCUMENTO, ORGAOEXPEDIDOR, ORGAOEXPEDIDOR_UF, SEXO, OBSERVACAO, CONSUMIDORFINAL, TIPODESCONTO, NAOCONTRIBUINTE, ATIVO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_GRUPO, :NOMECLIENTE, :NOMEROTULO, :NOMEPAI, :NOMEMAE, :EMAIL1, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CODIGO_TIPODOCUMENTO, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :SEXO, :OBSERVACAO, :CONSUMIDORFINAL, :TIPODESCONTO,:NAOCONTRIBUINTE, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF,:CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF,:ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    BEGIN
        UPDATE CIDADEESTADO CID
        SET CID.NOMECIDADE = (SELECT RETORNO FROM FN_TIRA_ACENTO(CID.NOMECIDADE));
    END

    BEGIN
        UPDATE FC07200 FC
        SET FC.MUNIC = (SELECT RETORNO FROM FN_TIRA_ACENTO(FC.MUNIC));
    END

    BEGIN
        UPDATE FC07200 FC
        SET FC.CODIGO_CIDADE_PS = (SELECT FIRST 1 CID.CODIGO
                              FROM CIDADEESTADO CID
                              WHERE FC.MUNIC = CID.NOMECIDADE
                                AND FC.UNFED = CID.UF)
        WHERE FC.CODIGO_CIDADE_PS IS NULL;
    END

    FOR SELECT
                GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                1 AS TIPO_CADASTRO,
                C.CODIGO_PS AS CODIGO_CADASTRO,
                SUBSTRING(IIF(E.MUNIC IS NOT NULL AND E.CODIGO_CIDADE_PS IS NULL,
                          IIF(E.BAIRR IS NOT NULL AND E.BAIRR <> '', E.ENDER || ', ' || E.BAIRR ||
                          IIF(E.MUNIC IS NOT NULL AND E.MUNIC <> '', ', ' || E.MUNIC, '') ||
                          IIF(E.UNFED IS NOT NULL AND E.UNFED <> '', '-' || E.UNFED, ''), E.ENDER ||
                          IIF(E.MUNIC IS NOT NULL AND E.MUNIC <> '', ', ' || E.MUNIC, '') ||
                          IIF(E.UNFED IS NOT NULL AND E.UNFED <> '', '-' || E.UNFED, '')),
                          IIF(E.BAIRR IS NOT NULL AND E.BAIRR <> '', E.ENDER || ', ' || E.BAIRR, E.ENDER))
                          FROM 1 FOR 100)
                AS ENDERECO,
                E.ENDNR AS NUMERO,
                E.NRCEP AS CEP,
                E.ENDCP AS OBSERVACAO,
                1 AS CODIGO_REGIAODETALHE,
                COALESCE(CODIGO_CIDADE_PS, 1) AS CODIGO_CIDADEESTADO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
            FROM FC07200 E
            INNER JOIN FC07000 C ON C.CDCLI = E.CDCLI
            WHERE
                ENDER IS NOT NULL AND
                ENDER <> '.' AND
                ENDER <> ''
                AND C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO
    BEGIN
         I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, CEP, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

/*$$IBEC$$     BEGIN
            UPDATE FC07200 SET NRDDD = NULL WHERE NRDDD = '' OR NRDDD = 0;
            UPDATE FC07200 SET NRDDD2 = NULL WHERE NRDDD2 = '' OR NRDDD2 = 0;
            UPDATE FC07200 SET NRDDDFAX = NULL WHERE NRDDDFAX = '' OR NRDDDFAX = 0;
            UPDATE FC07200 SET NRTEL = NULL WHERE NRTEL = '';
            UPDATE FC07200 SET NRTEL2 = NULL WHERE NRTEL2 = '';
            UPDATE FC07200 SET NRFAX = NULL WHERE NRFAX = '';
    END $$IBEC$$*/

    FOR
        SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            C.CODIGO_PS AS  CODIGO_CADASTRO,
            IIF((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL)) <= 5, 1, 3) AS TELEFONE_TIPO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(REPLACE(T.NRDDD, ' ', ''))) FROM 1 FOR 2) AS TELEFONEPREFIXO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL)) FROM 1 FOR 18) AS TELEFONE,
            (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.RAMAL)) AS OBSERVACAO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
            FROM FC07200 T
            INNER JOIN FC07000 C ON C.CDCLI = T.CDCLI
        WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL)) <> ''
        AND C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO
    UNION
        SELECT --T.NRTEL2 T.NRDDD2 T.RAMAL2
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            C.CODIGO_PS AS CODIGO_CADASTRO,
            IIF((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL2)) <= 5, 1, 3) AS TELEFONE_TIPO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(REPLACE(T.NRDDD2, ' ', ''))) FROM 1 FOR 2) AS TELEFONEPREFIXO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL)) FROM 1 FOR 18) AS TELEFONE,
            (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.RAMAL2)) AS OBSERVACAO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM FC07200 T
        INNER JOIN FC07000 C ON C.CDCLI = T.CDCLI
        WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRTEL2)) <> ''
        AND C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO
    UNION
        SELECT --T.NRFAX  T.NRDDDFAX T.RAMALFAX
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            C.CODIGO_PS AS CODIGO_CADASTRO,
            IIF((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRFAX)) <= 5, 1, 3) AS TELEFONE_TIPO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(REPLACE(T.NRDDDFAX, ' ', ''))) FROM 1 FOR 2) AS TELEFONEPREFIXO,
            SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRFAX)) FROM 1 FOR 18) AS TELEFONE,
            (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.RAMALFAX)) AS OBSERVACAO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM FC07200 T
        INNER JOIN FC07000 C ON C.CDCLI = T.CDCLI
        WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(T.NRFAX)) <> ''
        AND C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO
        INTO
            :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO
    BEGIN
        -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
        I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO,TIPO_CADASTRO,CODIGO_CADASTRO,TELEFONE_TIPO,TELEFONEPREFIXO,TELEFONE,OBSERVACAO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';

        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
END;