create or alter procedure FN_TIRA_ACENTO (
    TEXTO varchar(500))
returns (
    RETORNO varchar(500))
as
declare variable VL_ASCII smallint;
declare variable ILOOP smallint = 1;
BEGIN
  RETORNO = '';
  WHILE (ILOOP <= CHAR_LENGTH(:TEXTO)) DO
  BEGIN
    VL_ASCII = ASCII_VAL(SUBSTRING(:TEXTO FROM :ILOOP FOR 1));
    IF (:VL_ASCII BETWEEN 192 AND 196) THEN
      VL_ASCII = 65;
    IF (:VL_ASCII = 199) THEN
      VL_ASCII = 67;
    IF (:VL_ASCII BETWEEN 200 AND 203) THEN
      VL_ASCII = 69;
    IF (:VL_ASCII BETWEEN 204 AND 207) THEN
      VL_ASCII = 73;
    IF (:VL_ASCII = 209) THEN
      VL_ASCII = 78;
    IF (:VL_ASCII BETWEEN 210 AND 214) THEN
      VL_ASCII = 79;
    IF (:VL_ASCII BETWEEN 217 AND 220) THEN
      VL_ASCII = 85;
    IF (:VL_ASCII BETWEEN 224 AND 228) THEN
      VL_ASCII = 97;
    IF (:VL_ASCII = 231) THEN
      VL_ASCII = 99;
    IF (:VL_ASCII BETWEEN 232 AND 235) THEN
      VL_ASCII = 101;
    IF (:VL_ASCII BETWEEN 236 AND 239) THEN
      VL_ASCII = 105;
    IF (:VL_ASCII = 241) THEN
      VL_ASCII = 110;
    IF (:VL_ASCII BETWEEN 242 AND 246) THEN
      VL_ASCII = 111;
    IF (:VL_ASCII BETWEEN 249 AND 252) THEN
      VL_ASCII = 117;
    RETORNO = :RETORNO || ASCII_CHAR(:VL_ASCII);
    ILOOP = :ILOOP + 1;
  END
  --OPTEI POR UM RETORNO NULL
  IF (:RETORNO = '') THEN
    RETORNO = NULL;
  SUSPEND;
END