create or alter procedure UTIL_FORMATA_TEL_FC04400
as
BEGIN
    -- Limpa os campos removendo caracteres não numéricos usando STRIP_NON_NUMERIC
    UPDATE FC04400
    SET 
        NRDDD = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRDDD)),
        NRDDD2 = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRDDD2)),
        NRDDDFAX = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRDDDFAX)),
        NRTEL = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRTEL)),
        NRTEL2 = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRTEL2)),
        NRFAX = (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(NRFAX));

    -- Atualiza campos vazios ou com '0' para NULL
    UPDATE FC04400
    SET NRDDD = NULL
    WHERE NRDDD = '' OR NRDDD = '0';

    UPDATE FC04400
    SET NRDDD2 = NULL
    WHERE NRDDD2 = '' OR NRDDD2 = '0';

    UPDATE FC04400
    SET NRDDDFAX = NULL
    WHERE NRDDDFAX = '' OR NRDDDFAX = '0';

    UPDATE FC04400
    SET NRTEL = NULL
    WHERE NRTEL = '';

    UPDATE FC04400
    SET NRTEL2 = NULL
    WHERE NRTEL2 = '';

    UPDATE FC04400
    SET NRFAX = NULL
    WHERE NRFAX = '';
END;