create or alter procedure UTIL_EXTRACT_FCERTA
as
declare variable I_SQL varchar(200);
BEGIN
    BEGIN
        EXECUTE STATEMENT '
            CREATE TABLE CIDADEESTADO (
                CODIGO            INTEGER NOT NULL,
                CODIGO_IBGE       INTEGER,
                NOMECIDADE        VARCHAR(60),
                UF                VARCHAR(2),
                CODIGO_PAIS       INTEGER,
                CADASTRO_LJ       SMALLINT,
                CADASTRO_DT       TIMESTAMP,
                CADASTRO_CF       INTEGER,
                ALTERACAO_LJ      SMALLINT,
                ALTERACAO_DT      TIMESTAMP,
                ALTERACAO_CF      INTEGER,
                CODIGO_MUNICIPIO  INTEGER,
                REGISTRO_CEP      SMALLINT
            )';
    END

    BEGIN
        EXECUTE STATEMENT '
            CREATE TABLE CONEXAO (
                ALIAS     VARCHAR(60),
                IPSERVER  VARCHAR(60),
                PORTA     VARCHAR(4)
            )';
    END

        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CLIENTE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_FUNCIONARIO;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_MEDICO;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL0;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL1;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL2;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL3;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL4;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_ENDERECO;';
        EXECUTE STATEMENT 'ALTER SEQUENCE GEN_CADASTRO_ENDERECO RESTART WITH 3;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_TELEFONE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE_LA;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A1;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A2;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A3;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUEF_DETALHE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_MEDICO_ESPECIALIDADE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_MINMAX;;';
        EXECUTE STATEMENT 'ALTER SEQUENCE GEN_FUNCIONARIO RESTART WITH 1;';


        EXECUTE STATEMENT 'ALTER TABLE FC07000 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC07200 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC02000 ADD CODIGO_CIDADE_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC04400 ADD CODIGO_CIDADE_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC07200 ADD CODIGO_CIDADE_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC04000 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC04400 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03000 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03200 ADD CODIGO_PRODUTO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03200 ADD CODIGO_SINONIMO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC05000 ADD CODIGO_PRODUTO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC05000 ADD PRODUTO_NOVO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12000 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12100 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12100 ADD CODIGO_PS_A1 INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12100 ADD CODIGO_PS_MEDICO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12110 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC12110 ADD CODIGO_PS_A1 INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15000 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15100 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15100 ADD CODIGO_PS_A1 INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15100 ADD CODIGO_PS_MEDICO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15110 ADD CODIGO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC15110 ADD CODIGO_PS_A1 INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03140 ADD CODIGO_PS_LOTE INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03140 ADD CODIGO_PS_LOTE_LA INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC07000 ADD CONVERSAO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC04000 ADD CONVERSAO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03000 ADD CONVERSAO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC02000 ADD CONVERSAO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03200 ADD CONVERSAO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC07000 ADD NOVO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC04000 ADD NOVO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC03000 ADD NOVO INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC05200 ADD CODIGO_PRODUTO_PS INTEGER;';
        EXECUTE STATEMENT 'ALTER TABLE FC05000 ADD CONVERSAO SMALLINT;';
        EXECUTE STATEMENT 'ALTER TABLE CIDADEESTADO ADD CONSTRAINT PK_CIDADEESTADO PRIMARY KEY (CODIGO);';



END;