SET TERM ^ ;

create or alter procedure EXTRACT_DATA_FORNECEDOR (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable CODIGO_GRUPO integer;
declare variable TIPOPESSOA integer;
declare variable CPF_CNPJ varchar(20);
declare variable RG_IE varchar(20);
declare variable NOMEFORNECEDOR varchar(60);
declare variable NOMEFANTASIA varchar(60);
declare variable CONTATO1 varchar(60);
declare variable HOMEPAGE varchar(60);
declare variable EMAIL varchar(100);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable I_SQL varchar(2000);
declare variable CODIGO_CADASTRO integer;
declare variable CODIGO_CIDADE_PS integer;
declare variable TIPO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable CEP varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
declare variable OBSERVACAO varchar(300);
BEGIN
     V_USER = 'SYSDBA';
     V_SHA = 'masterkey';

    /*OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE*/
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO

    UPDATE T_FORNECEDOR F SET CONVERSAO = :V_CONVERSAO WHERE CONVERSAO IS NULL;

    UPDATE T_FORNECEDOR F
    SET F.CODIGO_PS = GEN_ID(GEN_FORNECEDOR,1)
    WHERE F.CODIGO_PS IS NULL
    AND F.CONVERSAO = :V_CONVERSAO;

    UPDATE T_FORNECEDOR F
    SET F.NR_INSC_ESTADUAL = REPLACE(REPLACE(REPLACE(F.NR_INSC_ESTADUAL,'.',''),'(',''),')','');

    UPDATE T_FORNECEDOR F
    SET F.NR_CNPJ = REPLACE(REPLACE(REPLACE(F.NR_INSC_ESTADUAL,'/',''),'(',''),')','');

    FOR
        SELECT
            F.CODIGO_PS AS CODIGO,
            500000 AS CODIGO_GRUPO,
            2 AS TIPOPESSOA,
            F.NR_CNPJ AS CPF_CNPJ,
            F.NR_INSC_ESTADUAL AS RG_IE,
            F.RS_FORNECEDOR AS NOMEFORNECEDOR,
            F.NM_FORNECEDOR AS NOMEFANTASIA,
            LOWER(F.DS_HOMEPAGE) AS HOMEPAGE,
            LOWER(F.DS_EMAIL)  AS EMAIL,
            F.DS_OBSERVACAO AS OBSERVACAO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
         FROM T_FORNECEDOR F
         WHERE F.CODIGO_PS IS NOT NULL
         AND F.CONVERSAO = :V_CONVERSAO
            INTO :CODIGO, :CODIGO_GRUPO,:TIPOPESSOA, :CPF_CNPJ, :RG_IE, :NOMEFORNECEDOR, :NOMEFANTASIA, :HOMEPAGE, :EMAIL, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ,:ALTERACAO_CF, :ALTERACAO_DT
            DO
            BEGIN
                I_SQL = 'INSERT INTO FORNECEDOR(CODIGO, CODIGO_GRUPO, TIPOPESSOA, CPF_CNPJ, RG_IE, NOMEFORNECEDOR, NOMEFANTASIA, HOMEPAGE, EMAIL, OBSERVACAO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
                EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_GRUPO,:TIPOPESSOA, :CPF_CNPJ, :RG_IE, :NOMEFORNECEDOR, :NOMEFANTASIA, :HOMEPAGE, :EMAIL,:OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ,:ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
            END

           /*PREPARATIVOS ENDERECO FORNECEDOR*/

        BEGIN
            UPDATE T_FORNECEDOR FC SET FC.NM_CIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(FC.NM_CIDADE));
        END
            UPDATE T_FORNECEDOR E
            SET E.CODIGO_CIDADE_PS = (SELECT FIRST 1 CID.CODIGO
                              FROM CIDADEESTADO CID
                              WHERE E.NM_CIDADE = CID.NOMECIDADE
                                AND E.NM_UF = CID.UF)
            WHERE E.CODIGO_CIDADE_PS IS NULL;

           FOR
               SELECT
                GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                4 AS TIPO_CADASTRO,
                F.CODIGO_PS AS CODIGO_CADASTRO,
                COALESCE (F.DS_ENDERECO,'')||', '||COALESCE (F.NM_BAIRRO,'') ||', '||COALESCE (F.NM_CIDADE,'') AS ENDERECO,
                'SN' AS NUMERO,
                '00000000' AS CEP,
                1 AS CODIGO_REGIAODETALHE,
                COALESCE(F.CODIGO_CIDADE_PS,1) AS CODIGO_CIDADEESTADO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
                FROM T_FORNECEDOR F
                WHERE F.DS_ENDERECO IS NOT NULL
                    AND F.CODIGO_PS IS NOT NULL
                    AND F.NM_BAIRRO IS NOT NULL
                    AND CONVERSAO = :V_CONVERSAO
               INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP,:CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
           DO
           BEGIN
                I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, CEP,CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
                EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
           END

           BEGIN
                UPDATE T_FORNECEDOR T
                SET T.NR_TELEFONE = REPLACE(REPLACE(REPLACE(T.NR_TELEFONE,'-',''),'(',''),')','');

                UPDATE T_FORNECEDOR T
                SET T.NR_TELEFONE = TRIM(T.NR_TELEFONE);
          END

            FOR
                 SELECT
                    GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                    1 AS TIPO_CADASTRO,
                    T.CODIGO_PS AS  CODIGO_CADASTRO,
                    3 AS TELEFONE_TIPO,
                        IIF(CHAR_LENGTH(NR_TELEFONE) =10,SUBSTRING (NR_TELEFONE FROM 1 FOR 2),
                        IIF(CHAR_LENGTH (NR_TELEFONE)=11,SUBSTRING (NR_TELEFONE FROM 1 FOR 2),NULL)) AS TELEFONEPREFIXO,
                    SUBSTRING (NR_TELEFONE FROM 3 FOR 11) AS TELEFONE,
                    1 AS CADASTRO_LJ,
                    1 AS CADASTRO_CF,
                    CURRENT_TIMESTAMP AS CADASTRO_DT,
                    1 AS ALTERACAO_LJ,
                    1 AS ALTERACAO_CF,
                    CURRENT_TIMESTAMP AS ALTERACAO_DT
                 FROM T_FORNECEDOR T
                 WHERE T.CODIGO_PS IS NOT NULL
                 AND T.NR_TELEFONE IS NOT NULL
                 AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NR_TELEFONE)) WHERE IS_NUM = 1)
                   INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
                DO
                BEGIN
                    -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
                    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO,TIPO_CADASTRO,CODIGO_CADASTRO,TELEFONE_TIPO,TELEFONEPREFIXO,TELEFONE,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
            
                    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END
                

END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON CONEXAO TO PROCEDURE EXTRACT_DATA_FORNECEDOR;
GRANT SELECT,UPDATE ON T_FORNECEDOR TO PROCEDURE EXTRACT_DATA_FORNECEDOR;
GRANT EXECUTE ON PROCEDURE TIRA_ACENTOS TO PROCEDURE EXTRACT_DATA_FORNECEDOR;
GRANT SELECT ON CIDADEESTADO TO PROCEDURE EXTRACT_DATA_FORNECEDOR;
GRANT EXECUTE ON PROCEDURE IS_NUMERIC TO PROCEDURE EXTRACT_DATA_FORNECEDOR;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE EXTRACT_DATA_FORNECEDOR TO SYSDBA;