create or alter procedure EXTRACT_DATA_MEDICO (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable I_SQL varchar(2000);
declare variable NOMEMEDICO varchar(255);
declare variable CRM varchar(15);
declare variable CR_ESTADO varchar(2);
declare variable SEXO varchar(2);
declare variable CODIGO_MEDICO_ESPECIALIDADE integer;
declare variable CODIGO_CONSELHO_REGIONAL integer;
declare variable CODIGO_GRUPO integer;
declare variable DIANASCIMENTO varchar(2);
declare variable MESNASCIMENTO varchar(2);
declare variable ANONASCIMENTO varchar(4);
declare variable OBSERVACAO_MED varchar(300);
declare variable ATIVO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGO_CADASTRO integer;
declare variable CODIGO_CIDADE_PS integer;
declare variable TIPO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable CEP varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
declare variable OBSERVACAO varchar(300);
BEGIN
    V_USER = 'SYSDBA';
     V_SHA = 'masterkey';

    /*OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE*/

    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
    UPDATE T_MEDICO SET CONVERSAO = :V_CONVERSAO WHERE CODIGO_PS IS NULL AND CONVERSAO IS NULL;

    /* UPDATE NO QUAL GERA O CODIGO_PS NA TABELA DO MEDICO*/

    UPDATE T_MEDICO M
        SET M.CODIGO_PS = GEN_ID(GEN_MEDICO, 1)
    WHERE M.CODIGO_PS IS NULL AND M.CONVERSAO = :V_CONVERSAO;

    /*QUERY QUE BUSCA E FORMATA INFORMACOES DE CADASTRO DE MEDICO */
    FOR
        SELECT
            M.CODIGO_PS AS CODIGO,
            UPPER (M.NM_MEDICO) AS NOMEMEDICO,
            M.NR_CRM AS CRM,
            M.NM_UF_CONSELHO AS CR_ESTADO,
            1 AS SEXO,
            1 AS CODIGO_MEDICO_ESPECIALIDADE,
            1 AS CODIGO_CONSELHO_REGIONAL,
            700000 AS CODIGO_GRUPO,
            M.DS_OBSERVACAO,
            -1 AS ATIVO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM T_MEDICO M
        WHERE M.CODIGO_PS IS NOT NULL AND M.CONVERSAO = :V_CONVERSAO
        INTO :CODIGO, :NOMEMEDICO, :CRM, :CR_ESTADO, :SEXO, :CODIGO_MEDICO_ESPECIALIDADE, :CODIGO_CONSELHO_REGIONAL, :CODIGO_GRUPO,:OBSERVACAO_MED, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
        DO BEGIN

            /*BLOCO ONDE RECEBE AS INFORMACOES DA QUERY DE CADASTRO DE MEDICO E VAI INSERINDO OS DADOS NO BANCO DE DADOS PHARMACIE*/

            I_SQL = 'INSERT INTO MEDICO (CODIGO, NOMEMEDICO, CRM, CR_ESTADO, SEXO, CODIGO_MEDICO_ESPECIALIDADE, CODIGO_CONSELHO_REGIONAL, CODIGO_GRUPO,OBSERVACAO, ATIVO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
            EXECUTE STATEMENT (:I_SQL) (:CODIGO, :NOMEMEDICO, :CRM, :CR_ESTADO, :SEXO, :CODIGO_MEDICO_ESPECIALIDADE, :CODIGO_CONSELHO_REGIONAL, :CODIGO_GRUPO,:OBSERVACAO_MED, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END
    /*UPDATE QUE VINCULA OS CODIGOS DE CIDADES DO PHARMACIE NA TABELA DE ENDERECOS DE MEDICO*/

    BEGIN
        UPDATE T_MEDICO FC
        SET FC.NM_CIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(FC.NM_CIDADE));

        UPDATE T_MEDICO E
        SET E.CODIGO_CIDADE_PS = (SELECT FIRST 1 CID.CODIGO
                              FROM CIDADEESTADO CID
                              WHERE E.NM_CIDADE = CID.NOMECIDADE
                                AND E.NM_UF = CID.UF)
        WHERE E.CODIGO_CIDADE_PS IS NULL;
    END
        FOR
            SELECT
                GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
                E.CODIGO_PS AS CODIGO_CADASTRO,
                E.DS_ENDERECO||', '||COALESCE (E.NM_BAIRRO,'') ||', '||COALESCE (E.NM_CIDADE,'') AS ENDERECO,
                'S/N' AS NUMERO,
                '00000000' AS CEP,
                1 AS CODIGO_REGIAODETALHE,
                COALESCE(E.CODIGO_CIDADE_PS,1) AS CODIGO_CIDADEESTADO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
            FROM T_MEDICO E
            WHERE E.DS_ENDERECO IS NOT NULL
                AND E.CODIGO_PS IS NOT NULL
                AND E.NM_BAIRRO IS NOT NULL
                AND E.CONVERSAO = :V_CONVERSAO
           INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP,:CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
           DO
           BEGIN
                I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, CEP, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
                EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
           END

       FOR
            SELECT
                GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
                T.CODIGO_PS AS  CODIGO_CADASTRO,
                3 AS TELEFONE_TIPO,
                    IIF(CHAR_LENGTH(NR_TELEFONE_CELULAR) =10,SUBSTRING (NR_TELEFONE_CELULAR FROM 1 FOR 2),
                    IIF(CHAR_LENGTH (NR_TELEFONE_CELULAR)=11,SUBSTRING (NR_TELEFONE_CELULAR FROM 1 FOR 2),NULL)) AS TELEFONEPREFIXO,
                SUBSTRING (NR_TELEFONE_CELULAR FROM 3 FOR 11) AS TELEFONE,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
                FROM T_MEDICO T
                WHERE T.CODIGO_PS IS NOT NULL
                AND T.NR_TELEFONE_CELULAR IS NOT NULL
                AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NR_TELEFONE_CELULAR)) WHERE IS_NUM = 1)
                AND T.CONVERSAO = :V_CONVERSAO
            UNION
            SELECT
                GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
                T.CODIGO_PS AS  CODIGO_CADASTRO,
                3 AS TELEFONE_TIPO,
                    IIF(CHAR_LENGTH(T.NR_TELEFONE_FAX) =10,SUBSTRING (T.NR_TELEFONE_FAX FROM 1 FOR 2),
                    IIF(CHAR_LENGTH (T.NR_TELEFONE_FAX)=11,SUBSTRING (T.NR_TELEFONE_FAX FROM 1 FOR 2),NULL)) AS TELEFONEPREFIXO,
                SUBSTRING (T.NR_TELEFONE_FAX FROM 3 FOR 11) AS TELEFONE,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
                FROM T_MEDICO T
                WHERE T.CODIGO_PS IS NOT NULL
                AND T.NR_TELEFONE_FAX IS NOT NULL
                AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NR_TELEFONE_FAX)) WHERE IS_NUM = 1)
                AND T.CONVERSAO = :V_CONVERSAO

                INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE,:CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
                DO
                BEGIN
                    -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
                    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, TELEFONE_TIPO, TELEFONEPREFIXO, TELEFONE , CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
            
                    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END
END