SET TERM ^ ;

create or alter procedure EXTRACT_DATA_PRODUTOS (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable I_SQL varchar(3000);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable CODIGOPRINCIPAL integer;
declare variable MOVIMENTOESTOQUE integer;
declare variable CODIGO_GRUPO integer;
declare variable CODIGO_ESTOQUE_CLASSIFICACAO integer;
declare variable CODIGO_ESTOQUE_TIPO integer;
declare variable CODIGOBARRA varchar(30);
declare variable NOMEPRODUTO varchar(150);
declare variable NOMEPRODUTO_FRACAO varchar(150);
declare variable NOMEPRODUTO_ROTULO varchar(150);
declare variable UNIDADE varchar(7);
declare variable UNIDADE_CALCULO varchar(7);
declare variable VALORCUSTO numeric(18,4);
declare variable VALORCOMPRA numeric(18,4);
declare variable VALORVENDA numeric(18,4);
declare variable FATOREQUIV numeric(18,4);
declare variable CODIGO_ESTOQUE_PORTARIA integer;
declare variable CHECARMAX integer;
declare variable QTDEMAX integer;
declare variable UNIDADEMAX varchar(7);
declare variable CHECARMIN integer;
declare variable QTDEMIN integer;
declare variable UNIDADEMIN varchar(7);
declare variable ATIVO smallint;
declare variable CODIGO_DCB varchar(20);
declare variable CODIGO_CAS varchar(20);
declare variable CODIGO_NCM varchar(20);
declare variable NUMERO_MS varchar(20);
declare variable CONCENTRACAO numeric(18,4);
declare variable DENSIDADE numeric(18,4);
declare variable CLASSE_BIOFARMACEUTICA smallint;
declare variable USO_ATENDIMENTO smallint;
declare variable FATORCALCULO smallint;
declare variable PRINCIPIOATIVO varchar(130);
declare variable OBSERVACAO varchar(7000);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGO_CEST varchar(1000);
BEGIN
              V_USER = 'SYSDBA';
              V_SHA = 'masterkey';

            /*OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE*/
            SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

            -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
            UPDATE T_PRODUTO
            SET CONVERSAO = :V_CONVERSAO
            WHERE CODIGO_PS IS NULL AND CONVERSAO IS NULL;

            /*GERA O CODIGO_PS NA TABELA DE PRODUTOS DE ACORDO COM OS GRUPOS*/
        
            --ESTOQUE_GERAL_0
            UPDATE T_PRODUTO P
            SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL0, 1)
            WHERE P.CD_GRUPO IN (9,10)
            AND P.CODIGO_PS IS NULL;

            --ESTOQUE_GERAL_1
            UPDATE T_PRODUTO P
               SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
            WHERE P.CD_GRUPO = 1
              AND P.CODIGO_PS IS NULL;
            
            --ESTOQUE_GERAL_2
            UPDATE T_PRODUTO P
               SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL2, 1)+2000000
            WHERE P.CD_GRUPO in (3,4)
              AND P.CODIGO_PS IS NULL;
            
            --ESTOQUE_GERAL_3
            UPDATE T_PRODUTO P
               SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL3, 1)+3000000
            WHERE P.CD_GRUPO = 5
              AND P.CODIGO_PS IS NULL;
            
            --ESTOQUE_GERAL_4
            UPDATE T_PRODUTO P
               SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL4, 1)+4000000
            WHERE P.CD_GRUPO = 2
              AND P.CODIGO_PS IS NULL;

/*$$IBEC$$             UPDATE T_PRODUTO
                SET VL_VENDA = 
            CASE
        -- Se o valor for nulo ou não for numérico, definir como 0.00
            WHEN VL_VENDA IS NULL OR VL_VENDA NOT SIMILAR TO '[0-9]*[.,]?[0-9]*' THEN '0.00'
            ELSE VL_VENDA
            END
            WHERE VL_VENDA IS NULL OR VL_VENDA NOT SIMILAR TO '[0-9]*[.,]?[0-9]*'; $$IBEC$$*/


         /*QUERY QUE BUSCA E FORMATA OS DADOS DE PRODUTOS DO BANCO DE DADOS FORMULA CERTA*/

        FOR
            SELECT
                CODIGO_PS AS CODIGO,
                CASE
                  WHEN CODIGO_PS < 1000000 THEN 0
                  WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 1
                  WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 2
                  WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 3
                  WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 4
                END AS MOVIMENTOESTOQUE,
                CASE
                  WHEN CODIGO_PS < 1000000 THEN 1
                  WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
                  WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
                  WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
                  WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
                END AS CODIGO_GRUPO,
                CASE
                  WHEN CODIGO_PS < 1000000 THEN 1
                  WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
                  WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
                  WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
                  WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_CLASSIFICACAO,
                CASE
                  WHEN CODIGO_PS < 1000000 THEN 1
                  WHEN CODIGO_PS > 1000000 AND CODIGO_PS < 1999999 THEN 100000
                  WHEN CODIGO_PS > 2000000 AND CODIGO_PS < 2999999 THEN 200000
                  WHEN CODIGO_PS > 3000000 AND CODIGO_PS < 3999999 THEN 300000
                  WHEN CODIGO_PS > 4000000 AND CODIGO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_TIPO,
                COALESCE (P.CD_BARRA,NULL)  AS CODIGOBARRA,
                IIF(P.ID_SITUACAO = 'I', UPPER('ZZZ-'||P.DS_PRODUTO),UPPER(P.DS_PRODUTO)) AS NOMEPRODUTO,
                P.DS_PRODUTO AS NOMEPRODUTO_FRACAO,
                IIF(P.ID_SITUACAO = 'I', UPPER('ZZZ-'||P.DS_PRODUTO),UPPER(P.DS_PRODUTO)) AS NOMEPRODUTO_ROTULO,
                CAST (P.VL_CUSTO AS NUMERIC(18,4)) AS VALORCUSTO,
                CAST (P.VL_CUSTO AS NUMERIC(18,4)) AS VALORCOMPRA,
                CAST (P.VL_VENDA AS NUMERIC(18,4)) AS VALORVENDA,
                CASE P.CD_PSICOTROPICO
                      WHEN 1    THEN 100001
                      WHEN 2    THEN 100002
                      WHEN 3    THEN 100003
                      WHEN 12   THEN 100004
                      WHEN 4    THEN 100005
                      WHEN 5    THEN 100006
                      WHEN 6    THEN 100007
                      WHEN 7    THEN 100008
                      WHEN 9    THEN 100010
                      WHEN 10   THEN 100011
                      WHEN 11   THEN 100012
                      ELSE NULL
                END AS CODIGO_ESTOQUE_PORTARIA,
                CASE
                WHEN P.ID_SITUACAO = 'A' THEN -1
                WHEN P.ID_SITUACAO = 'I' THEN 0
                END AS ATIVO,
                IIF (P.CD_DCB = '', NULL, P.CD_DCB) AS CODIGO_DCB,
                P.NR_NCM AS CODIGO_NCM,
                P.CD_CEST AS CODIGO_CEST,
                100 AS CONCENTRACAO,
                IIF (P.NR_DENSIDADE IS NULL,1,P.NR_DENSIDADE) AS DENSIDADE,
                -1 AS USO_ATENDIMENTO,
                2 AS FATORCALCULO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_DATE AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
            FROM T_PRODUTO P
            WHERE P.CODIGO_PS IS NOT NULL AND P.CONVERSAO = :V_CONVERSAO
            INTO :CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :CODIGOBARRA, :NOMEPRODUTO, :NOMEPRODUTO_FRACAO, :NOMEPRODUTO_ROTULO,:VALORCUSTO, :VALORCOMPRA, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :ATIVO, :CODIGO_DCB, :CODIGO_NCM, :CODIGO_CEST, :CONCENTRACAO, :DENSIDADE, :USO_ATENDIMENTO, :FATORCALCULO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT

            /*DE ACORDO COM OS RESULTADOS DA QUERY ACIMA ELE FAZ A INSERCAO DOS DADOS NA TABELA ESTOQUE_GERAL NO BANCO DE DADOS PHARMACIE*/
        DO
        BEGIN
            I_SQL = 'INSERT INTO ESTOQUE_GERAL(CODIGO, MOVIMENTOESTOQUE, CODIGO_GRUPO, CODIGO_ESTOQUE_CLASSIFICACAO, CODIGO_ESTOQUE_TIPO, CODIGOBARRA, NOMEPRODUTO, NOMEPRODUTO_FRACAO, NOMEPRODUTO_ROTULO, VALORCUSTO, VALORCOMPRA, VALORVENDA, CODIGO_ESTOQUE_PORTARIA, ATIVO, CODIGO_DCB, CODIGO_NCM, CODIGO_CEST, CONCENTRACAO, DENSIDADE, USO_ATENDIMENTO, FATORCALCULO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
        
            EXECUTE STATEMENT (:I_SQL) (CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :CODIGOBARRA, :NOMEPRODUTO, :NOMEPRODUTO_FRACAO, :NOMEPRODUTO_ROTULO, :VALORCUSTO, :VALORCOMPRA, :VALORVENDA, :CODIGO_ESTOQUE_PORTARIA, :ATIVO, :CODIGO_DCB, :CODIGO_NCM, :CODIGO_CEST, :CONCENTRACAO, :DENSIDADE, :USO_ATENDIMENTO, :FATORCALCULO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
        END

            -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
        UPDATE T_MATERIA_PRIMA_SINONIMO S
        SET CONVERSAO = :V_CONVERSAO
        WHERE CODIGO_PRODUTO_PS IS NULL AND CONVERSAO IS NULL;


        UPDATE T_MATERIA_PRIMA_SINONIMO S
        SET S.CODIGO_PRODUTO_PS = (SELECT P.CODIGO_PS FROM T_PRODUTO P WHERE P.CD_PRODUTO = S.CD_PRODUTO)
        WHERE S.CODIGO_PRODUTO_PS IS NULL;

        BEGIN
        UPDATE T_MATERIA_PRIMA_SINONIMO S
            SET S.CODIGO_SINONIMO_PS = CASE
                                WHEN CODIGO_PRODUTO_PS < 1000000 THEN GEN_ID(GEN_ESTOQUE_GERAL0, 1)
                                WHEN CODIGO_PRODUTO_PS > 1000000 AND CODIGO_PRODUTO_PS < 1999999 THEN GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
                                WHEN CODIGO_PRODUTO_PS > 2000000 AND CODIGO_PRODUTO_PS < 2999999 THEN GEN_ID(GEN_ESTOQUE_GERAL2, 1)+2000000
                                WHEN CODIGO_PRODUTO_PS > 3000000 AND CODIGO_PRODUTO_PS < 3999999 THEN GEN_ID(GEN_ESTOQUE_GERAL3, 1)+3000000
                                WHEN CODIGO_PRODUTO_PS > 4000000 AND CODIGO_PRODUTO_PS < 4999999 THEN GEN_ID(GEN_ESTOQUE_GERAL4, 1)+4000000
                              END
        WHERE S.CODIGO_SINONIMO_PS IS NULL;
        END

        FOR
            SELECT
                S.CODIGO_SINONIMO_PS AS CODIGO,
                S.CODIGO_PRODUTO_PS AS CODIGOPRINCIPAL,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 0
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 2
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 3
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 4
                END AS MOVIMENTOESTOQUE,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_GRUPO,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_CLASSIFICACAO,
                CASE
                  WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
                  WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
                  WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
                  WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
                  WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
                END AS CODIGO_ESTOQUE_TIPO,
                IIF(MP.ID_SITUACAO = 'I', UPPER('ZZZ-'||S.DS_SINONIMO),UPPER(S.DS_SINONIMO)) AS NOMEPRODUTO,
                IIF(MP.ID_SITUACAO = 'I', UPPER('ZZZ-'||S.DS_SINONIMO),UPPER(S.DS_SINONIMO)) AS NOMEPRODUTO_ROTULO,
                CASE
                WHEN MP.ID_SITUACAO = 'A' THEN -1
                WHEN MP.ID_SITUACAO = 'I' THEN 0
                END AS ATIVO,
                -1 AS USO_ATENDIMENTO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
                CURRENT_TIMESTAMP AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
                CURRENT_TIMESTAMP AS ALTERACAO_DT
                FROM T_PRODUTO MP
                INNER JOIN T_MATERIA_PRIMA_SINONIMO S ON S.CD_PRODUTO = MP.CD_PRODUTO
                AND S.CODIGO_SINONIMO_PS IS NOT NULL AND S.CONVERSAO = :V_CONVERSAO
                INTO :CODIGO, :CODIGOPRINCIPAL, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :NOMEPRODUTO, :NOMEPRODUTO_ROTULO, :ATIVO, :USO_ATENDIMENTO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
                        
                    /*DE ACORDO COM OS RESULTADOS DA QUERY ACIMA ELE FAZ A INSERCAO DOS DADOS NA TABELA ESTOQUE_GERAL NO BANCO DE DADOS PHARMACIE*/
                DO
                BEGIN
                    I_SQL = 'INSERT INTO ESTOQUE_GERAL(CODIGO, CODIGOPRINCIPAL, MOVIMENTOESTOQUE, CODIGO_GRUPO, CODIGO_ESTOQUE_CLASSIFICACAO, CODIGO_ESTOQUE_TIPO, NOMEPRODUTO, NOMEPRODUTO_ROTULO, ATIVO, USO_ATENDIMENTO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
                
                    EXECUTE STATEMENT (:I_SQL) (CODIGO, :CODIGOPRINCIPAL, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :NOMEPRODUTO, :NOMEPRODUTO_ROTULO, :ATIVO, :USO_ATENDIMENTO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END

END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON CONEXAO TO PROCEDURE EXTRACT_DATA_PRODUTOS;
GRANT SELECT,UPDATE ON T_PRODUTO TO PROCEDURE EXTRACT_DATA_PRODUTOS;
GRANT SELECT,UPDATE ON T_MATERIA_PRIMA_SINONIMO TO PROCEDURE EXTRACT_DATA_PRODUTOS;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE EXTRACT_DATA_PRODUTOS TO SYSDBA;