SET TERM ^ ;

create or alter procedure EXTRACT_DATA_CLIENTE (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable CODIGO integer;
declare variable NOMECLIENTE varchar(300);
declare variable NOMEROTULO varchar(300);
declare variable NOMEPAI varchar(300);
declare variable NOMEMAE varchar(300);
declare variable EMAIL1 varchar(300);
declare variable TIPOPESSOA integer;
declare variable CPF_CNPJ varchar(30);
declare variable RG_IE varchar(30);
declare variable CODIGO_TIPODOCUMENTO integer;
declare variable ORGAOEXPEDIDOR varchar(30);
declare variable ORGAOEXPEDIDOR_UF varchar(3);
declare variable SEXO integer;
declare variable OBSERVACAO varchar(300);
declare variable CONSUMIDORFINAL integer;
declare variable TIPODESCONTO integer;
declare variable NAOCONTRIBUINTE integer;
declare variable ATIVO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGO_GRUPO integer;
declare variable I_SQL varchar(2000);
declare variable ERROR_MESSAGE varchar(300);
declare variable CODIGO_CADASTRO integer;
declare variable CODIGO_CIDADE_PS integer;
declare variable TIPO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable CEP varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
BEGIN
     V_USER = 'SYSDBA';
     V_SHA = 'masterkey';
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- ATUALIZA O CAMPO CONVERSAO COM O VALOR FORNECIDO
    UPDATE T_CLIENTE SET CONVERSAO = :V_CONVERSAO WHERE CODIGO_PS IS NULL AND CONVERSAO IS NULL;

    -- GERA OS NOVOS CODIGOS E ATUALIZA O CAMPO CODIGO_PS PARA OS REGISTROS MARCADOS COM A CONVERSAO ATUAL
    UPDATE T_CLIENTE C
    SET C.CODIGO_PS = GEN_ID(GEN_CLIENTE,1)
    WHERE C.CODIGO_PS IS NULL AND C.CONVERSAO = :V_CONVERSAO;

    UPDATE T_CLIENTE_PES_FISICA CPF SET CPF.NR_RG = REPLACE(REPLACE(CPF.NR_RG,'-',''),'.','');

    FOR 
        SELECT
            CODIGO_PS AS CODIGO,
            800000 AS CODIGO_GRUPO,
            NM_CLIENTE AS NOMECLIENTE,
            NM_CLIENTE AS NOMEROTULO,
            IIF (DS_EMAIL IS NULL, NULL, UPPER(DS_EMAIL)) AS EMAIL1,
            1 AS TIPOPESSOA,
            IIF(CPF.NR_CPF = 0, NULL, CAST(CPF.NR_CPF_CHAR AS VARCHAR(20))) AS CPF_CNPJ,
             CPF.NR_RG AS RG_IE,
            2 AS CODIGO_TIPODOCUMENTO,
            IIF (CPF.NM_ORGAO_EXPEDITOR IS NULL,'SSP',NM_ORGAO_EXPEDITOR) AS ORGAOEXPEDIDOR,
            CPF.NM_UF_ORGAO_EXPEDIDOR AS ORGAOEXPEDIDOR_UF,
            CASE DS_PRONOME_TRATAMENTO
              WHEN 'Sr.' THEN 1
              WHEN 'Sra.' THEN 2
              ELSE '0'
            END AS SEXO,
            DS_OBSERVACOES AS OBSERVACAO,
            -1 AS CONSUMIDORFINAL,
            1 AS TIPODESCONTO,
            3 AS NAOCONTRIBUINTE,
            -1 AS ATIVO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_DATE AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
    FROM T_CLIENTE C
    LEFT JOIN T_CLIENTE_PES_FISICA CPF ON CPF.CD_CLIENTE = C.CD_CLIENTE
    WHERE C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :V_CONVERSAO AND C.CD_CLIENTE IS NOT NULL
    INTO :CODIGO, :CODIGO_GRUPO, :NOMECLIENTE,:NOMEROTULO,:EMAIL1, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CODIGO_TIPODOCUMENTO, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :SEXO, :OBSERVACAO, :CONSUMIDORFINAL, :TIPODESCONTO,:NAOCONTRIBUINTE, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF,:CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF,:ALTERACAO_DT
        DO BEGIN
            -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
            I_SQL = 'INSERT INTO CLIENTE (CODIGO, CODIGO_GRUPO, NOMECLIENTE, NOMEROTULO, EMAIL1, TIPOPESSOA, CPF_CNPJ, RG_IE, CODIGO_TIPODOCUMENTO, ORGAOEXPEDIDOR, ORGAOEXPEDIDOR_UF, SEXO, OBSERVACAO, CONSUMIDORFINAL, TIPODESCONTO, NAOCONTRIBUINTE, ATIVO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
            EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_GRUPO, :NOMECLIENTE, :NOMEROTULO, :EMAIL1, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CODIGO_TIPODOCUMENTO, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :SEXO, :OBSERVACAO, :CONSUMIDORFINAL, :TIPODESCONTO,:NAOCONTRIBUINTE, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF,:CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF,:ALTERACAO_DT)ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
        END

    BEGIN
        UPDATE CIDADEESTADO CID
        SET CID.NOMECIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(CID.NOMECIDADE));
    END

    BEGIN
        UPDATE T_CLIENTE FC SET FC.NM_CIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(FC.NM_CIDADE));
    END

    BEGIN
        UPDATE T_CLIENTE E
        SET E.CODIGO_CIDADE_PS = (SELECT FIRST 1 CID.CODIGO
                              FROM CIDADEESTADO CID
                              WHERE E.NM_CIDADE = CID.NOMECIDADE
                                AND E.NM_UF = CID.UF)
        WHERE E.CODIGO_CIDADE_PS IS NULL;
        UPDATE T_CLIENTE E SET E.NR_CEP = REPLACE(E.NR_CEP,'.','');
    END

    FOR
        SELECT
            GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            E.CODIGO_PS AS CODIGO_CADASTRO,
            E.DS_ENDERECO||', '||COALESCE (E.NM_BAIRRO,'') ||', '||COALESCE (E.NM_CIDADE,'') AS ENDERECO,
            IIF(E.NR_ENDERECO IS NULL,'S/N',E.NR_ENDERECO) AS NUMERO,
            IIF (E.NR_CEP_CHAR IS NULL or E.NR_CEP = 0,'00000000',E.NR_CEP_CHAR) AS CEP,
            E.DS_OBSERVACOES AS OBSERVACAO,
            1 AS CODIGO_REGIAODETALHE,
            COALESCE(E.CODIGO_CIDADE_PS,1) AS CODIGO_CIDADEESTADO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM T_CLIENTE E
        WHERE E.DS_ENDERECO IS NOT NULL
            AND E.CODIGO_PS IS NOT NULL
            AND E.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO
        BEGIN
         I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, CEP, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :CEP, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
        END

    BEGIN
        UPDATE T_CLIENTE T
        SET T.NR_TELEFONE_CELULAR = REPLACE(REPLACE(REPLACE(REPLACE(t.NR_TELEFONE_CELULAR,'-',''),'(',''),')',''),'.','');

        UPDATE T_CLIENTE t
        SET T.NR_TELEFONE_CELULAR = TRIM (T.NR_TELEFONE_CELULAR);

    END

    FOR
        SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            T.CODIGO_PS AS  CODIGO_CADASTRO,
            3 AS TELEFONE_TIPO,
            IIF(CHAR_LENGTH(NR_TELEFONE_CELULAR) =10,SUBSTRING (NR_TELEFONE_CELULAR FROM 1 FOR 2),
            IIF(CHAR_LENGTH (NR_TELEFONE_CELULAR)=11,SUBSTRING (NR_TELEFONE_CELULAR FROM 1 FOR 2),NULL)) AS TELEFONEPREFIXO,
            SUBSTRING (NR_TELEFONE_CELULAR FROM 3 FOR 11) AS TELEFONE,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM T_CLIENTE T
        WHERE T.CODIGO_PS IS NOT NULL
        AND T.NR_TELEFONE_CELULAR IS NOT NULL
        AND T.NR_TELEFONE_CELULAR <> ''
        AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NR_TELEFONE_CELULAR)) WHERE IS_NUM = 1)
        UNION
        SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
            T.CODIGO_PS AS  CODIGO_CADASTRO,
            3 AS TELEFONE_TIPO,
            IIF(CHAR_LENGTH(NR_TELEFONE) =10,SUBSTRING (NR_TELEFONE FROM 1 FOR 2),
            IIF(CHAR_LENGTH (NR_TELEFONE)=11,SUBSTRING (NR_TELEFONE FROM 1 FOR 2),NULL)) AS TELEFONEPREFIXO,
            SUBSTRING (NR_TELEFONE FROM 3 FOR 11) AS TELEFONE,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
            CURRENT_TIMESTAMP AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
            CURRENT_TIMESTAMP AS ALTERACAO_DT
        FROM T_CLIENTE T
        WHERE T.CODIGO_PS IS NOT NULL
        AND T.NR_TELEFONE IS NOT NULL
        AND T.NR_TELEFONE <> ''
        AND EXISTS (SELECT 1 FROM IS_NUMERIC(TRIM(NR_TELEFONE)) WHERE IS_NUM = 1)


        INTO
            :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE,:CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO
    BEGIN
        -- FAZ A INSERCAO DOS DADOS NO BANCO DE DADOS PHARMACIE
        I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO,TIPO_CADASTRO,CODIGO_CADASTRO,TELEFONE_TIPO,TELEFONEPREFIXO,TELEFONE,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';

        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON CONEXAO TO PROCEDURE EXTRACT_DATA_CLIENTE;
GRANT SELECT,UPDATE ON T_CLIENTE TO PROCEDURE EXTRACT_DATA_CLIENTE;
GRANT SELECT,UPDATE ON T_CLIENTE_PES_FISICA TO PROCEDURE EXTRACT_DATA_CLIENTE;
GRANT SELECT,UPDATE ON CIDADEESTADO TO PROCEDURE EXTRACT_DATA_CLIENTE;
GRANT EXECUTE ON PROCEDURE TIRA_ACENTOS TO PROCEDURE EXTRACT_DATA_CLIENTE;
GRANT EXECUTE ON PROCEDURE IS_NUMERIC TO PROCEDURE EXTRACT_DATA_CLIENTE;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE EXTRACT_DATA_CLIENTE TO SYSDBA;