CREATE OR ALTER PROCEDURE UPDATE_CODIGOS (
    CONVERSAO_IP SMALLINT,
    TIPO_ATUALIZACAO SMALLINT)
RETURNS (MENSAGEM_RETORNO VARCHAR(1000))
AS
DECLARE VARIABLE V_USER VARCHAR(20);
DECLARE VARIABLE V_SHA VARCHAR(20);
DECLARE VARIABLE V_SQL VARCHAR(3000);
DECLARE VARIABLE CD_CLIENTE INTEGER;
DECLARE VARIABLE CD_MEDICO INTEGER;
DECLARE VARIABLE CD_FORNECEDOR INTEGER;
DECLARE VARIABLE CD_PRODUTO INTEGER;
DECLARE VARIABLE CD_SINONIMO INTEGER;
DECLARE VARIABLE CODIGO_PS INTEGER;
DECLARE VARIABLE CODIGO_PRODUTO_PS INTEGER;
DECLARE VARIABLE CODIGO_SINONIMO_PS INTEGER;
DECLARE VARIABLE CODIGO_CIDADE_PS INTEGER;
DECLARE VARIABLE CONVERSAO INTEGER;
DECLARE VARIABLE CON VARCHAR(120);

DECLARE VARIABLE CONTADOR_CLIENTES INTEGER;
DECLARE VARIABLE CONTADOR_MEDICOS INTEGER;
DECLARE VARIABLE CONTADOR_FORNECEDORES INTEGER;
DECLARE VARIABLE CONTADOR_PRODUTOS INTEGER;
DECLARE VARIABLE CONTADOR_SINONIMOS INTEGER;
BEGIN
/*
    -- LEGENDA DO PROCEDIMENTO --

    NOME: UPDATE_CODIGOS

    OBJETIVO:
    ATUALIZA OS CÓDIGOS DE CONVERSÃO E REFERÊNCIAS DE ENTIDADES (CLIENTE, MÉDICO,
    FORNECEDOR, ETC.) EM UM BANCO DE DADOS EXTERNO. A LÓGICA É BASEADA NA LEITURA
    DE DADOS DO BANCO DE DADOS LOCAL E NA EXECUÇÃO DE COMANDOS DE UPDATE NO BANCO
    DE DADOS DE DESTINO.

    PARÂMETROS DE ENTRADA:
    - CONVERSAO_IP SMALLINT: O VALOR DO CAMPO CONVERSAO QUE SERÁ USADO PARA
      FILTRAR OS REGISTROS A SEREM ATUALIZADOS (POR EXEMPLO, 1, 2, 3).
    - TIPO_ATUALIZACAO SMALLINT: CONTROLA QUAIS TABELAS SERÃO PROCESSADAS.
      VALORES ACEITOS:
      0 = ATUALIZA TODAS AS TABELAS (CLIENTE, MÉDICO, FORNECEDOR, ETC.).
      1 = APENAS A TABELA T_CLIENTE.
      2 = APENAS A TABELA T_MEDICO.
      3 = APENAS A TABELA T_FORNECEDOR.
      4 = APENAS A TABELA T_PRODUTO.
      5 = APENAS A TABELA T_MATERIA_PRIMA_SINONIMO.

    RETORNO:
    RETORNA UMA ÚNICA LINHA COM UMA MENSAGEM DE TEXTO (VARCHAR) CONTENDO UM
    RESUMO DA QUANTIDADE DE REGISTROS ATUALIZADOS PARA CADA TABELA PROCESSADA.
*/
    -- INICIALIZA OS CONTADORES
    CONTADOR_CLIENTES = 0;
    CONTADOR_MEDICOS = 0;
    CONTADOR_FORNECEDORES = 0;
    CONTADOR_PRODUTOS = 0;
    CONTADOR_SINONIMOS = 0;
    MENSAGEM_RETORNO = '';

    /* OBTEM E MONTA STRING DE CONEXAO DO PHARMACIE */
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS FROM CONEXAO CN INTO :CON;

    -- DEFINE AS CREDENCIAIS PARA O BANCO DE DADOS EXTERNO
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';

    IF (:TIPO_ATUALIZACAO = 0 OR :TIPO_ATUALIZACAO = 1) THEN
    BEGIN
        -- LOOP PARA LER OS DADOS DA TABELA T_CLIENTE
        FOR SELECT
            C.CD_CLIENTE,
            C.CODIGO_PS,
            C.CONVERSAO,
            COALESCE (C.CODIGO_CIDADE_PS, 1)
        FROM T_CLIENTE C
        WHERE C.CODIGO_PS IS NOT NULL AND C.CONVERSAO = :CONVERSAO_IP
        INTO :CD_CLIENTE, :CODIGO_PS, :CONVERSAO, :CODIGO_CIDADE_PS
        DO
        BEGIN
            V_SQL = 'UPDATE T_CLIENTE SET CODIGO_PS = ' || :CODIGO_PS || ', CONVERSAO = ' || :CONVERSAO || ', CODIGO_CIDADE_PS = ' || :CODIGO_CIDADE_PS || ' WHERE CD_CLIENTE = ' || :CD_CLIENTE;
            
            EXECUTE STATEMENT (:V_SQL)
            ON EXTERNAL :CON
            AS USER :V_USER PASSWORD :V_SHA
            WITH COMMON TRANSACTION;

            -- INCREMENTA O CONTADOR DE CLIENTES
            CONTADOR_CLIENTES = CONTADOR_CLIENTES + 1;
        END
        MENSAGEM_RETORNO = MENSAGEM_RETORNO || 'CLIENTES ATUALIZADOS: ' || CONTADOR_CLIENTES || ASCII_CHAR(13) || ASCII_CHAR(10);
    END

    IF (:TIPO_ATUALIZACAO = 0 OR :TIPO_ATUALIZACAO = 2) THEN
    BEGIN
        -- LOOP PARA LER OS DADOS DA TABELA T_MEDICO
        FOR SELECT
            M.CD_MEDICO,
            M.CODIGO_PS,
            M.CONVERSAO,
            COALESCE (M.CODIGO_CIDADE_PS, 1)
        FROM T_MEDICO M
        WHERE M.CODIGO_PS IS NOT NULL AND M.CONVERSAO = :CONVERSAO_IP
        INTO :CD_MEDICO, :CODIGO_PS, :CONVERSAO, :CODIGO_CIDADE_PS
        DO
        BEGIN
            V_SQL = 'UPDATE T_MEDICO SET CODIGO_PS = ' || :CODIGO_PS || ', CONVERSAO = ' || :CONVERSAO || ', CODIGO_CIDADE_PS = ' || :CODIGO_CIDADE_PS || ' WHERE CD_MEDICO = ' || :CD_MEDICO;

            EXECUTE STATEMENT (:V_SQL)
            ON EXTERNAL :CON
            AS USER :V_USER PASSWORD :V_SHA
            WITH COMMON TRANSACTION;

            -- INCREMENTA O CONTADOR DE MEDICOS
            CONTADOR_MEDICOS = CONTADOR_MEDICOS + 1;
        END
        MENSAGEM_RETORNO = MENSAGEM_RETORNO || 'MEDICOS ATUALIZADOS: ' || CONTADOR_MEDICOS || ASCII_CHAR(13) || ASCII_CHAR(10);
    END
    
    IF (:TIPO_ATUALIZACAO = 0 OR :TIPO_ATUALIZACAO = 3) THEN
    BEGIN
        -- LOOP PARA LER OS DADOS DA TABELA T_FORNECEDOR
        FOR SELECT
            F.CD_FORNECEDOR,
            F.CODIGO_PS,
            F.CONVERSAO,
            COALESCE (F.CODIGO_CIDADE_PS, 1)
        FROM T_FORNECEDOR F
        WHERE F.CODIGO_PS IS NOT NULL AND F.CONVERSAO = :CONVERSAO_IP
        INTO :CD_FORNECEDOR, :CODIGO_PS, :CONVERSAO, :CODIGO_CIDADE_PS
        DO
        BEGIN
            V_SQL = 'UPDATE T_FORNECEDOR SET CODIGO_PS = ' || :CODIGO_PS || ', CONVERSAO = ' || :CONVERSAO || ', CODIGO_CIDADE_PS = ' || :CODIGO_CIDADE_PS || ' WHERE CD_FORNECEDOR = ' || :CD_FORNECEDOR;

            EXECUTE STATEMENT (:V_SQL)
            ON EXTERNAL :CON
            AS USER :V_USER PASSWORD :V_SHA
            WITH COMMON TRANSACTION;
            
            -- INCREMENTA O CONTADOR DE FORNECEDORES
            CONTADOR_FORNECEDORES = CONTADOR_FORNECEDORES + 1;
        END
        MENSAGEM_RETORNO = MENSAGEM_RETORNO || 'FORNECEDORES ATUALIZADOS: ' || CONTADOR_FORNECEDORES || ASCII_CHAR(13) || ASCII_CHAR(10);
    END

    IF (:TIPO_ATUALIZACAO = 0 OR :TIPO_ATUALIZACAO = 4) THEN
    BEGIN
        -- LOOP PARA LER OS DADOS DA TABELA T_PRODUTO
        FOR SELECT
            P.CD_PRODUTO,
            P.CODIGO_PS,
            P.CONVERSAO
        FROM T_PRODUTO P
        WHERE P.CODIGO_PS IS NOT NULL AND P.CONVERSAO = :CONVERSAO_IP
        INTO :CD_PRODUTO, :CODIGO_PS, :CONVERSAO
        DO
        BEGIN
            V_SQL = 'UPDATE T_PRODUTO SET CODIGO_PS = ' || :CODIGO_PS || ', CONVERSAO = ' || :CONVERSAO || ' WHERE CD_PRODUTO = ' || :CD_PRODUTO;

            EXECUTE STATEMENT (:V_SQL)
            ON EXTERNAL :CON
            AS USER :V_USER PASSWORD :V_SHA
            WITH COMMON TRANSACTION;
            
            -- INCREMENTA O CONTADOR DE PRODUTOS
            CONTADOR_PRODUTOS = CONTADOR_PRODUTOS + 1;
        END
        MENSAGEM_RETORNO = MENSAGEM_RETORNO || 'PRODUTOS ATUALIZADOS: ' || CONTADOR_PRODUTOS || ASCII_CHAR(13) || ASCII_CHAR(10);
    END
    
    IF (:TIPO_ATUALIZACAO = 0 OR :TIPO_ATUALIZACAO = 5) THEN
    BEGIN
        -- LOOP PARA LER OS DADOS DA TABELA T_MATERIA_PRIMA_SINONIMO
        FOR SELECT
            S.CD_PRODUTO,
            S.CD_SINONIMO,
            S.CODIGO_PRODUTO_PS,
            S.CODIGO_SINONIMO_PS,
            S.CONVERSAO
        FROM T_MATERIA_PRIMA_SINONIMO S
        WHERE S.CODIGO_SINONIMO_PS IS NOT NULL AND S.CONVERSAO = :CONVERSAO_IP
        INTO :CD_PRODUTO, :CD_SINONIMO, :CODIGO_PRODUTO_PS, :CODIGO_SINONIMO_PS, :CONVERSAO
        DO
        BEGIN
            V_SQL = 'UPDATE T_MATERIA_PRIMA_SINONIMO SET CODIGO_PRODUTO_PS = ' || :CODIGO_PRODUTO_PS || ', CODIGO_SINONIMO_PS = ' || :CODIGO_SINONIMO_PS || ', CONVERSAO = ' || :CONVERSAO || ' WHERE CD_PRODUTO = ' || :CD_PRODUTO || ' AND CD_SINONIMO = ' || :CD_SINONIMO;

            EXECUTE STATEMENT (:V_SQL)
            ON EXTERNAL :CON
            AS USER :V_USER PASSWORD :V_SHA
            WITH COMMON TRANSACTION;
            
            -- INCREMENTA O CONTADOR DE SINONIMOS
            CONTADOR_SINONIMOS = CONTADOR_SINONIMOS + 1;
        END
        MENSAGEM_RETORNO = MENSAGEM_RETORNO || 'SINONIMOS ATUALIZADOS: ' || CONTADOR_SINONIMOS || ASCII_CHAR(13) || ASCII_CHAR(10);
    END
    
    -- RETORNA A MENSAGEM FINAL COM A CONTAGEM DE REGISTROS ATUALIZADOS
    SUSPEND;
END;