SET TERM ^ ;

create or alter procedure UTIL_EXTRACT_INTUICTIVE
as
declare variable I_SQL varchar(200);
BEGIN
    BEGIN
        EXECUTE STATEMENT '
            CREATE TABLE CIDADEESTADO (
                CODIGO            INTEGER NOT NULL,
                CODIGO_IBGE       INTEGER,
                NOMECIDADE        VARCHAR(60),
                UF                VARCHAR(2),
                CODIGO_PAIS       INTEGER,
                CADASTRO_LJ       SMALLINT,
                CADASTRO_DT       TIMESTAMP,
                CADASTRO_CF       INTEGER,
                ALTERACAO_LJ      SMALLINT,
                ALTERACAO_DT      TIMESTAMP,
                ALTERACAO_CF      INTEGER,
                CODIGO_MUNICIPIO  INTEGER,
                REGISTRO_CEP      SMALLINT
            )';
    END

    BEGIN
        EXECUTE STATEMENT '
            CREATE TABLE CONEXAO (
                ALIAS     VARCHAR(60),
                IPSERVER  VARCHAR(60),
                PORTA     VARCHAR(4)
            )';
    END

        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CLIENTE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_FUNCIONARIO;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_MEDICO;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL0;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL1;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL2;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL3;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL4;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_ENDERECO;';
        EXECUTE STATEMENT 'ALTER SEQUENCE GEN_CADASTRO_ENDERECO RESTART WITH 2;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_TELEFONE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE_LA;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A1;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A2;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A3;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUEF_DETALHE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_MEDICO_ESPECIALIDADE;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_MINMAX;';
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_FORNECEDOR';                          
        EXECUTE STATEMENT 'ALTER SEQUENCE GEN_FUNCIONARIO RESTART WITH 1;';



		
EXECUTE STATEMENT	'ALTER TABLE T_CLIENTE ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_MEDICO ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_FORNECEDOR ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_PRODUTO ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_CLIENTE ADD CODIGO_CIDADE_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_MEDICO ADD CODIGO_CIDADE_PS INTEGER'; 
EXECUTE STATEMENT	'ALTER TABLE T_FORNECEDOR ADD CODIGO_CIDADE_PS INTEGER'; 
EXECUTE STATEMENT	'ALTER TABLE T_PRODUTO ADD CODIGO_CIDADE_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_MATERIA_PRIMA_SINONIMO ADD CODIGO_PRODUTO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_MATERIA_PRIMA_SINONIMO ADD CODIGO_SINONIMO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORCAMENTO ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORC_ITEM ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORC_ITEM ADD CODIGO_PS_A1 INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORC_ITEM ADD CODIGO_MEDICO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORC_MATERIA_PRIMA ADD CODIGO_PS INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_ORC_MATERIA_PRIMA ADD CODIGO_PS_A1 INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_PRODUTO_LOTE ADD CODIGO_PS_LOTE INTEGER';
EXECUTE STATEMENT	'ALTER TABLE T_CLIENTE ADD CONVERSAO INTEGER';
EXECUTE STATEMENT   'ALTER TABLE T_MEDICO ADD CONVERSAO SMALLINT';
EXECUTE STATEMENT   'ALTER TABLE T_FORNECEDOR ADD CONVERSAO SMALLINT';
EXECUTE STATEMENT   'ALTER TABLE T_PRODUTO ADD CONVERSAO SMALLINT';
EXECUTE STATEMENT  'ALTER TABLE T_MATERIA_PRIMA_SINONIMO ADD CONVERSAO SMALLINT';










END^

SET TERM ; ^

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE UTIL_EXTRACT_INTUICTIVE TO SYSDBA;