create or alter procedure EXTRACT_DATA_REFAZER (
    V_CONVERSAO numeric(18,2))
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable MSG_ERRO varchar(100);
declare variable CODIGO integer;
declare variable CADASTRO_DT timestamp;
declare variable CODIGO_CLIENTE integer;
declare variable OBSERVACAO varchar(7000);
declare variable CODIGO_MEDICO integer;
declare variable CODIGO_REF_A1 integer;
declare variable NUMEROFORMULA integer;
declare variable CODIGO_FORMAFARMACEUTICA integer;
declare variable QVD numeric(18,4);
declare variable OBSERVACAOFORMULA blob sub_type 1 segment size 80;
declare variable POSOLOGIA blob sub_type 1 segment size 80;
declare variable TEXTOROTULO blob sub_type 1 segment size 80;
declare variable CODIGO_PRODUTO integer;
declare variable QUANTIDADE numeric(18,4);
declare variable UNIDADE varchar(20);
declare variable INCLUSAOSISTEMA integer;
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
    -- OBTEM STRING DE CONEXAO
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
    FROM CONEXAO CN 
    INTO :CON;
    
    IF (:CON IS NULL OR :CON = '') THEN
    BEGIN
        MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
        SUSPEND;
        EXIT;
    END
    ELSE
    BEGIN
        MSG_ERRO = 'CONEXÃO OK: ' || :CON;
    END  

    -- ATUALIZA CAMPO CONVERSAO PARA VENDA (registros sem CODIGO_PS)
    BEGIN
        UPDATE VENDA A1 SET A1.CONVERSAO = :V_CONVERSAO 
        WHERE A1.CODIGO_PS IS NULL AND EXISTS (
            SELECT A2.NUMEROVENDA FROM FORMULAVENDA A2 
            WHERE A2.NUMEROVENDA = A1.NUMEROVENDA
        ) AND EXISTS(
            SELECT C.CODIGOCLIENTE FROM CLIENTE C 
            WHERE C.CODIGOCLIENTE = A1.CODIGOCLIENTE
        );
    WHEN ANY DO BEGIN END END
    
    -- ATUALIZA CAMPO CONVERSAO PARA FORMULAVENDA (registros sem CODIGO_PS_A1)
    BEGIN
        UPDATE FORMULAVENDA A2 SET A2.CONVERSAO = :V_CONVERSAO 
        WHERE A2.CODIGO_PS_A1 IS NULL AND EXISTS (
            SELECT A1.CODIGO_PS FROM VENDA A1 
            WHERE A1.NUMEROVENDA = A2.NUMEROVENDA AND A1.CONVERSAO = :V_CONVERSAO
        );
    WHEN ANY DO BEGIN END END
    
    -- ATUALIZA CAMPO CONVERSAO PARA ITEMFORMULAVENDA (registros sem CODIGO_PS_A1)
    BEGIN
        UPDATE ITEMFORMULAVENDA A3 SET A3.CONVERSAO = :V_CONVERSAO 
        WHERE A3.CODIGO_PS_A1 IS NULL AND EXISTS (
            SELECT A1.CODIGO_PS FROM VENDA A1 
            WHERE A1.NUMEROVENDA = A3.NUMEROVENDA AND A1.CONVERSAO = :V_CONVERSAO
        ) AND EXISTS (
            SELECT P.CODIGO_PS FROM PRODUTO P 
            WHERE P.CODIGOPRODUTO = A3.CODIGOPRODUTO AND P.CODIGOGRUPO = A3.CODIGOGRUPO
        );
    WHEN ANY DO BEGIN END END
    
    -- GERA CODIGO_PS PARA VENDA (registros com CONVERSAO)
    BEGIN
        UPDATE VENDA A1
        SET A1.CODIGO_PS = GEN_ID(GEN_REFAZER_A1, 1),
            A1.CODIGO_MEDICO = (SELECT FIRST 1 M.CODIGO_PS FROM FORMULAVENDA A22 INNER JOIN MEDICO M ON M.CODIGOMEDICO = A22.CODIGOMEDICO WHERE A22.NUMEROVENDA = A1.NUMEROVENDA)
        WHERE A1.CONVERSAO = :V_CONVERSAO
          AND A1.CODIGO_PS IS NULL
          AND EXISTS (SELECT A2.NUMEROVENDA
                      FROM FORMULAVENDA A2
                      WHERE A2.NUMEROVENDA = A1.NUMEROVENDA)
          AND EXISTS(SELECT C.CODIGOCLIENTE
                     FROM CLIENTE C
                     WHERE C.CODIGOCLIENTE = A1.CODIGOCLIENTE);
    WHEN ANY DO BEGIN END END
    
    -- GERA CODIGO_PS PARA FORMULAVENDA (registros com CONVERSAO)
    BEGIN
        UPDATE FORMULAVENDA A2
        SET A2.CODIGO_PS = GEN_ID(GEN_REFAZER_A2, 1),
            A2.CODIGO_PS_A1 = (SELECT FIRST 1 A1.CODIGO_PS
                               FROM VENDA A1
                               WHERE A1.NUMEROVENDA = A2.NUMEROVENDA AND
                                     A1.CODIGO_PS IS NOT NULL)
        WHERE A2.CONVERSAO = :V_CONVERSAO
          AND A2.CODIGO_PS IS NULL
          AND EXISTS (SELECT FIRST 1 A1.CODIGO_PS
                      FROM VENDA A1
                      WHERE A1.NUMEROVENDA = A2.NUMEROVENDA AND
                            A1.CODIGO_PS IS NOT NULL);
    WHEN ANY DO BEGIN END END
    
    -- GERA CODIGO_PS PARA ITEMFORMULAVENDA (registros com CONVERSAO)
    BEGIN
        UPDATE ITEMFORMULAVENDA A3
        SET A3.CODIGO_PS = GEN_ID(GEN_REFAZER_A3, 1),
            A3.CODIGO_PS_A1 = (SELECT FIRST 1 A1.CODIGO_PS
                               FROM VENDA A1
                               WHERE A1.NUMEROVENDA = A3.NUMEROVENDA AND
                                     A1.CODIGO_PS IS NOT NULL)
        WHERE A3.CONVERSAO = :V_CONVERSAO
          AND A3.CODIGO_PS IS NULL
          AND EXISTS (SELECT FIRST 1 A1.CODIGO_PS
                      FROM VENDA A1
                      WHERE A1.NUMEROVENDA = A3.NUMEROVENDA AND
                            A1.CODIGO_PS IS NOT NULL)
          AND EXISTS (SELECT FIRST 1 P.CODIGO_PS
                      FROM PRODUTO P
                      WHERE P.CODIGOPRODUTO = A3.CODIGOPRODUTO AND P.CODIGOGRUPO = A3.CODIGOGRUPO AND P.CODIGO_PS < 4000000)
        ORDER BY A3.NUMEROVENDA ASC;
    WHEN ANY DO BEGIN END END
    
    -- EXTRAI VENDAS (ATENDIMENTO_REF_A1)
    I_SQL = 'INSERT INTO ATENDIMENTO_REF_A1 (CODIGO, CADASTRO_DT, CODIGO_CLIENTE, OBSERVACAO, CODIGO_MEDICO) VALUES (?, ?, ?, ?, ?)';
    
    FOR SELECT
        A1.CODIGO_PS AS CODIGO,
        A1.DATAEMISSAOVENDA AS CADASTRO_DT,
        C.CODIGO_PS AS CODIGO_CLIENTE,
        '### VALOR BRUTO: R$ ' || 
          CAST(COALESCE(A1.VALORBRUTOVENDA, 0) AS NUMERIC(18,2)) ||
        ' | DESCONTO: R$ ' || 
          CAST(COALESCE(A1.VALORDESCONTOVENDA, 0) AS NUMERIC(18,2)) ||
        ' | VALOR LIQUIDO: R$ ' || 
          CAST(COALESCE(A1.VALORLIQUIDOVENDA, 0) AS NUMERIC(18,2)) ||
        ' ###' AS OBSERVACAO,
        COALESCE(A1.CODIGO_MEDICO, 9999999) AS CODIGO_MEDICO
    FROM VENDA A1
    INNER JOIN CLIENTE C ON C.CODIGOCLIENTE = A1.CODIGOCLIENTE
    WHERE A1.CODIGO_PS IS NOT NULL AND A1.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :CADASTRO_DT, :CODIGO_CLIENTE, :OBSERVACAO, :CODIGO_MEDICO
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CADASTRO_DT, :CODIGO_CLIENTE, :OBSERVACAO, :CODIGO_MEDICO) 
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    -- EXTRAI FORMULAS (ATENDIMENTO_REF_A2)
    I_SQL = 'INSERT INTO ATENDIMENTO_REF_A2 (CODIGO, CODIGO_REF_A1, NUMEROFORMULA, CODIGO_FORMAFARMACEUTICA, QVD, OBSERVACAOFORMULA, POSOLOGIA, TEXTOROTULO) VALUES (?, ?, ?, ?, ?, ?, ?,?)';
    
    FOR SELECT
        A2.CODIGO_PS AS CODIGO,
        A2.CODIGO_PS_A1 AS CODIGO_REF_A1,
        A2.NUMEROFORMULA AS NUMEROFORMULA,
        FF.CODIGO_PS AS CODIGO_FORMAFARMACEUTICA,
        CAST(
        CASE
            WHEN A2.QUANTIDADEFORMULA IS NOT NULL THEN A2.QUANTIDADEFORMULA
            WHEN A2.QUANTIDADECAPSULASFORMULA IS NOT NULL THEN A2.QUANTIDADECAPSULASFORMULA
            ELSE A2.VOLUMEBASEFORMULA
        END 
        AS NUMERIC(18,4)) AS QVD,
        TRIM(
            COALESCE(
                '### VALOR FÓRMULA: R$ ' || 
                CAST(A2.VALORLIQUIDOFORMULA AS NUMERIC(18,2)) || ' ###', ''
            )
            || 
            CASE 
                WHEN A2.OBSERVACAOFORMULA IS NOT NULL AND A2.OBSERVACAOFORMULA <> '' 
                THEN ASCII_CHAR(10) || CAST(A2.OBSERVACAOFORMULA AS VARCHAR(7000))
                ELSE '' 
            END
        ) AS OBSERVACAOFORMULA,
        COALESCE(UPPER(PS.DESCRICAOPOSOLOGIA), '') AS POSOLOGIA,
        (SELECT TEXTO_LIMPO FROM UTIL_LIMPA_RTF (A2.ETIQUETAFORMULA)) AS TEXTOROTULO
    FROM FORMULAVENDA A2
    INNER JOIN POSOLOGIA PS ON PS.CODIGOPOSOLOGIA = A2.CODIGOPOSOLOGIA
    INNER JOIN FORMAFARMACEUTICA FF ON FF.CODIGOFORMA = A2.CODIGOFORMA
    WHERE A2.CODIGO_PS IS NOT NULL AND A2.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :CODIGO_REF_A1, :NUMEROFORMULA, :CODIGO_FORMAFARMACEUTICA, :QVD, :OBSERVACAOFORMULA, :POSOLOGIA, :TEXTOROTULO
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_REF_A1, :NUMEROFORMULA, :CODIGO_FORMAFARMACEUTICA, :QVD, :OBSERVACAOFORMULA, :POSOLOGIA, :TEXTOROTULO)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    -- EXTRAI ITENS (ATENDIMENTO_REF_A3)
    I_SQL = 'INSERT INTO ATENDIMENTO_REF_A3 (CODIGO, CODIGO_REF_A1, CODIGO_PRODUTO, QUANTIDADE, UNIDADE, NUMEROFORMULA, INCLUSAOSISTEMA) VALUES (?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT
        A3.CODIGO_PS AS CODIGO,
        A3.CODIGO_PS_A1 AS CODIGO_REF_A1,
        P.CODIGO_PS AS CODIGO_PRODUTO,
        CAST(COALESCE(A3.QUANTIDADE, A3.DINAMIZACAO) AS NUMERIC(18,4)) AS QUANTIDADE,
        LOWER(
            IIF(
                A3.CALCULOITEM = 0, '%',
                IIF(A3.CALCULOITEM = 2, 'qsp(g)',
                    CASE
                        WHEN P.SIGLAUNIDADE = 'UN' THEN 'u'
                        WHEN A3.SIGLAUNIDADE IS NULL THEN COALESCE(A3.METODO, P.SIGLAUNIDADE)
                        ELSE  A3.SIGLAUNIDADE
                    END
                )
            )
        ) AS UNIDADE,
        A3.NUMEROFORMULA AS NUMEROFORMULA,
        0 AS INCLUSAOSISTEMA
    FROM ITEMFORMULAVENDA A3
    INNER JOIN PRODUTO P ON P.CODIGOPRODUTO = A3.CODIGOPRODUTO AND P.CODIGOGRUPO = A3.CODIGOGRUPO
    WHERE A3.CODIGO_PS IS NOT NULL AND A3.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :CODIGO_REF_A1, :CODIGO_PRODUTO, :QUANTIDADE, :UNIDADE, :NUMEROFORMULA, :INCLUSAOSISTEMA
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_REF_A1, :CODIGO_PRODUTO, :QUANTIDADE, :UNIDADE, :NUMEROFORMULA, :INCLUSAOSISTEMA) 
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
END;