create or alter procedure EXTRACT_DATA_PRODUTO (
    V_CONVERSAO numeric(18,4))
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable CODIGO integer;
declare variable MOVIMENTOESTOQUE integer;
declare variable CODIGO_GRUPO integer;
declare variable CODIGO_ESTOQUE_CLASSIFICACAO integer;
declare variable CODIGO_ESTOQUE_TIPO integer;
declare variable NOMEPRODUTO varchar(300);
declare variable NOMEPRODUTO_ROTULO varchar(300);
declare variable NOMEPRODUTO_FRACAO varchar(300);
declare variable CODIGO_NCM varchar(20);
declare variable CODIGO_DCB varchar(20);
declare variable CODIGOBARRA varchar(50);
declare variable CODIGO_ESTOQUE_PORTARIA integer;
declare variable FRACAOVENDA integer;
declare variable UNIDADE varchar(10);
declare variable UNIDADE_CALCULO varchar(10);
declare variable VALORCOMPRA numeric(18,4);
declare variable VALORCUSTO numeric(18,4);
declare variable VALORVENDA numeric(18,4);
declare variable UTR numeric(18,4);
declare variable UI numeric(18,4);
declare variable DENSIDADE numeric(18,4);
declare variable CONCENTRACAO numeric(18,4);
declare variable FATOREQUIV numeric(18,4);
declare variable FATOREQUIV_UC numeric(18,4);
declare variable FATORCALCULO integer;
declare variable ESTOQUEMINIMO integer;
declare variable QTDEMAX integer;
declare variable QTDEMAXP integer;
declare variable CHECARMAX integer;
declare variable CARACTERISTICA varchar(7000);
declare variable OBSERVACAO varchar(7000);
declare variable USO_ATENDIMENTO integer;
declare variable ATIVO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGOPRINCIPAL integer;
declare variable MSG_ERRO varchar(100);
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
        -- OBTEM STRING DE CONEXAO
        SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
        FROM CONEXAO CN 
        INTO :CON;
        
        IF (:CON IS NULL OR :CON = '') THEN
        BEGIN
            MSG_ERRO = 'CONEXAO BANCO DE DADOS PHARMACIE NAO CONFIGURADA';
            SUSPEND;
            EXIT;
        END
        ELSE
        BEGIN
            MSG_ERRO = 'CONEXAO OK: ' || :CON;
        END

    -- ATUALIZA CAMPO CONVERSAO
    BEGIN
        UPDATE PRODUTO P 
        SET P.CONVERSAO = :V_CONVERSAO 
        WHERE P.CODIGO_PS IS NULL;
    WHEN ANY DO BEGIN END
    END

    BEGIN
        UPDATE SINONIMO S 
        SET S.CONVERSAO = :V_CONVERSAO 
        WHERE S.CODIGO_PRODUTO_PS IS NULL;
    WHEN ANY DO BEGIN END
    END
    -- ESTOQUE_GERAL_0 (MOVIMENTOESTOQUE = 0)
    BEGIN
        UPDATE PRODUTO P
        SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL0, 1)
        WHERE P.CODIGO_PS IS NULL
          AND P.CONVERSAO = :V_CONVERSAO
          AND EXISTS (
            SELECT 1
            FROM GRUPO_PHARMACIE G
            WHERE G.CODIGOGRUPO = P.CODIGOGRUPO
              AND G.MOVIMENTOESTOQUE = 0
          );
    WHEN ANY DO BEGIN END
    END

    -- ESTOQUE_GERAL_1 (MOVIMENTOESTOQUE = 1)
    BEGIN
        UPDATE PRODUTO P
        SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL1, 1) + 1000000
        WHERE P.CODIGO_PS IS NULL
          AND P.CONVERSAO = :V_CONVERSAO
          AND EXISTS (
            SELECT 1
            FROM GRUPO_PHARMACIE G
            WHERE G.CODIGOGRUPO = P.CODIGOGRUPO
              AND G.MOVIMENTOESTOQUE = 1
          );
    WHEN ANY DO BEGIN END
    END

    -- ESTOQUE_GERAL_2 (MOVIMENTOESTOQUE = 2)
    BEGIN
        UPDATE PRODUTO P
        SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL2, 1) + 2000000
        WHERE P.CODIGO_PS IS NULL
          AND P.CONVERSAO = :V_CONVERSAO
          AND EXISTS (
            SELECT 1
            FROM GRUPO_PHARMACIE G
            WHERE G.CODIGOGRUPO = P.CODIGOGRUPO
              AND G.MOVIMENTOESTOQUE = 2
          );
    WHEN ANY DO BEGIN END
    END

    -- ESTOQUE_GERAL_3 (MOVIMENTOESTOQUE = 3)
    BEGIN
        UPDATE PRODUTO P
        SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL3, 1) + 3000000
        WHERE P.CODIGO_PS IS NULL
          AND P.CONVERSAO = :V_CONVERSAO
          AND EXISTS (
            SELECT 1
            FROM GRUPO_PHARMACIE G
            WHERE G.CODIGOGRUPO = P.CODIGOGRUPO
              AND G.MOVIMENTOESTOQUE = 3
          );
    WHEN ANY DO BEGIN END
    END

    -- ESTOQUE_GERAL_4 (MOVIMENTOESTOQUE = 4)
    BEGIN
        UPDATE PRODUTO P
        SET P.CODIGO_PS = GEN_ID(GEN_ESTOQUE_GERAL4, 1) + 4000000
        WHERE P.CODIGO_PS IS NULL
          AND P.CONVERSAO = :V_CONVERSAO
          AND EXISTS (
            SELECT 1
            FROM GRUPO_PHARMACIE G
            WHERE G.CODIGOGRUPO = P.CODIGOGRUPO
              AND G.MOVIMENTOESTOQUE = 4
          );
    WHEN ANY DO BEGIN END
    END
    -- ATUALIZA CODIGO_PRODUTO_PS DOS SINONIMOS
    BEGIN
        UPDATE SINONIMO S
        SET S.CODIGO_PRODUTO_PS = (SELECT P.CODIGO_PS FROM PRODUTO P WHERE P.CODIGOPRODUTO = S.CODIGOPRODUTO AND P.CODIGOGRUPO = S.CODIGOGRUPO)
        WHERE S.CODIGO_PRODUTO_PS IS NULL AND S.CONVERSAO = :V_CONVERSAO;
    WHEN ANY DO BEGIN END
    END

    -- ATUALIZA CODIGO_SINONIMO_PS DOS SINONIMOS
    BEGIN
        UPDATE SINONIMO S
        SET S.CODIGO_SINONIMO_PS = CASE
                                    WHEN CODIGO_PRODUTO_PS > 1000000 AND CODIGO_PRODUTO_PS < 1999999 THEN GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
                                    WHEN CODIGO_PRODUTO_PS > 2000000 AND CODIGO_PRODUTO_PS < 2999999 THEN GEN_ID(GEN_ESTOQUE_GERAL2, 1)+2000000
                                  END
        WHERE S.CODIGO_PRODUTO_PS IS NOT NULL AND S.CONVERSAO = :V_CONVERSAO;
    WHEN ANY DO BEGIN END
    END

    I_SQL = 'INSERT INTO ESTOQUE_GERAL (CODIGO,MOVIMENTOESTOQUE,CODIGO_GRUPO,CODIGO_ESTOQUE_CLASSIFICACAO,CODIGO_ESTOQUE_TIPO,NOMEPRODUTO,NOMEPRODUTO_ROTULO,NOMEPRODUTO_FRACAO,CODIGO_NCM,CODIGO_DCB,CODIGOBARRA,CODIGO_ESTOQUE_PORTARIA,FRACAOVENDA,UNIDADE,UNIDADE_CALCULO,VALORCOMPRA,VALORCUSTO,VALORVENDA,UTR,UI,DENSIDADE,CONCENTRACAO,FATOREQUIV,FATORCALCULO,ESTOQUEMINIMO,QTDEMAX,QTDEMAXP,CHECARMAX,CARACTERISTICA,OBSERVACAO,USO_ATENDIMENTO,ATIVO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT
        P.CODIGO_PS AS CODIGO,
        CASE
            WHEN P.CODIGO_PS < 1000000 THEN 0
            WHEN P.CODIGO_PS > 1000000 AND P.CODIGO_PS < 1999999 THEN 1
            WHEN P.CODIGO_PS > 2000000 AND P.CODIGO_PS < 2999999 THEN 2
            WHEN P.CODIGO_PS > 3000000 AND P.CODIGO_PS < 3999999 THEN 3
            WHEN P.CODIGO_PS > 4000000 AND P.CODIGO_PS < 4999999 THEN 4
        END AS MOVIMENTOESTOQUE,
        CASE
            WHEN P.CODIGO_PS < 1000000 THEN 1
            WHEN P.CODIGO_PS > 1000000 AND P.CODIGO_PS < 1999999 THEN 100000
            WHEN P.CODIGO_PS > 2000000 AND P.CODIGO_PS < 2999999 THEN 200000
            WHEN P.CODIGO_PS > 3000000 AND P.CODIGO_PS < 3999999 THEN 300000
            WHEN P.CODIGO_PS > 4000000 AND P.CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_GRUPO,
        CASE
            WHEN P.CODIGO_PS < 1000000 THEN 1
            WHEN P.CODIGO_PS > 1000000 AND P.CODIGO_PS < 1999999 THEN 100000
            WHEN P.CODIGO_PS > 2000000 AND P.CODIGO_PS < 2999999 THEN 200000
            WHEN P.CODIGO_PS > 3000000 AND P.CODIGO_PS < 3999999 THEN 300000
            WHEN P.CODIGO_PS > 4000000 AND P.CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_ESTOQUE_CLASSIFICACAO,
        CASE
            WHEN P.CODIGO_PS < 1000000 THEN 1
            WHEN P.CODIGO_PS > 1000000 AND P.CODIGO_PS < 1999999 THEN 100000
            WHEN P.CODIGO_PS > 2000000 AND P.CODIGO_PS < 2999999 THEN 200000
            WHEN P.CODIGO_PS > 3000000 AND P.CODIGO_PS < 3999999 THEN 300000
            WHEN P.CODIGO_PS > 4000000 AND P.CODIGO_PS < 4999999 THEN 400000
        END AS CODIGO_ESTOQUE_TIPO,
        IIF(P.INATIVOPRODUTO = 1, 'ZZZ-' || UPPER(P.DESCRICAOPRODUTO), UPPER(P.DESCRICAOPRODUTO)) AS NOMEPRODUTO,
        IIF(
            P.INATIVOPRODUTO = 1,
            'ZZZ-' || UPPER(
                IIF(
                    P.DESCRICAOROTULOPRODUTO IS NULL OR P.DESCRICAOROTULOPRODUTO = '',
                    P.DESCRICAOPRODUTO,
                    P.DESCRICAOROTULOPRODUTO
                )
            ),
            UPPER(
                IIF(
                    P.DESCRICAOROTULOPRODUTO IS NULL OR P.DESCRICAOROTULOPRODUTO = '',
                    P.DESCRICAOPRODUTO,
                    P.DESCRICAOROTULOPRODUTO
                )
            )
        ) AS NOMEPRODUTO_ROTULO,
        UPPER(P.DESCRICAOPRODUTO) AS NOMEPRODUTO_FRACAO,
        COALESCE(P.CODIGONCM, NULL) AS CODIGO_NCM,
        COALESCE(P.CODIGODCB, NULL) AS CODIGO_DCB,
        IIF(P.CODIGOBARRAPRODUTO = '' OR P.CODIGOBARRAPRODUTO IS NULL, NULL, P.CODIGOBARRAPRODUTO) AS CODIGOBARRA,
        CASE P.CODIGOLISTACONTROLADO
            WHEN 'A1' THEN 100001
            WHEN 'A2' THEN 100002
            WHEN 'A3' THEN 100003
            WHEN 'AM' THEN 100004
            WHEN 'B1' THEN 100005
            WHEN 'B2' THEN 100006
            WHEN 'C1' THEN 100007
            WHEN 'C2' THEN 100008
            WHEN 'C3' THEN 100009
            WHEN 'C4' THEN 100010
            WHEN 'C5' THEN 100011
            WHEN 'D1' THEN 100012
            WHEN 'D2' THEN 100013
            WHEN 'F1' THEN 100014
            WHEN 'F2' THEN 100015
            WHEN 'F4' THEN 100016
        END AS CODIGO_ESTOQUE_PORTARIA,
        COALESCE(P.FRACIONAMENTOPRODUTO, 1) AS FRACAOVENDA,
        IIF(P.SIGLAUNIDADEVOLUME IS NULL OR P.SIGLAUNIDADEVOLUME = '', P.SIGLAUNIDADEESTOQUE, P.SIGLAUNIDADEVOLUME) AS UNIDADE,
        IIF(P.SIGLAUNIDADE IS NULL OR P.SIGLAUNIDADE = '', P.SIGLAUNIDADEESTOQUE, P.SIGLAUNIDADE) AS UNIDADE_CALCULO,
        CAST(P.VALORCUSTOPRODUTO AS NUMERIC(18,4)) AS VALORCOMPRA,
        CAST(P.CUSTOREFERENCIAPRODUTO AS NUMERIC(18,4)) AS VALORCUSTO,
        CAST(
            CAST(
                IIF(P.CUSTOREFERENCIAPRODUTO > 10000000, 0, P.CUSTOREFERENCIAPRODUTO) 
                AS NUMERIC(18,4)
            ) *
            (
                CAST(1.0 AS NUMERIC(18,4)) +
                CAST(COALESCE(P.FATORREFERENCIAPRODUTO, 800) AS NUMERIC(18,4)) /
                CAST(100.0 AS NUMERIC(18,4))
            )
        AS NUMERIC(18,4)) AS VALORVENDA,
        IIF(P.FATORUTRPRODUTO > 0, P.FATORUTRPRODUTO, NULL) AS UTR,
        IIF(P.FATORUIPRODUTO > 0, P.FATORUIPRODUTO, NULL) AS UI,
        IIF(P.DENSIDADEPRODUTO > 0, P.DENSIDADEPRODUTO, 1) AS DENSIDADE,
        IIF(P.FATORCORRECAOPRODUTO > 0, (100/P.FATORCORRECAOPRODUTO), 100) AS CONCENTRACAO,
        COALESCE(P.FATOREQUIVALENCIAPRODUTO, 1) AS FATOREQUIV,
        2 AS FATORCALCULO,
        -P.ESTOQUEMINIMOPRODUTO AS ESTOQUEMINIMO,
        P.DOSEMAXIMAPRODUTO AS QTDEMAX,
        P.DOSEMAXIMAPERCENTUALPRODUTO AS QTDEMAXP,
        IIF(P.DOSEMAXIMAPRODUTO IS NOT NULL OR P.DOSEMAXIMAPRODUTO <> '', -1, 0) AS CHECARMAX,
        IIF(P.CONSERVACAOPRODUTO IS NOT NULL OR P.CONSERVACAOPRODUTO <> '',
            P.CONSERVACAOPRODUTO || ASCII_CHAR(13) || ASCII_CHAR(10) || COALESCE(P.CATEGORIATERAPEUTICAPRODUTO, ''),
            COALESCE(P.CATEGORIATERAPEUTICAPRODUTO, '')) AS CARACTERISTICA,
        IIF(P.OBSERVACAOPRODUTO IS NOT NULL OR P.OBSERVACAOPRODUTO <> '',
            P.OBSERVACAOPRODUTO || ASCII_CHAR(13) || ASCII_CHAR(10) || COALESCE(P.OBSERVACAOFICHATECNICA, '') || ASCII_CHAR(13) || ASCII_CHAR(10) || COALESCE(P.OBSERVACAOVENDAPRODUTO, ''),
            IIF(P.OBSERVACAOFICHATECNICA IS NOT NULL OR P.OBSERVACAOFICHATECNICA <> '',
                P.OBSERVACAOFICHATECNICA || ASCII_CHAR(13) || ASCII_CHAR(10) || COALESCE(P.OBSERVACAOVENDAPRODUTO, ''),
                COALESCE(P.OBSERVACAOVENDAPRODUTO, ''))
        ) AS OBSERVACAO,
        -1 AS USO_ATENDIMENTO,
        CASE P.INATIVOPRODUTO
            WHEN 0 THEN -1
            WHEN 1 THEN 0
        END AS ATIVO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        P.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        P.DT_ALTER AS ALTERACAO_DT
    FROM PRODUTO P
    WHERE P.CODIGO_PS IS NOT NULL AND P.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :NOMEPRODUTO, :NOMEPRODUTO_ROTULO, :NOMEPRODUTO_FRACAO, :CODIGO_NCM, :CODIGO_DCB, :CODIGOBARRA, :CODIGO_ESTOQUE_PORTARIA, :FRACAOVENDA, :UNIDADE, :UNIDADE_CALCULO, :VALORCOMPRA, :VALORCUSTO, :VALORVENDA, :UTR, :UI, :DENSIDADE, :CONCENTRACAO, :FATOREQUIV, :FATORCALCULO, :ESTOQUEMINIMO, :QTDEMAX, :QTDEMAXP, :CHECARMAX, :CARACTERISTICA, :OBSERVACAO, :USO_ATENDIMENTO, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :MOVIMENTOESTOQUE, :CODIGO_GRUPO, :CODIGO_ESTOQUE_CLASSIFICACAO, :CODIGO_ESTOQUE_TIPO, :NOMEPRODUTO, :NOMEPRODUTO_ROTULO, :NOMEPRODUTO_FRACAO, :CODIGO_NCM, :CODIGO_DCB, :CODIGOBARRA, :CODIGO_ESTOQUE_PORTARIA, :FRACAOVENDA, :UNIDADE, :UNIDADE_CALCULO, :VALORCOMPRA, :VALORCUSTO, :VALORVENDA, :UTR, :UI, :DENSIDADE, :CONCENTRACAO, :FATOREQUIV, :FATORCALCULO, :ESTOQUEMINIMO, :QTDEMAX, :QTDEMAXP, :CHECARMAX, :CARACTERISTICA, :OBSERVACAO, :USO_ATENDIMENTO, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT)
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    I_SQL = 'INSERT INTO ESTOQUE_GERAL (CODIGO,CODIGOPRINCIPAL,MOVIMENTOESTOQUE,CODIGO_GRUPO,CODIGO_ESTOQUE_CLASSIFICACAO,CODIGO_ESTOQUE_TIPO,NOMEPRODUTO,NOMEPRODUTO_ROTULO,FATOREQUIV,FATOREQUIV_UC,ATIVO,USO_ATENDIMENTO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT
    S.CODIGO_SINONIMO_PS AS CODIGO,
    S.CODIGO_PRODUTO_PS AS CODIGOPRINCIPAL,
    CASE
      WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 0
      WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 1
      WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 2
      WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 3
      WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 4
    END AS MOVIMENTOESTOQUE,
    CASE
      WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
      WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
      WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
      WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
      WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
    END AS CODIGO_GRUPO,
    CASE
      WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
      WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
      WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
      WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
      WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
    END AS CODIGO_ESTOQUE_CLASSIFICACAO,
    CASE
      WHEN S.CODIGO_SINONIMO_PS < 1000000 THEN 1
      WHEN S.CODIGO_SINONIMO_PS > 1000000 AND S.CODIGO_SINONIMO_PS < 1999999 THEN 100000
      WHEN S.CODIGO_SINONIMO_PS > 2000000 AND S.CODIGO_SINONIMO_PS < 2999999 THEN 200000
      WHEN S.CODIGO_SINONIMO_PS > 3000000 AND S.CODIGO_SINONIMO_PS < 3999999 THEN 300000
      WHEN S.CODIGO_SINONIMO_PS > 4000000 AND S.CODIGO_SINONIMO_PS < 4999999 THEN 400000
    END AS CODIGO_ESTOQUE_TIPO,
    UPPER (S.DESCRICAOSINONIMO) AS NOMEPRODUTO,
    UPPER (S.DESCRICAOROTULOSINONIMO) AS NOMEPRODUTO_ROTULO,
    IIF (S.FATOREQUIVALENCIASINONIMO = 0 or S.FATOREQUIVALENCIASINONIMO IS NULL ,1,S.FATOREQUIVALENCIASINONIMO) AS FATOREQUIV,
    CASE
        WHEN S.FATOREQUIVALENCIASINONIMO = 1 THEN -1
        WHEN S.FATOREQUIVALENCIASINONIMO IS NULL THEN -1
        WHEN S.FATOREQUIVALENCIASINONIMO <> 1 THEN -1
    END AS FATOREQUIV_UC,
    -1 AS ATIVO,
    -1 AS USO_ATENDIMENTO,
    1 AS CADASTRO_LJ,
    1 AS CADASTRO_CF,
    S.DT_CREATION AS CADASTRO_DT,
    1 AS ALTERACAO_LJ,
    1 AS ALTERACAO_CF,
    S.DT_ALTER AS ALTERACAO_DT
    FROM SINONIMO S
    WHERE S.CODIGO_PRODUTO_PS IS NOT NULL
    AND S.CODIGO_SINONIMO_PS IS NOT NULL
    AND S.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO,:CODIGOPRINCIPAL,:MOVIMENTOESTOQUE,:CODIGO_GRUPO,:CODIGO_ESTOQUE_CLASSIFICACAO,:CODIGO_ESTOQUE_TIPO,:NOMEPRODUTO,:NOMEPRODUTO_ROTULO,:FATOREQUIV,:FATOREQUIV_UC,:ATIVO,:USO_ATENDIMENTO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:CODIGOPRINCIPAL,:MOVIMENTOESTOQUE,:CODIGO_GRUPO,:CODIGO_ESTOQUE_CLASSIFICACAO,:CODIGO_ESTOQUE_TIPO,:NOMEPRODUTO,:NOMEPRODUTO_ROTULO,:FATOREQUIV,:FATOREQUIV_UC,:ATIVO,:USO_ATENDIMENTO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

END;