create or alter procedure EXTRACT_DATA_FORNECEDOR (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable CODIGO integer;
declare variable NOMEFANTASIA varchar(300);
declare variable NOMEFORNECEDOR varchar(300);
declare variable CODIGO_GRUPO integer;
declare variable TIPOPESSOA integer;
declare variable CPF_CNPJ varchar(30);
declare variable RG_IE varchar(30);
declare variable CONTATO1 varchar(300);
declare variable HOMEPAGE varchar(300);
declare variable EMAIL varchar(300);
declare variable OBSERVACAO varchar(2000);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable TIPO_CADASTRO integer;
declare variable CODIGO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable CEP varchar(30);
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(7000);
declare variable MSG_ERRO varchar(100);
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
        -- OBTEM STRING DE CONEXAO
        SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
        FROM CONEXAO CN 
        INTO :CON;
        
        IF (:CON IS NULL OR :CON = '') THEN
        BEGIN
            MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
            SUSPEND;
            EXIT;
        END
        ELSE
        BEGIN
            MSG_ERRO = 'CONEXÃO OK: ' || :CON;
        END
    
    -- ATUALIZA CAMPO CONVERSAO
    BEGIN
         UPDATE FORNECEDOR F 
         SET F.CONVERSAO = :V_CONVERSAO 
         WHERE F.CODIGO_PS IS NULL;
    END
    
    -- INSERE FORNECEDORES NO SISTEMA DESTINO
    I_SQL = 'INSERT INTO FORNECEDOR (CODIGO, NOMEFANTASIA, NOMEFORNECEDOR, CODIGO_GRUPO, TIPOPESSOA, CPF_CNPJ, RG_IE, CONTATO1, HOMEPAGE, EMAIL, OBSERVACAO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT 
        CAST(F.CODIGOFORNECEDOR AS INTEGER) AS CODIGO,
        UPPER(COALESCE(NULLIF(F.NOMEFORNECEDOR, ''), NULL)) AS NOMEFANTASIA,
        UPPER(COALESCE(NULLIF(F.NOMEFORNECEDOR, ''), NULL)) AS NOMEFORNECEDOR,
        500000 AS CODIGO_GRUPO,
        IIF(NULLIF(TRIM(F.CPFFORNECEDOR), '') IS NOT NULL, 1, 2) AS TIPOPESSOA,
        COALESCE(NULLIF(TRIM(F.CPFFORNECEDOR), ''), NULLIF(TRIM(F.CNPJFORNECEDOR), '')) AS CPF_CNPJ,
        NULLIF(TRIM(F.IEFORNECEDOR), '') AS RG_IE,
        NULLIF(TRIM(F.CONTATOFORNECEDOR), '') AS CONTATO1,
        LOWER(NULLIF(TRIM(F.HOMEPAGEFORNECEDOR), '')) AS HOMEPAGE,
        LOWER(NULLIF(TRIM(F.EMAILFORNECEDOR), '')) AS EMAIL,
        IIF(
            (F.CODIGOBANCO IS NOT NULL OR 
             NULLIF(TRIM(F.AGENCIAFORNECEDOR), '') IS NOT NULL OR 
             NULLIF(TRIM(F.CONTAFORNECEDOR), '') IS NOT NULL),
            TRIM(
                COALESCE('CÓDIGO BANCO: ' || CAST(F.CODIGOBANCO AS INTEGER), '') ||
                COALESCE(ASCII_CHAR(13) || ASCII_CHAR(10) || 'AGÊNCIA: ' || NULLIF(F.AGENCIAFORNECEDOR, ''), '') ||
                COALESCE(ASCII_CHAR(13) || ASCII_CHAR(10) || 'CONTA: ' || NULLIF(F.CONTAFORNECEDOR, ''), '')
            ),
            NULL
        ) AS OBSERVACAO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        F.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        F.DT_ALTER AS ALTERACAO_DT
    FROM FORNECEDOR F
    WHERE F.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :NOMEFANTASIA, :NOMEFORNECEDOR, :CODIGO_GRUPO, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CONTATO1, :HOMEPAGE, :EMAIL, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :NOMEFANTASIA, :NOMEFORNECEDOR, :CODIGO_GRUPO, :TIPOPESSOA, :CPF_CNPJ, :RG_IE, :CONTATO1, :HOMEPAGE, :EMAIL, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    -- INSERE ENDEREÇOS DOS FORNECEDORES
    I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CEP, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT
        GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
        4 AS TIPO_CADASTRO,
        CAST(F.CODIGOFORNECEDOR AS INTEGER) AS CODIGO_CADASTRO,
        UPPER(
            COALESCE(NULLIF(TRIM(F.ENDERECOFORNECEDOR), ''), '') ||
            IIF(NULLIF(TRIM(F.ENDERECOFORNECEDOR), '') IS NOT NULL, ', ', '') ||
            COALESCE(B.NOMEBAIRRO, '')
        ) AS ENDERECO,
        COALESCE(NULLIF(TRIM(F.NUMEROENDERECOFORNECEDOR), ''), 'S/N') AS NUMERO,
        IIF(NULLIF(TRIM(F.COMPLEMENTOFORNECEDOR), '') IS NOT NULL,
            UPPER(TRIM(F.COMPLEMENTOFORNECEDOR)),
            NULL) AS OBSERVACAO,
        1 AS CODIGO_REGIAODETALHE,
        IIF(C.CODIGO_PS IS NOT NULL, C.CODIGO_PS, 1) AS CODIGO_CIDADEESTADO,
        COALESCE(NULLIF(REPLACE(TRIM(F.CEPFORNECEDOR), '-', ''), ''), NULL) AS CEP,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        F.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        F.DT_ALTER AS ALTERACAO_DT
    FROM FORNECEDOR F
        LEFT JOIN CIDADE C ON C.CODIGOCIDADE = F.CODIGOCIDADE
        LEFT JOIN BAIRRO B ON B.CODIGOBAIRRO = F.CODIGOBAIRRO
    WHERE F.ENDERECOFORNECEDOR <> ''
    AND F.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    -- INSERE TELEFONES DOS FORNECEDORES
    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, TELEFONE_TIPO, TELEFONEPREFIXO, TELEFONE, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    -- TELEFONE PRINCIPAL
    FOR SELECT 
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
        4 AS TIPO_CADASTRO,
        CAST(F.CODIGOFORNECEDOR AS INTEGER) AS CODIGO_CADASTRO,
        IIF(SUBSTRING(TRIM(F.TELEFONEFORNECEDOR) FROM 1 FOR 1) IN ('6','7','8','9'), 3, 2) AS TELEFONE_TIPO,
        IIF(CHAR_LENGTH(TRIM(F.DDDFORNECEDOR)) >= 2,
            IIF(SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 1) = '0',
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 2 FOR 2),
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 2)),
            NULL) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.TELEFONEFORNECEDOR)) FROM 1 FOR 18) AS TELEFONE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        F.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        F.DT_ALTER AS ALTERACAO_DT
    FROM FORNECEDOR F
    WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.TELEFONEFORNECEDOR)) <> ''
    AND F.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- TELEFONE CONTATO
    FOR SELECT 
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
        4 AS TIPO_CADASTRO,
        CAST(F.CODIGOFORNECEDOR AS INTEGER) AS CODIGO_CADASTRO,
        IIF(SUBSTRING(TRIM(F.TELEFONECONTATOFORNECEDOR) FROM 1 FOR 1) IN ('6','7','8','9'), 3, 2) AS TELEFONE_TIPO,
        IIF(CHAR_LENGTH(TRIM(F.DDDFORNECEDOR)) >= 2,
            IIF(SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 1) = '0',
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 2 FOR 2),
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 2)),
            NULL) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.TELEFONECONTATOFORNECEDOR)) FROM 1 FOR 18) AS TELEFONE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        F.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        F.DT_ALTER AS ALTERACAO_DT
    FROM FORNECEDOR F
    WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.TELEFONECONTATOFORNECEDOR)) <> ''
    AND F.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- FAX
    FOR SELECT 
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
        4 AS TIPO_CADASTRO,
        CAST(F.CODIGOFORNECEDOR AS INTEGER) AS CODIGO_CADASTRO,
        IIF(SUBSTRING(TRIM(F.FAXFORNECEDOR) FROM 1 FOR 1) IN ('6','7','8','9'), 3, 2) AS TELEFONE_TIPO,
        IIF(CHAR_LENGTH(TRIM(F.DDDFORNECEDOR)) >= 2,
            IIF(SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 1) = '0',
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 2 FOR 2),
                SUBSTRING(TRIM(F.DDDFORNECEDOR) FROM 1 FOR 2)),
            NULL) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.FAXFORNECEDOR)) FROM 1 FOR 18) AS TELEFONE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        F.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        F.DT_ALTER AS ALTERACAO_DT
    FROM FORNECEDOR F
    WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(F.FAXFORNECEDOR)) <> ''
    AND F.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

END;