create or alter procedure EXTRACT_DATA_CLIENTE (
    V_CONVERSAO INTEGER)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable CODIGO integer;
declare variable CODIGO_GRUPO integer;
declare variable TIPOPESSOA integer;
declare variable NOMECLIENTE varchar(300);
declare variable NOMEROTULO varchar(300);
declare variable SEXO integer;
declare variable CPF_CNPJ varchar(30);
declare variable CODIGO_TIPODOCUMENTO integer;
declare variable RG_IE varchar(30);
declare variable ORGAOEXPEDIDOR varchar(30);
declare variable ORGAOEXPEDIDOR_UF varchar(3);
declare variable EMAIL1 varchar(300);
declare variable DIANASCIMENTO integer;
declare variable MESNASCIMENTO integer;
declare variable ANONASCIMENTO integer;
declare variable ATIVO integer;
declare variable CONSUMIDORFINAL integer;
declare variable TIPODESCONTO integer;
declare variable NAOCONTRIBUINTE integer;
declare variable OBSERVACAO varchar(7000);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable TIPO_CADASTRO integer;
declare variable CODIGO_CADASTRO integer;
declare variable ENDERECO varchar(100);
declare variable NUMERO varchar(30);
declare variable OBSERVACAO_END varchar(1000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable CEP varchar(30);
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(7000);
declare variable MSG_ERRO varchar(100);
BEGIN
     V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
    -- OBTEM STRING DE CONEXAO
        SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
        FROM CONEXAO CN 
        INTO :CON;
        
        IF (:CON IS NULL OR :CON = '') THEN
        BEGIN
            MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
            SUSPEND;
            EXIT;
        END
        ELSE
        BEGIN
            MSG_ERRO = 'CONEXÃO OK: ' || :CON;
        END
    
    -- REMOVE ACENTOS DAS CIDADES
    BEGIN
        UPDATE CIDADEESTADO CID SET 
        CID.NOMECIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(CID.NOMECIDADE));
    WHEN ANY DO BEGIN END
    END

    BEGIN
       UPDATE CIDADE C SET 
       C.NOMECIDADE = (SELECT RETORNO FROM TIRA_ACENTOS(C.NOMECIDADE));
    WHEN ANY DO BEGIN END
    END

    -- ATUALIZA CODIGO_PS DAS CIDADES POR CODIGO IBGE
    BEGIN
        UPDATE CIDADE C SET 
        C.CODIGO_PS = (SELECT CE.CODIGO FROM CIDADEESTADO CE WHERE CE.CODIGO_IBGE = C.CODIGOIBGE AND CE.CODIGO_IBGE IS NOT NULL) 
        WHERE C.CODIGO_PS IS NULL;
    WHEN ANY DO BEGIN END
    END

    -- ATUALIZA CODIGO_PS DAS CIDADES POR NOME
    BEGIN
        UPDATE CIDADE C SET 
        C.CODIGO_PS = (SELECT FIRST 1 CE.CODIGO FROM CIDADEESTADO CE WHERE CE.NOMECIDADE = C.NOMECIDADE) 
        WHERE C.CODIGO_PS IS NULL;
    WHEN ANY DO BEGIN END
    END

    BEGIN
        UPDATE CLIENTE C 
        SET C.CONVERSAO = :V_CONVERSAO 
        WHERE C.CODIGO_PS IS NULL;
    END
    -- GERA CODIGO_PS PARA CLIENTES
    BEGIN
        UPDATE CLIENTE C 
        SET C.CODIGO_PS = GEN_ID(GEN_CLIENTE,1) 
        WHERE C.CODIGO_PS IS NULL 
        ORDER BY C.CODIGOCLIENTE;
    WHEN ANY DO BEGIN END
    END



    -- ATUALIZA CODIGO_PS DOS ENDEREÇOS DE ENTREGA
    BEGIN
        UPDATE CLIENTE_ENDERECO_ENTREGA CEC 
        SET CEC.CODIGO_PS = (SELECT FIRST 1 C.CODIGO_PS FROM CLIENTE C 
        WHERE C.CODIGOCLIENTE = CEC.CODIGOCLIENTE);
    WHEN ANY DO BEGIN END
    END
    
    -- INSERE CLIENTES NO SISTEMA DESTINO
    I_SQL = 'INSERT INTO CLIENTE (CODIGO, CODIGO_GRUPO, TIPOPESSOA, NOMECLIENTE, NOMEROTULO, SEXO, CPF_CNPJ, CODIGO_TIPODOCUMENTO, RG_IE, ORGAOEXPEDIDOR, ORGAOEXPEDIDOR_UF, EMAIL1, DIANASCIMENTO, MESNASCIMENTO, ANONASCIMENTO, ATIVO, CONSUMIDORFINAL, TIPODESCONTO, NAOCONTRIBUINTE, OBSERVACAO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT
            C.CODIGO_PS AS CODIGO,
            800000 AS CODIGO_GRUPO,
        IIF(CHAR_LENGTH(REPLACE(REPLACE(REPLACE(CPFCNPJCLIENTE, '-', ''), '/', ''), '.', '')) > 11, 2, 1) AS TIPOPESSOA,
        UPPER(IIF(NULLIF(TRIM(NOMECLIENTE), '') IS NULL, NULL, NOMECLIENTE)) AS NOMECLIENTE,
        UPPER(IIF(NULLIF(TRIM(NOMEROTULOCLIENTE), '') IS NULL, NOMECLIENTE, NOMEROTULOCLIENTE)) AS NOMEROTULO,
        IIF(NULLIF(TRIM(GENERO), '') IS NULL, 1, GENERO) AS SEXO,
        IIF(NULLIF(TRIM(CPFCNPJCLIENTE), '') IS NULL, NULL, REPLACE(REPLACE(REPLACE(CPFCNPJCLIENTE, '-', ''), '/', ''), '.', '')) AS CPF_CNPJ,
        IIF(NULLIF(TRIM(RGCLIENTE), '') IS NULL, 19, 2) AS CODIGO_TIPODOCUMENTO,
        IIF(NULLIF(TRIM(RGCLIENTE), '') IS NULL, 
            IIF(NULLIF(TRIM(IECLIENTE), '') IS NULL, NULL, IECLIENTE), 
            RGCLIENTE) AS RG_IE,
        IIF(NULLIF(TRIM(ORGAOEXPEDIDORCLIENTE), '') IS NULL, NULL, ORGAOEXPEDIDORCLIENTE) AS ORGAOEXPEDIDOR,
        IIF(NULLIF(TRIM(UFEXPEDIDORCLIENTE), '') IS NULL, NULL, UFEXPEDIDORCLIENTE) AS ORGAOEXPEDIDOR_UF,
        IIF(NULLIF(TRIM(EMAILCLIENTE), '') IS NULL, NULL, EMAILCLIENTE) AS EMAIL1,
        COALESCE(EXTRACT(DAY FROM DATANASCIMENTOCLIENTE), 0) AS DIANASCIMENTO,
        COALESCE(EXTRACT(MONTH FROM DATANASCIMENTOCLIENTE), 0) AS MESNASCIMENTO,
        COALESCE(EXTRACT(YEAR FROM DATANASCIMENTOCLIENTE), 0) AS ANONASCIMENTO,
        CASE IE_ATIVO
            WHEN 'A' THEN -1
            ELSE 0
        END AS ATIVO,
            -1 AS CONSUMIDORFINAL,
            1 AS TIPODESCONTO,
            3 AS NAOCONTRIBUINTE,
        CAST(SUBSTRING(
            IIF(NULLIF(TRIM(MENSAGEMVENDACLIENTE), '') IS NOT NULL,
                MENSAGEMVENDACLIENTE || ASCII_CHAR(13) || ASCII_CHAR(10),
                '') ||
            IIF(NULLIF(TRIM(OBSGERALCLIENTE), '') IS NOT NULL,
                OBSGERALCLIENTE || ASCII_CHAR(13) || ASCII_CHAR(10),
                '') ||
            IIF(NULLIF(TRIM(OBSERVACAOOPCLIENTE), '') IS NOT NULL,
                OBSERVACAOOPCLIENTE,
                '')
            FROM 1 FOR 7000) AS VARCHAR(7000)) AS OBSERVACAO,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
        DT_CREATION AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
        DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE C
    WHERE C.CODIGO_PS IS NOT NULL
    AND C.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :CODIGO_GRUPO, :TIPOPESSOA, :NOMECLIENTE, :NOMEROTULO, :SEXO, :CPF_CNPJ, :CODIGO_TIPODOCUMENTO, :RG_IE, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :EMAIL1, :DIANASCIMENTO, :MESNASCIMENTO, :ANONASCIMENTO, :ATIVO, :CONSUMIDORFINAL, :TIPODESCONTO, :NAOCONTRIBUINTE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_GRUPO, :TIPOPESSOA, :NOMECLIENTE, :NOMEROTULO, :SEXO, :CPF_CNPJ, :CODIGO_TIPODOCUMENTO, :RG_IE, :ORGAOEXPEDIDOR, :ORGAOEXPEDIDOR_UF, :EMAIL1, :DIANASCIMENTO, :MESNASCIMENTO, :ANONASCIMENTO, :ATIVO, :CONSUMIDORFINAL, :TIPODESCONTO, :NAOCONTRIBUINTE, :OBSERVACAO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    -- INSERE ENDEREÇOS DE ENTREGA
    I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CEP, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';

    FOR SELECT
                GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                1 AS TIPO_CADASTRO,
        CAST(CL.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        SUBSTRING(
            UPPER(
                COALESCE(CEE.DS_ENDERECO, '') ||
                CASE 
                    WHEN CEE.DS_ENDERECO IS NOT NULL AND CEE.DS_ENDERECO <> '' 
                         AND B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> ''
                        THEN ', ' || B.NOMEBAIRRO
                    WHEN B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> ''
                        THEN B.NOMEBAIRRO
                    ELSE ''
                END ||
                CASE 
                    WHEN (
                        (CEE.DS_ENDERECO IS NOT NULL AND CEE.DS_ENDERECO <> '') OR 
                        (B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> '')
                    ) AND CC.NOMECIDADE IS NOT NULL AND CC.NOMECIDADE <> ''
                        THEN ', ' || CC.NOMECIDADE
                    WHEN CC.NOMECIDADE IS NOT NULL AND CC.NOMECIDADE <> ''
                        THEN CC.NOMECIDADE
                    ELSE ''
                END
            ) FROM 1 FOR 100
        ) AS ENDERECO,
        COALESCE(CEE.NR_ENDERECO, 'S/N') AS NUMERO,
        UPPER(COALESCE(CEE.DS_COMPLEMENTO, '') || IIF(CEE.DS_COMPLEMENTO <> '', ', ', '') || COALESCE(DS_PROXIMIDADE, '')) AS OBSERVACAO,
        1 AS CODIGO_REGIAODETALHE,
        IIF(CC.CODIGO_PS IS NOT NULL, CC.CODIGO_PS, 1) AS CODIGO_CIDADEESTADO,
        COALESCE(CEE.CD_CEP, '00000000') AS CEP,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CEE.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CEE.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE_ENDERECO_ENTREGA CEE
        INNER JOIN CLIENTE CL ON CL.CODIGOCLIENTE = CEE.CODIGOCLIENTE
        LEFT JOIN CIDADE CC ON CC.CODIGOCIDADE = CEE.CD_CIDADE
        LEFT JOIN BAIRRO B ON B.CODIGOBAIRRO = CEE.CD_BAIRRO
    WHERE CEE.DS_ENDERECO <> ''
    AND CL.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- INSERE ENDEREÇOS PRINCIPAIS DOS CLIENTES
    FOR SELECT
        GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
        1 AS TIPO_CADASTRO,
        CAST(C.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        SUBSTRING(
            UPPER(
                COALESCE(C.ENDERECOCLIENTE, '') ||
                CASE
                    WHEN C.ENDERECOCLIENTE IS NOT NULL AND C.ENDERECOCLIENTE <> '' 
                         AND B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> ''
                        THEN ', ' || B.NOMEBAIRRO
                    WHEN B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> ''
                        THEN B.NOMEBAIRRO
                    ELSE ''
                END ||
                CASE
                    WHEN (C.ENDERECOCLIENTE IS NOT NULL AND C.ENDERECOCLIENTE <> '') 
                         OR (B.NOMEBAIRRO IS NOT NULL AND B.NOMEBAIRRO <> '')
                        THEN
                            CASE
                                WHEN CC.NOMECIDADE IS NOT NULL AND CC.NOMECIDADE <> '' 
                                    THEN ', ' || CC.NOMECIDADE
                                ELSE ''
                            END
                    WHEN CC.NOMECIDADE IS NOT NULL AND CC.NOMECIDADE <> '' 
                        THEN CC.NOMECIDADE
                    ELSE ''
                END
            ) FROM 1 FOR 100
        ) AS ENDERECO,
        COALESCE(C.NUMEROENDERECOCLIENTE, 'S/N') AS NUMERO,
        UPPER(COALESCE(C.COMPLEMENTOCLIENTE, '') || IIF(C.COMPLEMENTOCLIENTE <> '', ', ', '') || COALESCE(C.PROXIMIDADECLIENTE, '')) AS OBSERVACAO,
                1 AS CODIGO_REGIAODETALHE,
        IIF(CC.CODIGO_PS IS NOT NULL, CC.CODIGO_PS, 1) AS CODIGO_CIDADEESTADO,
        COALESCE(C.CEPCLIENTE, '00000000') AS CEP,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
        C.DT_CREATION AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
        C.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE C
        LEFT JOIN CIDADE CC ON CC.CODIGOCIDADE = C.CODIGOCIDADE
        LEFT JOIN BAIRRO B ON B.CODIGOBAIRRO = C.CODIGOBAIRRO
    WHERE C.ENDERECOCLIENTE <> ''
        AND NOT EXISTS (
            SELECT 1
            FROM CLIENTE_ENDERECO_ENTREGA CEE2
            WHERE CEE2.CODIGOCLIENTE = C.CODIGOCLIENTE
                AND CEE2.DS_ENDERECO <> ''
        )
        AND C.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    -- INSERE TELEFONES DOS CLIENTES
    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, TELEFONE_TIPO, TELEFONEPREFIXO, TELEFONE, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    -- TELEFONES DE ENTREGA
    FOR SELECT
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
        1 AS TIPO_CADASTRO,
        CAST(CC.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        IIF(ASCII_VAL(SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_TELEFONE)) FROM 1 FOR 1)) BETWEEN 48 AND 53, 1, 3) AS TELEFONE_TIPO,
        IIF(SUBSTRING(TRIM(CEE.DDD_TELEFONE) FROM 1 FOR 1) = '0', SUBSTRING(TRIM(CEE.DDD_TELEFONE) FROM 2 FOR 2), SUBSTRING(TRIM(CEE.DDD_TELEFONE) FROM 1 FOR 2)) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_TELEFONE)) FROM 1 FOR 18) AS TELEFONE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CEE.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CEE.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE_ENDERECO_ENTREGA CEE
        INNER JOIN CLIENTE CC ON CC.CODIGOCLIENTE = CEE.CODIGOCLIENTE
    WHERE CEE.NR_TELEFONE <> ''
        AND (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_TELEFONE)) <> ''
        AND CC.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- CELULARES DE ENTREGA
    FOR SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
        CAST(CC.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        IIF(ASCII_VAL(SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_CELULAR)) FROM 1 FOR 1)) BETWEEN 48 AND 53, 1, 3) AS TELEFONE_TIPO,
        IIF(SUBSTRING(TRIM(CEE.DDD_CELULAR) FROM 1 FOR 1) = '0', SUBSTRING(TRIM(CEE.DDD_CELULAR) FROM 2 FOR 2), SUBSTRING(TRIM(CEE.DDD_CELULAR) FROM 1 FOR 2)) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_CELULAR)) FROM 1 FOR 18) AS TELEFONE,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
        CEE.DT_CREATION AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
        CEE.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE_ENDERECO_ENTREGA CEE
        INNER JOIN CLIENTE CC ON CC.CODIGOCLIENTE = CEE.CODIGOCLIENTE
    WHERE CEE.NR_CELULAR <> ''
        AND (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CEE.NR_CELULAR)) <> ''
        AND CC.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- TELEFONES PRINCIPAIS DOS CLIENTES
    FOR SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
        CAST(CC.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        IIF(ASCII_VAL(SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.TELEFONECLIENTE)) FROM 1 FOR 1)) BETWEEN 48 AND 53, 1, 3) AS TELEFONE_TIPO,
        IIF(SUBSTRING(TRIM(CC.DDDTELEFONECLIENTE) FROM 1 FOR 1) = '0', SUBSTRING(TRIM(CC.DDDTELEFONECLIENTE) FROM 2 FOR 2), SUBSTRING(TRIM(CC.DDDTELEFONECLIENTE) FROM 1 FOR 2)) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.TELEFONECLIENTE)) FROM 1 FOR 18) AS TELEFONE,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
        CC.DT_CREATION AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
        CC.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE CC
    WHERE CC.TELEFONECLIENTE <> ''
        AND (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.TELEFONECLIENTE)) <> ''
        AND NOT EXISTS (
            SELECT 1
            FROM CLIENTE_ENDERECO_ENTREGA CEE2
            WHERE CEE2.CODIGOCLIENTE = CC.CODIGOCLIENTE
                AND CEE2.NR_TELEFONE <> ''
        )
        AND CC.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- CELULARES PRINCIPAIS DOS CLIENTES
    FOR SELECT
            GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
            1 AS TIPO_CADASTRO,
        CAST(CC.CODIGO_PS AS INTEGER) AS CODIGO_CADASTRO,
        IIF(ASCII_VAL(SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.CELULARCLIENTE)) FROM 1 FOR 1)) BETWEEN 48 AND 53, 1, 3) AS TELEFONE_TIPO,
        IIF(SUBSTRING(TRIM(CC.DDDCELULARCLIENTE) FROM 1 FOR 1) = '0', SUBSTRING(TRIM(CC.DDDCELULARCLIENTE) FROM 2 FOR 2), SUBSTRING(TRIM(CC.DDDTELEFONECLIENTE) FROM 1 FOR 2)) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.CELULARCLIENTE)) FROM 1 FOR 18) AS TELEFONE,
            1 AS CADASTRO_LJ,
            1 AS CADASTRO_CF,
        CC.DT_CREATION AS CADASTRO_DT,
            1 AS ALTERACAO_LJ,
            1 AS ALTERACAO_CF,
        CC.DT_ALTER AS ALTERACAO_DT
    FROM CLIENTE CC
    WHERE CC.CELULARCLIENTE <> ''
        AND (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(CC.CELULARCLIENTE)) <> ''
        AND NOT EXISTS (
            SELECT 1
            FROM CLIENTE_ENDERECO_ENTREGA CEE3
            WHERE CEE3.CODIGOCLIENTE = CC.CODIGOCLIENTE
                AND CEE3.NR_CELULAR <> ''
        )
        AND CC.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
END;