create or alter procedure EXTRACT_DATA_FORMAFARMACEUTICA
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable MSG_ERRO varchar(100);
declare variable CODIGO integer;
declare variable NOMEFORMAFARMACEUTICA varchar(100);
declare variable NOMEROTULO varchar(100);
declare variable TIPO_USO integer;
declare variable VALIDADE integer;
declare variable VALORMINIMOATENDIMENTO numeric(18,2);
declare variable CODIGO_LABORATORIO integer;
declare variable TIPOINFORME integer;
declare variable CODIGO_FORMAFARMACEUTICA_TU integer;
declare variable METODOUTILIZACAO integer;
declare variable USOVALIDADE integer;
declare variable DESCRICAOROTULO_TIPO integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable CADASTRO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ATIVO integer;

BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
    -- OBTEM STRING DE CONEXAO
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
    FROM CONEXAO CN 
    INTO :CON;
    
    IF (:CON IS NULL OR :CON = '') THEN
    BEGIN
        MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
        SUSPEND;
        EXIT;
    END
    ELSE
    BEGIN
        MSG_ERRO = 'CONEXÃO OK: ' || :CON;
    END

    
    -- GERA CODIGOS PS PARA FORMAS FARMACEUTICAS
    BEGIN
        UPDATE FORMAFARMACEUTICA FF
        SET FF.CODIGO_PS = GEN_ID(GEN_FORMAFARMACEUTICA,1)
        WHERE FF.CODIGO_PS IS NULL
        ORDER BY FF.DESCRICAOFORMA ASC;
    WHEN ANY DO BEGIN END
    END

    
    -- INSERE FORMAS FARMACEUTICAS NO SISTEMA DESTINO
    I_SQL = 'INSERT INTO FORMAFARMACEUTICA (CODIGO,NOMEFORMAFARMACEUTICA,NOMEROTULO,TIPO_USO,VALIDADE,VALORMINIMOATENDIMENTO,CODIGO_LABORATORIO,TIPOINFORME,CODIGO_FORMAFARMACEUTICA_TU,METODOUTILIZACAO,USOVALIDADE,DESCRICAOROTULO_TIPO,CADASTRO_CF,CADASTRO_DT,CADASTRO_LJ,ALTERACAO_CF,ALTERACAO_DT,ALTERACAO_LJ,ATIVO) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT
        FF.CODIGO_PS AS CODIGO,
        UPPER(FF.DESCRICAOFORMA) AS NOMEFORMAFARMACEUTICA,
        UPPER(FF.DESCRICAOFORMA) AS NOMEROTULO,
        3 AS TIPO_USO,
        FF.VALIDADEFORMA AS VALIDADE,
        CAST(FF.VALORMINIMOFORMA AS NUMERIC(18,2)) AS VALORMINIMOATENDIMENTO,
        1 AS CODIGO_LABORATORIO,
        0 AS TIPOINFORME,
        1 AS CODIGO_FORMAFARMACEUTICA_TU,
        1 AS METODOUTILIZACAO,
        1 AS USOVALIDADE,
        1 AS DESCRICAOROTULO_TIPO,
        1 AS CADASTRO_CF,
        CURRENT_TIMESTAMP AS CADASTRO_DT,
        1 AS CADASTRO_LJ,
        1 AS ALTERACAO_CF,
        CURRENT_TIMESTAMP AS ALTERACAO_DT,
        1 AS ALTERACAO_LJ,
        -1 AS ATIVO
    FROM FORMAFARMACEUTICA FF
    WHERE FF.CODIGO_PS IS NOT NULL
    ORDER BY 1
    INTO :CODIGO,:NOMEFORMAFARMACEUTICA,:NOMEROTULO,:TIPO_USO,:VALIDADE,:VALORMINIMOATENDIMENTO,:CODIGO_LABORATORIO,:TIPOINFORME,:CODIGO_FORMAFARMACEUTICA_TU,:METODOUTILIZACAO,:USOVALIDADE,:DESCRICAOROTULO_TIPO,:CADASTRO_CF,:CADASTRO_DT,:CADASTRO_LJ,:ALTERACAO_CF,:ALTERACAO_DT,:ALTERACAO_LJ,:ATIVO
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:NOMEFORMAFARMACEUTICA,:NOMEROTULO,:TIPO_USO,:VALIDADE,:VALORMINIMOATENDIMENTO,:CODIGO_LABORATORIO,:TIPOINFORME,:CODIGO_FORMAFARMACEUTICA_TU,:METODOUTILIZACAO,:USOVALIDADE,:DESCRICAOROTULO_TIPO,:CADASTRO_CF,:CADASTRO_DT,:CADASTRO_LJ,:ALTERACAO_CF,:ALTERACAO_DT,:ALTERACAO_LJ,:ATIVO)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

END;
