create or alter procedure EXTRACT_DATA_LOTE
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable MSG_ERRO varchar(100);
declare variable CODIGO integer;
declare variable TIPOLOTE integer;
declare variable CODIGO_MOV integer;
declare variable CODIGO_MOV_DET integer;
declare variable CODIGO_PRODUTO integer;
declare variable CODIGO_FORNECEDOR integer;
declare variable CODIGO_ESTOQUE_ORIGEM integer;
declare variable LOTE varchar(100);
declare variable CONCENTRACAO numeric(18,4);
declare variable DENSIDADE numeric(18,4);
declare variable UMIDADE integer;
declare variable UTR numeric(18,4);
declare variable UFC numeric(18,4);
declare variable TIPOESCALA varchar(10);
declare variable DINAMIZACAO integer;
declare variable FABRICACAO_DT date;
declare variable VENCIMENTO_DT date;
declare variable QUANTIDADE numeric(18,4);
declare variable FECHARLOTE integer;
declare variable LOTEUNIFICADO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT date;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable STATUSGERAL integer;
declare variable UI numeric(18,4);
declare variable FRACAO_ENTRADA integer;
declare variable CODIGO_ESTOQUE integer;
declare variable CODIGO_ESTOQUE_LOTE integer;
declare variable QTDE_ENTRADA numeric(18,4);
declare variable SALDO_DT timestamp;
declare variable STATUSLOTE integer;
declare variable ORIGEMLOTE integer;
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
    -- OBTEM STRING DE CONEXAO
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
    FROM CONEXAO CN 
    INTO :CON;
    
    IF (:CON IS NULL OR :CON = '') THEN
    BEGIN
        MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
        SUSPEND;
        EXIT;
    END
    ELSE
    BEGIN
        MSG_ERRO = 'CONEXÃO OK: ' || :CON;
    END
    -- GERA CODIGOS PS PARA LOTES
    BEGIN
        UPDATE LOTE L
        SET L.CODIGO_PS_LOTE = GEN_ID(GEN_ESTOQUE_LOTE,1),
            L.CODIGO_PS_LOTE_LA = GEN_ID(GEN_ESTOQUE_LOTE_LA,1)
        WHERE CAST(L.QUANTIDADELOTE AS NUMERIC(18,4)) - CAST(L.QUANTIDADECOMPROMETIDALOTE AS NUMERIC(18,4)) > 0
        AND EXISTS (SELECT 1
            FROM PRODUTO P
            WHERE P.CODIGOGRUPO = L.CODIGOGRUPO 
            AND P.CODIGOPRODUTO = L.CODIGOPRODUTO 
            AND P.CODIGO_PS IS NOT NULL);
    WHEN ANY DO BEGIN END
    END
    
    -- INSERE LOTES NO SISTEMA DESTINO (ESTOQUE_LOTE)
    I_SQL = 'INSERT INTO ESTOQUE_LOTE (CODIGO,TIPOLOTE,CODIGO_MOV,CODIGO_MOV_DET,CODIGO_PRODUTO,CODIGO_FORNECEDOR,CODIGO_ESTOQUE_ORIGEM,LOTE,CONCENTRACAO,DENSIDADE,UMIDADE,UTR,UFC,TIPOESCALA,DINAMIZACAO,FABRICACAO_DT,VENCIMENTO_DT,QUANTIDADE,FECHARLOTE,LOTEUNIFICADO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT,STATUSGERAL,UI,FRACAO_ENTRADA) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT 
        L.CODIGO_PS_LOTE AS CODIGO,
        0 AS TIPOLOTE,
        0 AS CODIGO_MOV,
        0 AS CODIGO_MOV_DET,
        P.CODIGO_PS AS CODIGO_PRODUTO,
        CAST(L.CODIGOFORNECEDOR AS INTEGER) AS CODIGO_FORNECEDOR,
        1 AS CODIGO_ESTOQUE_ORIGEM,
        L.LOTEFORNECEDOR AS LOTE,
        IIF(L.FATORCORRECAOLOTE IS NULL OR L.FATORCORRECAOLOTE = 0, 100, 100 / L.FATORCORRECAOLOTE) AS CONCENTRACAO,
        IIF(L.DENSIDADELOTE IS NULL OR (L.DENSIDADELOTE = 0), 1, L.DENSIDADELOTE) AS DENSIDADE,
        0 AS UMIDADE,
        COALESCE(L.FATORUTR, 0) AS UTR,
        CASE 
            WHEN L.FATORUFC >= 1000000000 THEN L.FATORUFC / 1000000000
            ELSE L.FATORUFC
        END AS UFC,
        CASE L.METODOLOTE
            WHEN 'C' THEN 'CH'
            WHEN 'CH-DG' THEN 'CH'
            WHEN 'CH/' THEN 'CH'
            WHEN 'CHM' THEN 'CH'
            WHEN 'CHM/' THEN 'CH'
            WHEN 'CHMM/M' THEN 'CH'
            WHEN 'CHMM/M/' THEN 'CH'
            WHEN 'CMM' THEN 'CH'
            WHEN 'CMM/' THEN 'CH'
            WHEN 'CMM/M' THEN 'CH'
            WHEN 'CMM/M/' THEN 'CH'
            WHEN 'LOTE:' THEN NULL
            WHEN 'LM/' THEN 'LM'
            ELSE L.METODOLOTE
        END AS TIPOESCALA,
        CAST(L.DINAMIZACAOLOTE AS INTEGER) AS DINAMIZACAO,
        CAST(L.DATAFABRICACAOLOTE AS DATE) AS FABRICACAO_DT,
        CAST(L.DATAVALIDADELOTE AS DATE) AS VENCIMENTO_DT,
        CAST(L.QUANTIDADELOTE AS NUMERIC(18,4)) - CAST(L.QUANTIDADECOMPROMETIDALOTE AS NUMERIC(18,4)) AS QUANTIDADE,
        0 AS FECHARLOTE,
        0 AS LOTEUNIFICADO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CAST(L.DT_CREATION AS DATE) AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        L.DT_ALTER AS ALTERACAO_DT,
        0 AS STATUSGERAL,
        COALESCE(L.FATORUI, 0) AS UI,
        0 AS FRACAO_ENTRADA
    FROM LOTE L
    INNER JOIN PRODUTO P ON P.CODIGOPRODUTO = L.CODIGOPRODUTO AND P.CODIGOGRUPO = L.CODIGOGRUPO
    WHERE CAST(L.QUANTIDADELOTE AS NUMERIC(18,4)) - CAST(L.QUANTIDADECOMPROMETIDALOTE AS NUMERIC(18,4)) > 0
    AND P.CODIGO_PS IS NOT NULL
    AND L.CODIGO_PS_LOTE IS NOT NULL
    ORDER BY 1
    INTO :CODIGO,:TIPOLOTE,:CODIGO_MOV,:CODIGO_MOV_DET,:CODIGO_PRODUTO,:CODIGO_FORNECEDOR,:CODIGO_ESTOQUE_ORIGEM,:LOTE,:CONCENTRACAO,:DENSIDADE,:UMIDADE,:UTR,:UFC,:TIPOESCALA,:DINAMIZACAO,:FABRICACAO_DT,:VENCIMENTO_DT,:QUANTIDADE,:FECHARLOTE,:LOTEUNIFICADO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT,:STATUSGERAL,:UI,:FRACAO_ENTRADA

    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:TIPOLOTE,:CODIGO_MOV,:CODIGO_MOV_DET,:CODIGO_PRODUTO,:CODIGO_FORNECEDOR,:CODIGO_ESTOQUE_ORIGEM,:LOTE,:CONCENTRACAO,:DENSIDADE,:UMIDADE,:UTR,:UFC,:TIPOESCALA,:DINAMIZACAO,:FABRICACAO_DT,:VENCIMENTO_DT,:QUANTIDADE,:FECHARLOTE,:LOTEUNIFICADO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT,:STATUSGERAL,:UI,:FRACAO_ENTRADA)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    -- INSERE LOTES_LA NO SISTEMA DESTINO (ESTOQUE_LOTE_LA)
    I_SQL = 'INSERT INTO ESTOQUE_LOTE_LA (CODIGO,CODIGO_ESTOQUE,CODIGO_ESTOQUE_LOTE,CODIGO_MOV,QTDE_ENTRADA,SALDO_DT,STATUSLOTE,ORIGEMLOTE,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT 
        L.CODIGO_PS_LOTE_LA AS CODIGO,
        CASE
            WHEN P.CODIGO_PS < 1000000 THEN 1
            WHEN P.CODIGO_PS > 1000000 AND P.CODIGO_PS < 1999999 THEN 3
            WHEN P.CODIGO_PS > 2000000 AND P.CODIGO_PS < 2999999 THEN 3
            WHEN P.CODIGO_PS > 3000000 AND P.CODIGO_PS < 3999999 THEN 2
            WHEN P.CODIGO_PS > 4000000 AND P.CODIGO_PS < 4999999 THEN 3
        END AS CODIGO_ESTOQUE,
        L.CODIGO_PS_LOTE AS CODIGO_ESTOQUE_LOTE,
        0 AS CODIGO_MOV,
        CAST(L.QUANTIDADELOTE AS NUMERIC(18,4)) - CAST(L.QUANTIDADECOMPROMETIDALOTE AS NUMERIC(18,4)) AS QTDE_ENTRADA,
        CURRENT_TIMESTAMP AS SALDO_DT,
        1 AS STATUSLOTE,
        0 AS ORIGEMLOTE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CURRENT_TIMESTAMP AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CURRENT_TIMESTAMP AS ALTERACAO_DT
    FROM LOTE L
    INNER JOIN PRODUTO P ON P.CODIGOPRODUTO = L.CODIGOPRODUTO AND P.CODIGOGRUPO = L.CODIGOGRUPO
    WHERE L.CODIGO_PS_LOTE_LA IS NOT NULL
    ORDER BY 1
    INTO :CODIGO,:CODIGO_ESTOQUE,:CODIGO_ESTOQUE_LOTE,:CODIGO_MOV,:QTDE_ENTRADA,:SALDO_DT,:STATUSLOTE,:ORIGEMLOTE,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:CODIGO_ESTOQUE,:CODIGO_ESTOQUE_LOTE,:CODIGO_MOV,:QTDE_ENTRADA,:SALDO_DT,:STATUSLOTE,:ORIGEMLOTE,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

END;