create or alter procedure EXTRACT_DATA_PROD_INTERNA
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable MSG_ERRO varchar(100);
declare variable CODIGO integer;
declare variable MOVIMENTOESTOQUE integer;
declare variable CODIGO_GRUPO integer;
declare variable CODIGO_ESTOQUE_CLASSIFICACAO integer;
declare variable CODIGO_ESTOQUE_TIPO integer;
declare variable NOMEPRODUTO varchar(300);
declare variable NOMEPRODUTO_FRACAO varchar(300);
declare variable NOMEPRODUTO_ROTULO varchar(300);
declare variable ATIVO integer;
declare variable CONCENTRACAO integer;
declare variable DENSIDADE integer;
declare variable INDICELUCROCVM integer;
declare variable USO_ATENDIMENTO integer;
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable CODIGO_FORMULA integer;
declare variable CODIGO_FORMAFARMACEUTICA integer;
declare variable MODOFAZER varchar(7000);
declare variable OPCAO_ATENDIMENTO integer;
declare variable PRECOSISTEMA integer;
declare variable OPCAO_ROTULO integer;
declare variable TIPOCADASTRO integer;
declare variable PESOFORMULA integer;
declare variable INDICECALCULO integer;
declare variable CONCLUIDO integer;
declare variable CODIGO_ESTOQUEF integer;
declare variable CODIGO_PRODUTO integer;
declare variable QUANTIDADE numeric(18,4);
declare variable UNIDADE varchar(20);
declare variable FASE smallint;
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
    -- OBTEM STRING DE CONEXAO
    SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
    FROM CONEXAO CN 
    INTO :CON;
    
    IF (:CON IS NULL OR :CON = '') THEN
    BEGIN
        MSG_ERRO = 'CONEXÃƒO BANCO DE DADOS PHARMACIE NAO CONFIGURADA';
        SUSPEND;
        EXIT;
    END
    ELSE
    BEGIN
        MSG_ERRO = 'CONEXAO OK: ' || :CON;
    END    
    BEGIN
        UPDATE FORMULAPADRAO F
        SET F.CODIGO_PRODUTO_PS = (SELECT FIRST 1 P.CODIGO_PS FROM PRODUTO P WHERE P.CODIGOPRODUTO = F.CODIGOPRODUTO AND P.CODIGOGRUPO = F.CODIGOGRUPO)
        WHERE F.CODIGO_PRODUTO_PS IS NULL;
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        UPDATE FORMULAPADRAO F
        SET F.OPCAO_ATENDIMENTO_PS = 2
        WHERE F.CODIGO_PRODUTO_PS IS NULL
        AND F.TIPOFORMULAPADRAO = 2;
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        UPDATE FORMULAPADRAO F
        SET F.CODIGO_PRODUTO_PS = GEN_ID(GEN_ESTOQUE_GERAL1, 1)+1000000
        WHERE F.OPCAO_ATENDIMENTO_PS = 2;
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        UPDATE FORMULAPADRAO F
        SET F.CODIGO_ESTOQUEF = GEN_ID(GEN_ESTOQUEF,1)
        WHERE F.CODIGO_PRODUTO_PS IS NOT NULL;
    WHEN ANY DO BEGIN END
    END

    I_SQL = 'INSERT INTO ESTOQUE_GERAL (CODIGO,MOVIMENTOESTOQUE,CODIGO_GRUPO,CODIGO_ESTOQUE_CLASSIFICACAO,CODIGO_ESTOQUE_TIPO,NOMEPRODUTO,NOMEPRODUTO_FRACAO,NOMEPRODUTO_ROTULO,ATIVO,CONCENTRACAO,DENSIDADE,INDICELUCROCVM,USO_ATENDIMENTO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT
        F.CODIGO_PRODUTO_PS AS CODIGO,
        IIF(F.CODIGO_PRODUTO_PS < 1999999, 1, 3) AS MOVIMENTOESTOQUE,
        IIF(F.CODIGO_PRODUTO_PS < 1999999, 100000, 300000) AS CODIGO_GRUPO,
        IIF(F.CODIGO_PRODUTO_PS < 1999999, 100000, 300000) AS CODIGO_ESTOQUE_CLASSIFICACAO,
        IIF(F.CODIGO_PRODUTO_PS < 1999999, 100000, 300000) AS CODIGO_ESTOQUE_TIPO,
        UPPER(F.DESCRICAOFORMULAPADRAO) || ' (PRODUCAO INTERNA)' AS NOMEPRODUTO,
        UPPER(F.DESCRICAOFORMULAPADRAO) || ' (PRODUCAO INTERNA)' AS NOMEPRODUTO_FRACAO,
        UPPER(F.DESCRICAOFORMULAPADRAO) AS NOMEPRODUTO_ROTULO,
        -1 AS ATIVO,
        100 AS CONCENTRACAO,
        1 AS DENSIDADE,
        1 AS INDICELUCROCVM,
        -1 AS USO_ATENDIMENTO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CURRENT_TIMESTAMP AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CURRENT_TIMESTAMP AS ALTERACAO_DT
    FROM FORMULAPADRAO F
    WHERE F.OPCAO_ATENDIMENTO_PS = 2
    INTO :CODIGO,:MOVIMENTOESTOQUE,:CODIGO_GRUPO,:CODIGO_ESTOQUE_CLASSIFICACAO,:CODIGO_ESTOQUE_TIPO,:NOMEPRODUTO,:NOMEPRODUTO_FRACAO,:NOMEPRODUTO_ROTULO,:ATIVO,:CONCENTRACAO,:DENSIDADE,:INDICELUCROCVM,:USO_ATENDIMENTO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:MOVIMENTOESTOQUE,:CODIGO_GRUPO,:CODIGO_ESTOQUE_CLASSIFICACAO,:CODIGO_ESTOQUE_TIPO,:NOMEPRODUTO,:NOMEPRODUTO_FRACAO,:NOMEPRODUTO_ROTULO,:ATIVO,:CONCENTRACAO,:DENSIDADE,:INDICELUCROCVM,:USO_ATENDIMENTO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    I_SQL = 'INSERT INTO ESTOQUEF (CODIGO,MOVIMENTOESTOQUE,CODIGO_FORMULA,CODIGO_FORMAFARMACEUTICA,MODOFAZER,OPCAO_ATENDIMENTO,PRECOSISTEMA,OPCAO_ROTULO,TIPOCADASTRO,PESOFORMULA,INDICECALCULO,CONCLUIDO,CADASTRO_LJ,CADASTRO_CF,CADASTRO_DT,ALTERACAO_LJ,ALTERACAO_CF,ALTERACAO_DT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)';
    
    FOR SELECT
        F.CODIGO_ESTOQUEF AS CODIGO,
        CASE
            WHEN F.CODIGO_PRODUTO_PS < 1000000 THEN 0
            WHEN F.CODIGO_PRODUTO_PS > 1000000 AND F.CODIGO_PRODUTO_PS < 1999999 THEN 1
            WHEN F.CODIGO_PRODUTO_PS > 2000000 AND F.CODIGO_PRODUTO_PS < 2999999 THEN 2
            WHEN F.CODIGO_PRODUTO_PS > 3000000 AND F.CODIGO_PRODUTO_PS < 3999999 THEN 3
            WHEN F.CODIGO_PRODUTO_PS > 4000000 AND F.CODIGO_PRODUTO_PS < 4999999 THEN 4
        END AS MOVIMENTOESTOQUE,
        F.CODIGO_PRODUTO_PS AS CODIGO_FORMULA,
        FF.CODIGO_PS AS CODIGO_FORMAFARMACEUTICA,
        UPPER(
        CASE
            -- 1. Quando AMBOS os campos tem texto
            WHEN COALESCE(TRIM(F.OBSERVACAOFORMULAPADRAO), '') <> '' AND COALESCE(TRIM(F.OBSERVACAOETIQUETA), '') <> ''
            THEN CAST(F.OBSERVACAOFORMULAPADRAO AS VARCHAR(7000)) || (ASCII_CHAR(13) || ASCII_CHAR(10)) || CAST(F.OBSERVACAOETIQUETA AS VARCHAR(7000))

            -- 2. Quando apenas o PRIMEIRO campo tem texto
            WHEN COALESCE(TRIM(F.OBSERVACAOFORMULAPADRAO), '') <> ''
            THEN CAST(F.OBSERVACAOFORMULAPADRAO AS VARCHAR(7000))

            -- 3. Quando apenas o SEGUNDO campo tem texto
            WHEN COALESCE(TRIM(F.OBSERVACAOETIQUETA), '') <> ''
            THEN CAST(F.OBSERVACAOETIQUETA AS VARCHAR(7000))

            -- 4. Quando ambos estao vazios ou nulos
            ELSE ''
        END
        ) AS MODOFAZER,
        COALESCE(F.OPCAO_ATENDIMENTO_PS, 0) AS OPCAO_ATENDIMENTO,
        0 AS PRECOSISTEMA,
        0 AS OPCAO_ROTULO,
        CASE
            WHEN F.CODIGO_PRODUTO_PS > 1000000 AND F.CODIGO_PRODUTO_PS < 1999999 THEN 1
            WHEN F.CODIGO_PRODUTO_PS > 3000000 AND F.CODIGO_PRODUTO_PS < 3999999 THEN 2
            ELSE 1
        END AS TIPOCADASTRO,
        COALESCE(F.VOLUMEBASEFORMULAPADRAO, 100) AS PESOFORMULA,
        1 AS INDICECALCULO,
        -1 AS CONCLUIDO,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        CURRENT_TIMESTAMP AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        CURRENT_TIMESTAMP AS ALTERACAO_DT
    FROM FORMULAPADRAO F
    INNER JOIN FORMAFARMACEUTICA FF ON FF.CODIGOFORMA = F.CODIGOFORMA
    WHERE F.CODIGO_ESTOQUEF IS NOT NULL
    INTO :CODIGO,:MOVIMENTOESTOQUE,:CODIGO_FORMULA,:CODIGO_FORMAFARMACEUTICA,:MODOFAZER,:OPCAO_ATENDIMENTO,:PRECOSISTEMA,:OPCAO_ROTULO,:TIPOCADASTRO,:PESOFORMULA,:INDICECALCULO,:CONCLUIDO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO,:MOVIMENTOESTOQUE,:CODIGO_FORMULA,:CODIGO_FORMAFARMACEUTICA,:MODOFAZER,:OPCAO_ATENDIMENTO,:PRECOSISTEMA,:OPCAO_ROTULO,:TIPOCADASTRO,:PESOFORMULA,:INDICECALCULO,:CONCLUIDO,:CADASTRO_LJ,:CADASTRO_CF,:CADASTRO_DT,:ALTERACAO_LJ,:ALTERACAO_CF,:ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    
    BEGIN
        UPDATE ITEMFORMULAPADRAO FI
        SET FI.CODIGO_ESTOQUEF = (
            SELECT FIRST 1 F.CODIGO_ESTOQUEF 
            FROM FORMULAPADRAO F 
            WHERE F.CODIGOFORMULAPADRAO = FI.CODIGOFORMULAPADRAO
        );
    WHEN ANY DO BEGIN END
    END

    I_SQL = 'INSERT INTO ESTOQUEF_DETALHE (CODIGO, CODIGO_ESTOQUEF, FASE, CODIGO_PRODUTO, QUANTIDADE, UNIDADE, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR     -- Query 1: Itens da Formula
    SELECT
        GEN_ID(GEN_ESTOQUEF_DETALHE, 1) AS CODIGO,
        FI.CODIGO_ESTOQUEF AS CODIGO_ESTOQUEF,
        FI.FASEITEMFORMULA AS FASE,
        P.CODIGO_PS AS CODIGO_PRODUTO,
        CAST(
            IIF(
                FI.CALCULOITEMFORMULA = 2, COALESCE (FP.VOLUMEBASEFORMULAPADRAO,100), FI.QUANTIDADEITEMFORMULA
            ) AS NUMERIC(18,4)
        ) AS QUANTIDADE,

        LOWER(
            IIF(
                FI.CALCULOITEMFORMULA = 0, '%',
                IIF(FI.CALCULOITEMFORMULA = 2, 'qsp(g)',
                    CASE
                        WHEN P.SIGLAUNIDADE = 'UN' THEN 'u'
                        WHEN FI.SIGLAUNIDADE IS NULL THEN P.SIGLAUNIDADE
                        ELSE FI.SIGLAUNIDADE
                    END
                )
            )
        ) AS UNIDADE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        FI.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        FI.DT_ALTER AS ALTERACAO_DT
    FROM ITEMFORMULAPADRAO FI
    INNER JOIN PRODUTO P
        ON P.CODIGOPRODUTO = FI.CODIGOPRODUTO
        AND P.CODIGOGRUPO = FI.CODIGOGRUPO
    INNER JOIN FORMULAPADRAO FP
        ON FP.CODIGOFORMULAPADRAO = FI.CODIGOFORMULAPADRAO
    WHERE FI.CODIGO_ESTOQUEF IS NOT NULL
      AND P.CODIGO_PS IS NOT NULL -- 12

    UNION ALL

    -- Query 2: Embalagem
    SELECT
        GEN_ID(GEN_ESTOQUEF_DETALHE, 1) AS CODIGO,
        FP.CODIGO_ESTOQUEF AS CODIGO_ESTOQUEF,
        NULL AS FASE,
        P.CODIGO_PS AS CODIGO_PRODUTO,
        FP.QTDEEMBALAGEMFORMULAPADRAO AS QUANTIDADE,
        'u' AS UNIDADE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        FP.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        FP.DT_ALTER AS ALTERACAO_DT
    FROM FORMULAPADRAO FP
    INNER JOIN PRODUTO P ON P.CODIGOPRODUTO = FP.CODIGOPRODUTOEMBALAGEM AND P.CODIGOGRUPO = FP.CODIGOGRUPOEMBALAGEM
    WHERE
        FP.CODIGO_ESTOQUEF IS NOT NULL -- 12

    UNION ALL

    -- Query 3: Capsula
    SELECT
        GEN_ID(GEN_ESTOQUEF_DETALHE, 1) AS CODIGO,
        FP.CODIGO_ESTOQUEF AS CODIGO_ESTOQUEF,
        NULL AS FASE,
        P.CODIGO_PS AS CODIGO_PRODUTO,
        FP.CAPSULASBASEFORMULAPADRAO AS QUANTIDADE,
        'u' AS UNIDADE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        FP.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        FP.DT_ALTER AS ALTERACAO_DT
    FROM FORMULAPADRAO FP
    INNER JOIN PRODUTO P ON P.CODIGOPRODUTO = FP.CODIGOPRODUTOCAPSULA AND P.CODIGOGRUPO = FP.CODIGOGRUPOCAPSULA
    WHERE
        FP.CODIGO_ESTOQUEF IS NOT NULL --12
    INTO :CODIGO, :CODIGO_ESTOQUEF, :FASE, :CODIGO_PRODUTO, :QUANTIDADE, :UNIDADE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
        EXECUTE STATEMENT (:I_SQL) (:CODIGO, :CODIGO_ESTOQUEF, :FASE, :CODIGO_PRODUTO, :QUANTIDADE, :UNIDADE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT)
        ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

END;