create or alter procedure EXTRACT_DATA_MEDICO (
    V_CONVERSAO integer)
as
declare variable V_USER varchar(20);
declare variable V_SHA varchar(20);
declare variable CON varchar(60);
declare variable I_SQL varchar(3000);
declare variable ERROR_MESSAGE varchar(300);
declare variable CODIGO integer;
declare variable NOMEESPECIALIDADE varchar(150);
declare variable CADASTRO_LJ integer;
declare variable CADASTRO_CF integer;
declare variable CADASTRO_DT timestamp;
declare variable ALTERACAO_LJ integer;
declare variable ALTERACAO_CF integer;
declare variable ALTERACAO_DT timestamp;
declare variable NOMEMEDICO varchar(300);
declare variable CODIGO_GRUPO integer;
declare variable CODIGO_MEDICO_ESPECIALIDADE integer;
declare variable CODIGO_CONSELHO_REGIONAL integer;
declare variable CRM varchar(30);
declare variable CR_ESTADO varchar(3);
declare variable SEXO integer;
declare variable EMAIL varchar(300);
declare variable DIANASCIMENTO integer;
declare variable MESNASCIMENTO integer;
declare variable ANONASCIMENTO integer;
declare variable ATIVO integer;
declare variable TIPO_CADASTRO integer;
declare variable CODIGO_CADASTRO integer;
declare variable ENDERECO varchar(500);
declare variable NUMERO varchar(30);
declare variable OBSERVACAO_END varchar(2000);
declare variable CODIGO_REGIAODETALHE integer;
declare variable CODIGO_CIDADEESTADO integer;
declare variable CEP varchar(30);
declare variable TELEFONE_TIPO integer;
declare variable TELEFONEPREFIXO varchar(4);
declare variable TELEFONE varchar(30);
declare variable MSG_ERRO varchar(100);
BEGIN
    V_USER = 'SYSDBA';
    V_SHA = 'SySPs_PHARMACIE';
    
        -- OBTEM STRING DE CONEXAO
        SELECT FIRST 1 CN.IPSERVER || '/' || CN.PORTA || ':' || CN.ALIAS 
        FROM CONEXAO CN 
        INTO :CON;
        
        IF (:CON IS NULL OR :CON = '') THEN
        BEGIN
            MSG_ERRO = 'CONEXÃO BANCO DE DADOS PHARMACIE NÃO CONFIGURADA';
            SUSPEND;
            EXIT;
        END
        ELSE
        BEGIN
            MSG_ERRO = 'CONEXÃO OK: ' || :CON;
        END
    
    -- ATUALIZA CAMPO CONVERSAO
    BEGIN
        UPDATE MEDICO M 
        SET M.CONVERSAO = :V_CONVERSAO 
        WHERE M.CODIGO_PS IS NULL;
    END
    -- GERA CODIGO_PS PARA MEDICOS
    BEGIN
        UPDATE MEDICO M 
        SET M.CODIGO_PS = GEN_ID(GEN_MEDICO,1) 
        ORDER BY M.CODIGOMEDICO;
    WHEN ANY DO BEGIN END
    END

    -- INSERE ESPECIALIDADES NO SISTEMA DESTINO
    I_SQL = 'INSERT INTO MEDICO_ESPECIALIDADE (CODIGO, NOMEESPECIALIDADE, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT 
        CAST(E.CODIGOESPECIALIDADE AS INTEGER) AS CODIGO,
        UPPER(E.DESCRICAOESPECIALIDADE) AS NOMEESPECIALIDADE,
        1 AS CADASTRO_LJ,
        1 AS CADASTRO_CF,
        E.DT_CREATION AS CADASTRO_DT,
        1 AS ALTERACAO_LJ,
        1 AS ALTERACAO_CF,
        E.DT_ALTER AS ALTERACAO_DT
    FROM ESPECIALIDADE E
    WHERE E.CODIGOESPECIALIDADE <> 1
    ORDER BY 1
    INTO :CODIGO, :NOMEESPECIALIDADE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :NOMEESPECIALIDADE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- INSERE MÉDICOS NO SISTEMA DESTINO
    I_SQL = 'INSERT INTO MEDICO (CODIGO, NOMEMEDICO, CODIGO_GRUPO, CODIGO_MEDICO_ESPECIALIDADE, CODIGO_CONSELHO_REGIONAL, CRM, CR_ESTADO, SEXO, EMAIL, DIANASCIMENTO, MESNASCIMENTO, ANONASCIMENTO, ATIVO, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT 
        M.CODIGO_PS AS CODIGO,
        UPPER(M.NOMEMEDICO) AS NOMEMEDICO,
        700000 AS CODIGO_GRUPO,
        COALESCE((SELECT FIRST 1 CAST(EM.CODIGOESPECIALIDADE AS INTEGER) FROM ESPECIALIDADEMEDICO EM WHERE EM.CODIGOMEDICO = M.CODIGOMEDICO), 1) AS CODIGO_MEDICO_ESPECIALIDADE,
        CASE M.TIPOCRMEDICO
            WHEN 'B' THEN 12
            WHEN 'BM' THEN 12
            WHEN 'BR' THEN 1
            WHEN 'C' THEN 1
            WHEN 'CO' THEN 6
            WHEN 'CR' THEN 8
            WHEN 'E' THEN 1
            WHEN 'EF' THEN 1
            WHEN 'EN' THEN 1
            WHEN 'ES' THEN 1
            WHEN 'F' THEN 7
            WHEN 'FI' THEN 9
            WHEN 'FT' THEN 8
            WHEN 'HO' THEN 10
            WHEN 'IT' THEN 1
            WHEN 'M' THEN 1
            WHEN 'MB' THEN 9
            WHEN 'ME' THEN 1
            WHEN 'MV' THEN 2
            WHEN 'N' THEN 5
            WHEN 'O' THEN 3
            WHEN 'P' THEN 4
            WHEN 'R' THEN 9
            WHEN 'RF' THEN 13
            WHEN 'RM' THEN 9
            WHEN 'RN' THEN 5
            WHEN 'RO' THEN 3
            WHEN 'RP' THEN 4
            WHEN 'RT' THEN 6
            WHEN 'T' THEN 6
            WHEN 'TE' THEN 6
            WHEN 'TH' THEN 6
            WHEN 'V' THEN 2
            ELSE 1
        END AS CODIGO_CONSELHO_REGIONAL,
        M.CRMMEDICO AS CRM,
        M.SIGLAESTADOCRMMEDICO AS CR_ESTADO,
        CASE M.GENERO
            WHEN 'M' THEN 1
            WHEN 'F' THEN 2
            ELSE 1
        END AS SEXO,
        IIF(M.EMAILMEDICO = '', NULL, LOWER(M.EMAILMEDICO)) AS EMAIL,
        COALESCE(EXTRACT(DAY FROM M.DT_NASCIMENTO), 0) AS DIANASCIMENTO,
        COALESCE(EXTRACT(MONTH FROM M.DT_NASCIMENTO), 0) AS MESNASCIMENTO,
        COALESCE(EXTRACT(YEAR FROM M.DT_NASCIMENTO), 0) AS ANONASCIMENTO,
                -1 AS ATIVO,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
        M.DT_CREATION AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
        M.DT_ALTER AS ALTERACAO_DT
    FROM MEDICO M
    WHERE M.CONVERSAO = :V_CONVERSAO
    ORDER BY 1
    INTO :CODIGO, :NOMEMEDICO, :CODIGO_GRUPO, :CODIGO_MEDICO_ESPECIALIDADE, :CODIGO_CONSELHO_REGIONAL, :CRM, :CR_ESTADO, :SEXO, :EMAIL, :DIANASCIMENTO, :MESNASCIMENTO, :ANONASCIMENTO, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
            DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :NOMEMEDICO, :CODIGO_GRUPO, :CODIGO_MEDICO_ESPECIALIDADE, :CODIGO_CONSELHO_REGIONAL, :CRM, :CR_ESTADO, :SEXO, :EMAIL, :DIANASCIMENTO, :MESNASCIMENTO, :ANONASCIMENTO, :ATIVO, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    -- INSERE ENDEREÇOS DOS MÉDICOS
    I_SQL = 'INSERT INTO CADASTRO_ENDERECO (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, ENDERECO, NUMERO, OBSERVACAO, CODIGO_REGIAODETALHE, CODIGO_CIDADEESTADO, CEP, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    FOR SELECT
        GEN_ID(GEN_CADASTRO_ENDERECO, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
        M.CODIGO_PS AS CODIGO_CADASTRO,
        UPPER(COALESCE(M.ENDERECOMEDICO, '') || IIF(M.ENDERECOMEDICO <> '', ', ', '') || COALESCE(B.NOMEBAIRRO, '')) AS ENDERECO,
        IIF(NULLIF(TRIM(M.NUMEROENDERECOMEDICO), '') IS NULL, 'S/N', M.NUMEROENDERECOMEDICO) AS NUMERO,
        IIF(NULLIF(TRIM(M.COMPLEMENTOMEDICO), '') IS NULL, NULL, UPPER(M.COMPLEMENTOMEDICO)) AS OBSERVACAO,
                1 AS CODIGO_REGIAODETALHE,
        IIF(C.CODIGO_PS IS NOT NULL, C.CODIGO_PS, 1) AS CODIGO_CIDADEESTADO,
        IIF(NULLIF(TRIM(M.CEPMEDICO), '00000000') IS NULL, '00000000', M.CEPMEDICO) AS CEP,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
        M.DT_CREATION AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
        M.DT_ALTER AS ALTERACAO_DT
    FROM MEDICO M
        LEFT JOIN CIDADE C ON C.CODIGOCIDADE = M.CODIGOCIDADE
        LEFT JOIN BAIRRO B ON B.CODIGOBAIRRO = M.CODIGOBAIRRO
    WHERE M.ENDERECOMEDICO NOT IN ('', '.', ',', '*', '+', '+.')
    AND M.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :ENDERECO, :NUMERO, :OBSERVACAO_END, :CODIGO_REGIAODETALHE, :CODIGO_CIDADEESTADO, :CEP, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END
    -- INSERE TELEFONES DOS MÉDICOS
    I_SQL = 'INSERT INTO CADASTRO_TELEFONE (CODIGO, TIPO_CADASTRO, CODIGO_CADASTRO, TELEFONE_TIPO, TELEFONEPREFIXO, TELEFONE, CADASTRO_LJ, CADASTRO_CF, CADASTRO_DT, ALTERACAO_LJ, ALTERACAO_CF, ALTERACAO_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)';
    
    -- TELEFONES FIXOS
    FOR SELECT
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
        M.CODIGO_PS AS CODIGO_CADASTRO,
        2 AS TELEFONE_TIPO,
        IIF(
            TRIM(M.DDDTELEFONEMEDICO) IS NULL OR TRIM(M.DDDTELEFONEMEDICO) = '',
            '',
            IIF(
                SUBSTRING(TRIM(M.DDDTELEFONEMEDICO) FROM 1 FOR 1) = '0',
                SUBSTRING(TRIM(M.DDDTELEFONEMEDICO) FROM 2 FOR 2),
                SUBSTRING(TRIM(M.DDDTELEFONEMEDICO) FROM 1 FOR 2)
            )
        ) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(M.TELEFONEMEDICO)) FROM 1 FOR 18) AS TELEFONE,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
        M.DT_CREATION AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
        M.DT_ALTER AS ALTERACAO_DT
    FROM MEDICO M
    WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(M.TELEFONEMEDICO)) <> ''
    AND M.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
    END

    -- CELULARES
    FOR SELECT
        GEN_ID(GEN_CADASTRO_TELEFONE, 1) AS CODIGO,
                2 AS TIPO_CADASTRO,
        M.CODIGO_PS AS CODIGO_CADASTRO,
        3 AS TELEFONE_TIPO, -- assume que todo celular é tipo 3
        IIF(
            TRIM(M.DDDCELULARMEDICO) IS NULL OR TRIM(M.DDDCELULARMEDICO) = '',
            '',
            IIF(
                SUBSTRING(TRIM(M.DDDCELULARMEDICO) FROM 1 FOR 1) = '0',
                SUBSTRING(TRIM(M.DDDCELULARMEDICO) FROM 2 FOR 2),
                SUBSTRING(TRIM(M.DDDCELULARMEDICO) FROM 1 FOR 2)
            )
        ) AS TELEFONEPREFIXO,
        SUBSTRING((SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(M.CELULARMEDICO)) FROM 1 FOR 18) AS TELEFONE,
                1 AS CADASTRO_LJ,
                1 AS CADASTRO_CF,
        M.DT_CREATION AS CADASTRO_DT,
                1 AS ALTERACAO_LJ,
                1 AS ALTERACAO_CF,
        M.DT_ALTER AS ALTERACAO_DT
    FROM MEDICO M
    WHERE (SELECT ONLY_NUMBERS FROM STRIP_NON_NUMERIC(M.CELULARMEDICO)) <> ''
    AND M.CONVERSAO = :V_CONVERSAO
    INTO :CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT
    DO BEGIN
    EXECUTE STATEMENT (:I_SQL) (:CODIGO, :TIPO_CADASTRO, :CODIGO_CADASTRO, :TELEFONE_TIPO, :TELEFONEPREFIXO, :TELEFONE, :CADASTRO_LJ, :CADASTRO_CF, :CADASTRO_DT, :ALTERACAO_LJ, :ALTERACAO_CF, :ALTERACAO_DT) 
    ON EXTERNAL :CON AS USER :V_USER PASSWORD :V_SHA WITH COMMON TRANSACTION;
                END
END;