CREATE OR ALTER PROCEDURE UTIL_EXTRACT_PRISMA5
AS
DECLARE VARIABLE I_SQL VARCHAR(200);
DECLARE VARIABLE ERROR_MESSAGE VARCHAR(300);
BEGIN
    BEGIN
        EXECUTE STATEMENT 'CREATE TABLE CIDADEESTADO (CODIGO INTEGER NOT NULL, CODIGO_IBGE INTEGER, NOMECIDADE VARCHAR(60), UF VARCHAR(2), CODIGO_PAIS INTEGER, CADASTRO_LJ SMALLINT, CADASTRO_DT TIMESTAMP, CADASTRO_CF INTEGER, ALTERACAO_LJ SMALLINT, ALTERACAO_DT TIMESTAMP, ALTERACAO_CF INTEGER, CODIGO_MUNICIPIO INTEGER, REGISTRO_CEP SMALLINT)';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE TABLE GRUPO_PHARMACIE (CODIGOGRUPO INTEGER, DESCRICAOGRUPO VARCHAR(150), MOVIMENTOESTOQUE SMALLINT)';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE TABLE CONEXAO (ALIAS VARCHAR(60), IPSERVER VARCHAR(60), PORTA VARCHAR(4))';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A1';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A2';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_REFAZER_A3';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_ENDERECO';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER SEQUENCE GEN_CADASTRO_ENDERECO RESTART WITH 2';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CADASTRO_TELEFONE';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_GRUPO0';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_GRUPO1';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_GRUPO2';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_GRUPO3';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_GRUPO4';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL0';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL1';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL2';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL3';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_GERAL4';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_CLIENTE';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_LOTE_LA';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_FORMAFARMACEUTICA';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUEF';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUEF_DETALHE';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_ESTOQUE_MINMAX';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE SEQUENCE GEN_MEDICO';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CIDADE ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE GRUPO ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD CONVERSAO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE SINONIMO ADD CONVERSAO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE PRODUTO ADD NOVO SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE SINONIMO ADD CODIGO_PRODUTO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE SINONIMO ADD CODIGO_SINONIMO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE SINONIMO ADD NOVO SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAPADRAO ADD CODIGO_PRODUTO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAPADRAO ADD CODIGO_ESTOQUEF INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE ITEMFORMULAPADRAO ADD CODIGO_ESTOQUEF INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAPADRAO ADD OPCAO_ATENDIMENTO_PS SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE ITEMFORMULAVENDA ADD CODIGO_ESTOQUEF INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE ITEMFORMULAVENDA ADD CODIGO_PS_A1 INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE ITEMFORMULAVENDA ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CLIENTE ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CLIENTE ADD NOVO SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CLIENTE ADD CONVERSAO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CLIENTE_ENDERECO_ENTREGA ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE LOTE ADD CODIGO_PS_LOTE INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE LOTE ADD CODIGO_PS_LOTE_LA INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE VENDA ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE VENDA ADD CONVERSAO INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAVENDA ADD CONVERSAO INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE ITEMFORMULAVENDA ADD CONVERSAO INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE VENDA ADD CODIGO_MEDICO INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAVENDA ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMULAVENDA ADD CODIGO_PS_A1 INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE MEDICO ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE MEDICO ADD CONVERSAO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE MEDICO ADD ENVIADO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE MEDICO ADD NOVO SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORNECEDOR ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORNECEDOR ADD CONVERSAO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORNECEDOR ADD ENVIADO SMALLINT';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORNECEDOR ADD NOVO SMALLINT';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE VISITADOR ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE FORMAFARMACEUTICA ADD CODIGO_PS INTEGER';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE GRUPO_PHARMACIE ADD CODIGO_GRUPO_PHARMACIE INTEGER';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE DESCENDING INDEX VENDA_IDX2 ON VENDA (CODIGO_PS)';
    WHEN ANY DO BEGIN END
    END

    BEGIN
        EXECUTE STATEMENT 'CREATE INDEX VENDA_IDX1 ON VENDA (CODIGO_PS)';
    WHEN ANY DO BEGIN END
    END
    
    BEGIN
        EXECUTE STATEMENT 'ALTER TABLE CIDADEESTADO ADD CONSTRAINT PK_CIDADEESTADO PRIMARY KEY (CODIGO)';
    WHEN ANY DO BEGIN END
    END

END;