// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHistoryStatus() {
  return window['go']['app']['App']['CheckHistoryStatus']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetEnvDefaults() {
  return window['go']['app']['App']['GetEnvDefaults']();
}

export function GetLastRunInfo(arg1, arg2) {
  return window['go']['app']['App']['GetLastRunInfo'](arg1, arg2);
}

export function GetOptionNames(arg1) {
  return window['go']['app']['App']['GetOptionNames'](arg1);
}

export function LoadClientConfig(arg1, arg2) {
  return window['go']['app']['App']['LoadClientConfig'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['app']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function ReconnectHistory() {
  return window['go']['app']['App']['ReconnectHistory']();
}

export function SaveClientConfig(arg1) {
  return window['go']['app']['App']['SaveClientConfig'](arg1);
}

export function SelectDBFile() {
  return window['go']['app']['App']['SelectDBFile']();
}

export function SelectExcelFile() {
  return window['go']['app']['App']['SelectExcelFile']();
}

export function StartMigration(arg1) {
  return window['go']['app']['App']['StartMigration'](arg1);
}

export function StopMigration() {
  return window['go']['app']['App']['StopMigration']();
}
