// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {models} from '../models';

export function CheckHistoryStatus():Promise<app.HistoryStatus>;

export function GetAppVersion():Promise<string>;

export function GetEnvDefaults():Promise<app.EnvDefaults>;

export function GetLastRunInfo(arg1:string,arg2:string):Promise<app.LastRunInfo>;

export function GetOptionNames(arg1:string):Promise<Array<app.OptionDef>>;

export function LoadClientConfig(arg1:string,arg2:string):Promise<models.ClientConfig>;

export function Login(arg1:string,arg2:string):Promise<app.LoginResult>;

export function Logout():Promise<void>;

export function ReconnectHistory():Promise<void>;

export function SaveClientConfig(arg1:models.ClientConfig):Promise<void>;

export function SelectExcelFile():Promise<string>;

export function StartMigration(arg1:models.MigrationConfig):Promise<void>;

export function StopMigration():Promise<void>;
