-- Prime Migration - Banco central de histórico (Firebird 2.5+)
-- Executar no servidor com isql ou FlameRobin; charset WIN1252.

SET NAMES WIN1252;

-- Generators
CREATE GENERATOR GEN_CLIENTES_MIGRACAO_ID;
SET GENERATOR GEN_CLIENTES_MIGRACAO_ID TO 0;

CREATE GENERATOR GEN_MIGRATION_RECORDS_ID;
SET GENERATOR GEN_MIGRATION_RECORDS_ID TO 0;

CREATE GENERATOR GEN_MIGRATION_ERRORS_ID;
SET GENERATOR GEN_MIGRATION_ERRORS_ID TO 0;

-- CLIENTES_MIGRACAO
CREATE TABLE CLIENTES_MIGRACAO (
    ID INTEGER NOT NULL PRIMARY KEY,
    CLIENT_CODE VARCHAR(50) NOT NULL UNIQUE,
    NOME VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET TERM ^ ;
CREATE TRIGGER BI_CLIENTES_MIGRACAO FOR CLIENTES_MIGRACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CLIENTES_MIGRACAO_ID, 1);
END^
SET TERM ; ^

-- MIGRATION_RUNS
CREATE TABLE MIGRATION_RUNS (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CLIENT_ID INTEGER NOT NULL REFERENCES CLIENTES_MIGRACAO(ID),
    SYSTEM VARCHAR(20) NOT NULL,
    OPTIONS VARCHAR(30),
    MODE VARCHAR(20) DEFAULT 'COMPLETA',
    STATUS VARCHAR(20) DEFAULT 'EM_ANDAMENTO',
    STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FINISHED_AT TIMESTAMP,
    IMPLANTADOR VARCHAR(100),
    OBS BLOB SUB_TYPE TEXT
);

-- MIGRATION_RECORDS
CREATE TABLE MIGRATION_RECORDS (
    ID INTEGER NOT NULL PRIMARY KEY,
    RUN_ID CHAR(36) NOT NULL REFERENCES MIGRATION_RUNS(ID),
    CLIENT_ID INTEGER NOT NULL REFERENCES CLIENTES_MIGRACAO(ID),
    ENTITY_TYPE SMALLINT NOT NULL,
    SOURCE_ID VARCHAR(50) NOT NULL,
    DESTINATION_ID VARCHAR(50),
    SOURCE_HASH VARCHAR(64),
    MIGRATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET TERM ^ ;
CREATE TRIGGER BI_MIGRATION_RECORDS FOR MIGRATION_RECORDS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_MIGRATION_RECORDS_ID, 1);
END^
SET TERM ; ^

CREATE UNIQUE INDEX UQ_MIGREC_CLI_ENT_SRC
ON MIGRATION_RECORDS (CLIENT_ID, ENTITY_TYPE, SOURCE_ID);

-- MIGRATION_ERRORS
CREATE TABLE MIGRATION_ERRORS (
    ID INTEGER NOT NULL PRIMARY KEY,
    RUN_ID CHAR(36) NOT NULL REFERENCES MIGRATION_RUNS(ID),
    ENTITY_TYPE SMALLINT,
    SOURCE_ID VARCHAR(50),
    ERROR_MSG BLOB SUB_TYPE TEXT,
    OCCURRED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET TERM ^ ;
CREATE TRIGGER BI_MIGRATION_ERRORS FOR MIGRATION_ERRORS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_MIGRATION_ERRORS_ID, 1);
END^
SET TERM ; ^

COMMIT;
